volumes:
  brewgis_local_postgres_data: {}
  brewgis_local_postgres_data_backups: {}
  brewgis_local_redis_data: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    container_name: brewgis_local_postgres
    volumes:
      - brewgis_local_postgres_data:/var/lib/postgresql/data
      - brewgis_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  redis:
    image: docker.io/redis:6
    container_name: brewgis_local_redis
    volumes:
      - brewgis_local_redis_data:/data
    ports:
      - "6379:6379"

  tipg:
    image: ghcr.io/developmentseed/tipg:latest
    container_name: brewgis_local_tipg
    environment:
      PORT: 8081
      TIPG_DEBUG: "True"
      TIPG_ROOT_PATH: /tipg
      TIPG_DB_SCHEMAS: '["public", "tiger"]'
      DATABASE_URL: postgresql://rADfmsnMjDXKephNGWFkfdPkuSAjdASF:glm5bKLmVKkfdJaM9qkDREdor4y8uSEJZKZvLVwP5jeEX6YSnw6DnNG9EYvupSlg@postgres:5432/brewgis
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  martin:
    image: ghcr.io/maplibre/martin:latest
    container_name: brewgis_local_martin
    command: --base-path /martin
    environment:
      DATABASE_URL: postgresql://rADfmsnMjDXKephNGWFkfdPkuSAjdASF:glm5bKLmVKkfdJaM9qkDREdor4y8uSEJZKZvLVwP5jeEX6YSnw6DnNG9EYvupSlg@postgres:5432/brewgis
    ports:
      - "3000:3000"
    depends_on:
      - postgres
