MODEL (
  name brewgis.@{scenario_schema}.@{model_table},
  kind FULL,
  description 'Transportation CO2e per parcel from VMT and an EPA fleet-average emission factor, daily and annual.',
  column_descriptions (
    parcel_id = 'Parcel identifier from the scenario end state (core_end_state).',
    co2e_total_kg = 'Daily transportation CO2e emissions for the parcel (kg per day), VMT x the emission factor.',
    co2e_annual_kg = 'Annual transportation CO2e for the parcel (kg per year), the daily figure x days per year. The building, water and health models all measure a year, so this is the column they read.',
    co2e_per_capita_kg = 'Daily transportation CO2e emissions per resident (kg per person per day), zero where population is zero.',
    vmt_total = 'Vehicle miles travelled generated by the parcel (miles per day).',
    avg_trip_length_mi = 'Average one-way trip length used by the VMT model (miles).',
    auto_trips = 'Trips made by automobile (trips per day), from the VMT model.',
    geometry = 'Parcel geometry copied from the scenario end state (EPSG:4326).'
  ),
  blueprints @analysis_blueprints('transport_ghg'),
  audits (
    not_null(columns := (parcel_id,)),
    unique_values(columns := (parcel_id,))
  )
);

-- G1 — Transportation GHG
--
-- Computes greenhouse gas emissions (CO2e) from vehicle miles traveled.
-- VMT x emission factor (kg CO2e per mile), with optional speed adjustment.
--
-- Variables:
--   @blueprint_var('transport_ghg_co2_per_mile'): CO2e per mile (default: 0.411 kg/mi — EPA fleet avg).
--   @blueprint_var('transport_ghg_speed_adjust'): Enable speed-based emission adjustment (bool, default: false).
--   @blueprint_var('transport_ghg_days_per_year'): Days a year of travel the annual column stands for (default: 365).

WITH vmt_data AS (
    SELECT
        v.parcel_id,
        v.vmt_total,
        v.avg_trip_length_mi,
        v.auto_trips,
        es.pop,
        es.geometry
    FROM @{scenario_schema}.vmt AS v
    LEFT JOIN @{scenario_schema}.core_end_state AS es
        ON v.parcel_id = es.parcel_id
),

-- The emission factor and its speed adjustment, applied once: both the daily
-- and the annual column are the same figure.
emissions AS (
    SELECT
        parcel_id,
        vmt_total,
        avg_trip_length_mi,
        auto_trips,
        pop,
        geometry,
        vmt_total * @blueprint_var('transport_ghg_co2_per_mile')
        * CASE WHEN @blueprint_var('transport_ghg_speed_adjust') THEN 1.15 ELSE 1.0 END
            AS daily_co2e_kg
    FROM vmt_data
)

SELECT
    parcel_id,

    -- CO2e total (kg/day): VMT x emission factor, with optional speed adjustment
    daily_co2e_kg AS co2e_total_kg,

    -- The same figure over a year. Everything downstream that reports a year
    -- (building and water emissions, health outcomes) consumes this column:
    -- summing a daily figure into a yearly one is the unit mismatch that put
    -- transport at 0.35% of the scenario's greenhouse gases.
    daily_co2e_kg * @blueprint_var('transport_ghg_days_per_year') AS co2e_annual_kg,

    -- CO2e per capita (kg/person/day)
    CASE
        WHEN pop > 0
        THEN daily_co2e_kg / pop
        ELSE 0.0
    END AS co2e_per_capita_kg,

    vmt_total,
    avg_trip_length_mi,
    auto_trips,
    geometry
FROM emissions;

-- post_statements
  CREATE INDEX IF NOT EXISTS @snapshot_hash('idx_transport_ghg_geometry_')
  ON @this_model USING GIST (geometry);

  CREATE INDEX IF NOT EXISTS @snapshot_hash('idx_transport_ghg_parcel_id_')
  ON @this_model USING btree (parcel_id);


-- Publish this model's result view where the Layers, Martin and UI paths read
-- it. The view selects from this model's prod virtual view (never its physical
-- table), so promoting a non-prod environment never repoints it. See
-- sqlmesh/macros/analysis_blueprints.py.
ON_VIRTUAL_UPDATE_BEGIN;

CREATE SCHEMA IF NOT EXISTS "@{result_schema}";

CREATE OR REPLACE VIEW "@{result_schema}"."@{model_table}" AS
SELECT * FROM @{scenario_schema}."@{model_table}";

ON_VIRTUAL_UPDATE_END;
