MODEL (
  name brewgis.comparison.sacog_correlations,
  kind FULL
);

-- SACOG Correlations — per-column Pearson R correlation between brewgis and reference.
--
-- Computes CORR(bc.col, ref.col) for each paired numeric column between
-- the brewgis base_canvas and the v1 reference table, joined on geography_id.

SELECT
    CORR(bc.area_gross, ref.acres_gross) AS area_gross,
    CORR(bc.area_parcel, ref.acres_parcel) AS area_parcel,
    CORR(bc.area_parcel_res_detsf, ref.acres_parcel_res_detsf) AS area_parcel_res_detsf,
    CORR(bc.area_parcel_res_detsf_sl, ref.acres_parcel_res_detsf_sl) AS area_parcel_res_detsf_sl,
    CORR(bc.area_parcel_res_detsf_ll, ref.acres_parcel_res_detsf_ll) AS area_parcel_res_detsf_ll,
    CORR(bc.area_parcel_res_attsf, ref.acres_parcel_res_attsf) AS area_parcel_res_attsf,
    CORR(bc.area_parcel_res_mf, ref.acres_parcel_res_mf) AS area_parcel_res_mf,
    CORR(bc.area_parcel_res, ref.acres_parcel_res) AS area_parcel_res,
    CORR(bc.area_parcel_emp, ref.acres_parcel_emp) AS area_parcel_emp,
    CORR(bc.area_parcel_emp_ret, ref.acres_parcel_emp_ret) AS area_parcel_emp_ret,
    CORR(bc.area_parcel_emp_off, ref.acres_parcel_emp_off) AS area_parcel_emp_off,
    CORR(bc.area_parcel_emp_pub, ref.acres_parcel_emp_pub) AS area_parcel_emp_pub,
    CORR(bc.area_parcel_emp_ind, ref.acres_parcel_emp_ind) AS area_parcel_emp_ind,
    CORR(bc.area_parcel_emp_ag, ref.acres_parcel_emp_ag) AS area_parcel_emp_ag,
    CORR(bc.area_parcel_emp_military, ref.acres_parcel_emp_military) AS area_parcel_emp_military,
    CORR(bc.area_parcel_mixed_use, ref.acres_parcel_mixed_use) AS area_parcel_mixed_use,
    CORR(bc.area_parcel_no_use, ref.acres_parcel_no_use) AS area_parcel_no_use,
    CORR(bc.intersection_density, ref.intersection_density_sqmi) AS intersection_density,
    CORR(bc.pop, ref.pop) AS pop,
    CORR(bc.hh, ref.hh) AS hh,
    CORR(bc.du, ref.du) AS du,
    CORR(bc.du_detsf, ref.du_detsf) AS du_detsf,
    CORR(bc.du_detsf_sl, ref.du_detsf_sl) AS du_detsf_sl,
    CORR(bc.du_detsf_ll, ref.du_detsf_ll) AS du_detsf_ll,
    CORR(bc.du_attsf, ref.du_attsf) AS du_attsf,
    CORR(bc.du_mf, ref.du_mf) AS du_mf,
    CORR(bc.du_mf2to4, ref.du_mf2to4) AS du_mf2to4,
    CORR(bc.du_mf5p, ref.du_mf5p) AS du_mf5p,
    CORR(bc.emp, ref.emp) AS emp,
    CORR(bc.emp_ret, ref.emp_ret) AS emp_ret,
    CORR(bc.emp_retail_services, ref.emp_retail_services) AS emp_retail_services,
    CORR(bc.emp_restaurant, ref.emp_restaurant) AS emp_restaurant,
    CORR(bc.emp_accommodation, ref.emp_accommodation) AS emp_accommodation,
    CORR(bc.emp_arts_entertainment, ref.emp_arts_entertainment) AS emp_arts_entertainment,
    CORR(bc.emp_other_services, ref.emp_other_services) AS emp_other_services,
    CORR(bc.emp_off, ref.emp_off) AS emp_off,
    CORR(bc.emp_office_services, ref.emp_office_services) AS emp_office_services,
    CORR(bc.emp_medical_services, ref.emp_medical_services) AS emp_medical_services,
    CORR(bc.emp_pub, ref.emp_pub) AS emp_pub,
    CORR(bc.emp_public_admin, ref.emp_public_admin) AS emp_public_admin,
    CORR(bc.emp_education, ref.emp_education) AS emp_education,
    CORR(bc.emp_ind, ref.emp_ind) AS emp_ind,
    CORR(bc.emp_manufacturing, ref.emp_manufacturing) AS emp_manufacturing,
    CORR(bc.emp_wholesale, ref.emp_wholesale) AS emp_wholesale,
    CORR(bc.emp_transport_warehousing, ref.emp_transport_warehousing) AS emp_transport_warehousing,
    CORR(bc.emp_utilities, ref.emp_utilities) AS emp_utilities,
    CORR(bc.emp_construction, ref.emp_construction) AS emp_construction,
    CORR(bc.emp_ag, ref.emp_ag) AS emp_ag,
    CORR(bc.emp_agriculture, ref.emp_agriculture) AS emp_agriculture,
    CORR(bc.emp_extraction, ref.emp_extraction) AS emp_extraction,
    CORR(bc.emp_military, ref.emp_military) AS emp_military,
    CORR(bc.bldg_area_detsf_sl, ref.bldg_sqft_detsf_sl) AS bldg_area_detsf_sl,
    CORR(bc.bldg_area_detsf_ll, ref.bldg_sqft_detsf_ll) AS bldg_area_detsf_ll,
    CORR(bc.bldg_area_attsf, ref.bldg_sqft_attsf) AS bldg_area_attsf,
    CORR(bc.bldg_area_mf, ref.bldg_sqft_mf) AS bldg_area_mf,
    CORR(bc.bldg_area_retail_services, ref.bldg_sqft_retail_services) AS bldg_area_retail_services,
    CORR(bc.bldg_area_restaurant, ref.bldg_sqft_restaurant) AS bldg_area_restaurant,
    CORR(bc.bldg_area_accommodation, ref.bldg_sqft_accommodation) AS bldg_area_accommodation,
    CORR(bc.bldg_area_arts_entertainment, ref.bldg_sqft_arts_entertainment) AS bldg_area_arts_entertainment,
    CORR(bc.bldg_area_other_services, ref.bldg_sqft_other_services) AS bldg_area_other_services,
    CORR(bc.bldg_area_office_services, ref.bldg_sqft_office_services) AS bldg_area_office_services,
    CORR(bc.bldg_area_public_admin, ref.bldg_sqft_public_admin) AS bldg_area_public_admin,
    CORR(bc.bldg_area_education, ref.bldg_sqft_education) AS bldg_area_education,
    CORR(bc.bldg_area_medical_services, ref.bldg_sqft_medical_services) AS bldg_area_medical_services,
    CORR(bc.bldg_area_transport_warehousing, ref.bldg_sqft_transport_warehousing) AS bldg_area_transport_warehousing,
    CORR(bc.bldg_area_wholesale, ref.bldg_sqft_wholesale) AS bldg_area_wholesale,
    CORR(bc.residential_irrigated_area, ref.residential_irrigated_sqft) AS residential_irrigated_area,
    CORR(bc.commercial_irrigated_area, ref.commercial_irrigated_sqft) AS commercial_irrigated_area
FROM brewgis.comparison.sacog_brewgis_comparison_view bc
INNER JOIN public.sac_cnty_region_base_canvas ref ON bc.geography_id = ref.geography_id
WHERE bc.geography_id IS NOT NULL
