MODEL (
  name brewgis.comparison.sacog_summary,
  kind VIEW
);

-- SACOG Summary — single-row comparison joining totals, correlations, and weighted means.

WITH ref_totals AS (
    SELECT * FROM brewgis.comparison.sacog_reference_totals
),
brew_totals AS (
    SELECT * FROM brewgis.comparison.sacog_brewgis_totals
),
correlations AS (
    SELECT * FROM brewgis.comparison.sacog_correlations
),
weighted_means AS (
    SELECT * FROM brewgis.comparison.sacog_weighted_means
)
SELECT
    NOW()::timestamp AS generated_at,
    ref.acres_gross AS ref_acres_gross,
    ref.acres_parcel AS ref_acres_parcel,
    ref.acres_parcel_res AS ref_acres_parcel_res,
    ref.acres_parcel_emp AS ref_acres_parcel_emp,
    ref.acres_parcel_mixed_use AS ref_acres_parcel_mixed_use,
    ref.acres_parcel_no_use AS ref_acres_parcel_no_use,
    ref.pop AS ref_pop,
    ref.hh AS ref_hh,
    ref.du AS ref_du,
    ref.du_detsf AS ref_du_detsf,
    ref.du_detsf_sl AS ref_du_detsf_sl,
    ref.du_detsf_ll AS ref_du_detsf_ll,
    ref.du_attsf AS ref_du_attsf,
    ref.du_mf AS ref_du_mf,
    ref.du_mf2to4 AS ref_du_mf2to4,
    ref.du_mf5p AS ref_du_mf5p,
    ref.emp AS ref_emp,
    ref.emp_ret AS ref_emp_ret,
    ref.emp_off AS ref_emp_off,
    ref.emp_pub AS ref_emp_pub,
    ref.emp_ind AS ref_emp_ind,
    ref.emp_ag AS ref_emp_ag,
    ref.emp_military AS ref_emp_military,
    ref.emp_retail_services AS ref_emp_retail_services,
    ref.emp_restaurant AS ref_emp_restaurant,
    ref.emp_accommodation AS ref_emp_accommodation,
    ref.emp_arts_entertainment AS ref_emp_arts_entertainment,
    ref.emp_other_services AS ref_emp_other_services,
    ref.emp_office_services AS ref_emp_office_services,
    ref.emp_medical_services AS ref_emp_medical_services,
    ref.emp_public_admin AS ref_emp_public_admin,
    ref.emp_education AS ref_emp_education,
    ref.emp_manufacturing AS ref_emp_manufacturing,
    ref.emp_wholesale AS ref_emp_wholesale,
    ref.emp_transport_warehousing AS ref_emp_transport_warehousing,
    ref.emp_utilities AS ref_emp_utilities,
    ref.emp_construction AS ref_emp_construction,
    ref.emp_agriculture AS ref_emp_agriculture,
    ref.emp_extraction AS ref_emp_extraction,
    ref.bldg_sqft_detsf_sl AS ref_bldg_sqft_detsf_sl,
    ref.bldg_sqft_detsf_ll AS ref_bldg_sqft_detsf_ll,
    ref.bldg_sqft_attsf AS ref_bldg_sqft_attsf,
    ref.bldg_sqft_mf AS ref_bldg_sqft_mf,
    ref.bldg_sqft_retail_services AS ref_bldg_sqft_retail_services,
    ref.bldg_sqft_restaurant AS ref_bldg_sqft_restaurant,
    ref.bldg_sqft_accommodation AS ref_bldg_sqft_accommodation,
    ref.bldg_sqft_arts_entertainment AS ref_bldg_sqft_arts_entertainment,
    ref.bldg_sqft_other_services AS ref_bldg_sqft_other_services,
    ref.bldg_sqft_office_services AS ref_bldg_sqft_office_services,
    ref.bldg_sqft_public_admin AS ref_bldg_sqft_public_admin,
    ref.bldg_sqft_education AS ref_bldg_sqft_education,
    ref.bldg_sqft_medical_services AS ref_bldg_sqft_medical_services,
    ref.bldg_sqft_transport_warehousing AS ref_bldg_sqft_transport_warehousing,
    ref.bldg_sqft_wholesale AS ref_bldg_sqft_wholesale,
    ref.residential_irrigated_sqft AS ref_residential_irrigated_sqft,
    ref.commercial_irrigated_sqft AS ref_commercial_irrigated_sqft,
    ref.intersection_density_sqmi AS ref_intersection_density_sqmi,
    brew.area_gross_acres AS brew_area_gross_acres,
    brew.area_parcel_acres AS brew_area_parcel_acres,
    brew.area_parcel_res_acres AS brew_area_parcel_res_acres,
    brew.area_parcel_emp_acres AS brew_area_parcel_emp_acres,
    brew.area_parcel_mixed_use_acres AS brew_area_parcel_mixed_use_acres,
    brew.area_parcel_no_use_acres AS brew_area_parcel_no_use_acres,
    brew.pop AS brew_pop,
    brew.hh AS brew_hh,
    brew.du AS brew_du,
    brew.du_detsf AS brew_du_detsf,
    brew.du_detsf_sl AS brew_du_detsf_sl,
    brew.du_detsf_ll AS brew_du_detsf_ll,
    brew.du_attsf AS brew_du_attsf,
    brew.du_mf AS brew_du_mf,
    brew.du_mf2to4 AS brew_du_mf2to4,
    brew.du_mf5p AS brew_du_mf5p,
    brew.emp AS brew_emp,
    brew.emp_ret AS brew_emp_ret,
    brew.emp_off AS brew_emp_off,
    brew.emp_pub AS brew_emp_pub,
    brew.emp_ind AS brew_emp_ind,
    brew.emp_ag AS brew_emp_ag,
    brew.emp_military AS brew_emp_military,
    brew.emp_retail_services AS brew_emp_retail_services,
    brew.emp_restaurant AS brew_emp_restaurant,
    brew.emp_accommodation AS brew_emp_accommodation,
    brew.emp_arts_entertainment AS brew_emp_arts_entertainment,
    brew.emp_other_services AS brew_emp_other_services,
    brew.emp_office_services AS brew_emp_office_services,
    brew.emp_medical_services AS brew_emp_medical_services,
    brew.emp_public_admin AS brew_emp_public_admin,
    brew.emp_education AS brew_emp_education,
    brew.emp_manufacturing AS brew_emp_manufacturing,
    brew.emp_wholesale AS brew_emp_wholesale,
    brew.emp_transport_warehousing AS brew_emp_transport_warehousing,
    brew.emp_utilities AS brew_emp_utilities,
    brew.emp_construction AS brew_emp_construction,
    brew.emp_agriculture AS brew_emp_agriculture,
    brew.emp_extraction AS brew_emp_extraction,
    brew.bldg_area_detsf_sl AS brew_bldg_area_detsf_sl,
    brew.bldg_area_detsf_ll AS brew_bldg_area_detsf_ll,
    brew.bldg_area_attsf AS brew_bldg_area_attsf,
    brew.bldg_area_mf AS brew_bldg_area_mf,
    brew.bldg_area_retail_services AS brew_bldg_area_retail_services,
    brew.bldg_area_restaurant AS brew_bldg_area_restaurant,
    brew.bldg_area_accommodation AS brew_bldg_area_accommodation,
    brew.bldg_area_arts_entertainment AS brew_bldg_area_arts_entertainment,
    brew.bldg_area_other_services AS brew_bldg_area_other_services,
    brew.bldg_area_office_services AS brew_bldg_area_office_services,
    brew.bldg_area_public_admin AS brew_bldg_area_public_admin,
    brew.bldg_area_education AS brew_bldg_area_education,
    brew.bldg_area_medical_services AS brew_bldg_area_medical_services,
    brew.bldg_area_transport_warehousing AS brew_bldg_area_transport_warehousing,
    brew.bldg_area_wholesale AS brew_bldg_area_wholesale,
    brew.residential_irrigated_area AS brew_residential_irrigated_area,
    brew.commercial_irrigated_area AS brew_commercial_irrigated_area,
    brew.intersection_density AS brew_intersection_density,
    brew.median_income AS brew_median_income,
    brew.pct_minority AS brew_pct_minority,
    brew.pct_college_educated AS brew_pct_college_educated,
    brew.cost_burden_pct AS brew_cost_burden_pct,
    brew.rent_burden_pct AS brew_rent_burden_pct,
    corr.area_gross AS corr_area_gross,
    corr.area_parcel AS corr_area_parcel,
    corr.area_parcel_res_detsf AS corr_area_parcel_res_detsf,
    corr.area_parcel_res_detsf_sl AS corr_area_parcel_res_detsf_sl,
    corr.area_parcel_res_detsf_ll AS corr_area_parcel_res_detsf_ll,
    corr.area_parcel_res_attsf AS corr_area_parcel_res_attsf,
    corr.area_parcel_res_mf AS corr_area_parcel_res_mf,
    corr.area_parcel_res AS corr_area_parcel_res,
    corr.area_parcel_emp AS corr_area_parcel_emp,
    corr.area_parcel_emp_ret AS corr_area_parcel_emp_ret,
    corr.area_parcel_emp_off AS corr_area_parcel_emp_off,
    corr.area_parcel_emp_pub AS corr_area_parcel_emp_pub,
    corr.area_parcel_emp_ind AS corr_area_parcel_emp_ind,
    corr.area_parcel_emp_ag AS corr_area_parcel_emp_ag,
    corr.area_parcel_emp_military AS corr_area_parcel_emp_military,
    corr.area_parcel_mixed_use AS corr_area_parcel_mixed_use,
    corr.area_parcel_no_use AS corr_area_parcel_no_use,
    corr.intersection_density AS corr_intersection_density,
    corr.pop AS corr_pop,
    corr.hh AS corr_hh,
    corr.du AS corr_du,
    corr.du_detsf AS corr_du_detsf,
    corr.du_detsf_sl AS corr_du_detsf_sl,
    corr.du_detsf_ll AS corr_du_detsf_ll,
    corr.du_attsf AS corr_du_attsf,
    corr.du_mf AS corr_du_mf,
    corr.du_mf2to4 AS corr_du_mf2to4,
    corr.du_mf5p AS corr_du_mf5p,
    corr.emp AS corr_emp,
    corr.emp_ret AS corr_emp_ret,
    corr.emp_retail_services AS corr_emp_retail_services,
    corr.emp_restaurant AS corr_emp_restaurant,
    corr.emp_accommodation AS corr_emp_accommodation,
    corr.emp_arts_entertainment AS corr_emp_arts_entertainment,
    corr.emp_other_services AS corr_emp_other_services,
    corr.emp_off AS corr_emp_off,
    corr.emp_office_services AS corr_emp_office_services,
    corr.emp_medical_services AS corr_emp_medical_services,
    corr.emp_pub AS corr_emp_pub,
    corr.emp_public_admin AS corr_emp_public_admin,
    corr.emp_education AS corr_emp_education,
    corr.emp_ind AS corr_emp_ind,
    corr.emp_manufacturing AS corr_emp_manufacturing,
    corr.emp_wholesale AS corr_emp_wholesale,
    corr.emp_transport_warehousing AS corr_emp_transport_warehousing,
    corr.emp_utilities AS corr_emp_utilities,
    corr.emp_construction AS corr_emp_construction,
    corr.emp_ag AS corr_emp_ag,
    corr.emp_agriculture AS corr_emp_agriculture,
    corr.emp_extraction AS corr_emp_extraction,
    corr.emp_military AS corr_emp_military,
    corr.bldg_area_detsf_sl AS corr_bldg_area_detsf_sl,
    corr.bldg_area_detsf_ll AS corr_bldg_area_detsf_ll,
    corr.bldg_area_attsf AS corr_bldg_area_attsf,
    corr.bldg_area_mf AS corr_bldg_area_mf,
    corr.bldg_area_retail_services AS corr_bldg_area_retail_services,
    corr.bldg_area_restaurant AS corr_bldg_area_restaurant,
    corr.bldg_area_accommodation AS corr_bldg_area_accommodation,
    corr.bldg_area_arts_entertainment AS corr_bldg_area_arts_entertainment,
    corr.bldg_area_other_services AS corr_bldg_area_other_services,
    corr.bldg_area_office_services AS corr_bldg_area_office_services,
    corr.bldg_area_public_admin AS corr_bldg_area_public_admin,
    corr.bldg_area_education AS corr_bldg_area_education,
    corr.bldg_area_medical_services AS corr_bldg_area_medical_services,
    corr.bldg_area_transport_warehousing AS corr_bldg_area_transport_warehousing,
    corr.bldg_area_wholesale AS corr_bldg_area_wholesale,
    corr.residential_irrigated_area AS corr_residential_irrigated_area,
    corr.commercial_irrigated_area AS corr_commercial_irrigated_area,
    wavg.median_income_wavg,
    wavg.pct_minority_wavg,
    wavg.pct_college_educated_wavg,
    wavg.cost_burden_pct_wavg,
    wavg.rent_burden_pct_wavg
FROM ref_totals ref
CROSS JOIN brew_totals brew
CROSS JOIN correlations corr
CROSS JOIN weighted_means wavg
