MODEL (
  name brewgis.@{scenario_schema}.@{model_table},
  kind FULL,
  description 'Agricultural production and return estimates for parcels with agricultural or rural development.',
  column_descriptions (
    parcel_id = 'Assessor parcel number (APN) of the parcel.',
    crop_type = 'Crop type label, fixed to general_agriculture in this model.',
    acres_cultivated = 'Cultivated acres: agricultural acres, else developed rural acres (acres).',
    crop_yield_tons = 'Crop yield from cultivated acres at the configured rate (tons).',
    market_value = 'Gross market value of the yield at the configured price ($).',
    production_cost = 'Production cost of the cultivated acres at the configured rate ($).',
    net_return = 'Market value minus production cost ($).',
    water_consumption_af = 'Irrigation water use of the cultivated acres (acre-feet).',
    labor_hours = 'Farm labour required by the cultivated acres (hours).',
    truck_trips = 'Farm truck trips generated by the cultivated acres (trips).',
    geometry = 'Parcel boundary geometry (EPSG:4326).'
  ),
  blueprints @analysis_blueprints('agriculture'),
);

SELECT
    es.parcel_id,
    -- Crop type: inferred from available data; default to "general_agriculture"
    'general_agriculture' AS crop_type,
    -- Acres cultivated: use parcel_acres_agriculture, or acres_developed as proxy for rural parcels
    CASE
        WHEN es.parcel_acres_agriculture > 0 THEN es.parcel_acres_agriculture
        WHEN es.land_development_category = 'rural' AND es.acres_developed > 0
            THEN es.acres_developed
        ELSE 0.0
    END AS acres_cultivated,
    -- Crop yield (tons)
    CASE
        WHEN es.parcel_acres_agriculture > 0
            THEN es.parcel_acres_agriculture * @crop_yield_per_acre
        WHEN es.land_development_category = 'rural' AND es.acres_developed > 0
            THEN es.acres_developed * @crop_yield_per_acre
        ELSE 0.0
    END AS crop_yield_tons,
    -- Market value
    CASE
        WHEN es.parcel_acres_agriculture > 0
            THEN es.parcel_acres_agriculture * @crop_yield_per_acre * @crop_market_price_per_ton
        WHEN es.land_development_category = 'rural' AND es.acres_developed > 0
            THEN es.acres_developed * @crop_yield_per_acre * @crop_market_price_per_ton
        ELSE 0.0
    END AS market_value,
    -- Production cost
    CASE
        WHEN es.parcel_acres_agriculture > 0
            THEN es.parcel_acres_agriculture * @crop_production_cost_per_acre
        WHEN es.land_development_category = 'rural' AND es.acres_developed > 0
            THEN es.acres_developed * @crop_production_cost_per_acre
        ELSE 0.0
    END AS production_cost,
    -- Net return = market_value - production_cost
    CASE
        WHEN es.parcel_acres_agriculture > 0
            THEN es.parcel_acres_agriculture * @crop_yield_per_acre * @crop_market_price_per_ton
                 - es.parcel_acres_agriculture * @crop_production_cost_per_acre
        WHEN es.land_development_category = 'rural' AND es.acres_developed > 0
            THEN es.acres_developed * @crop_yield_per_acre * @crop_market_price_per_ton
                 - es.acres_developed * @crop_production_cost_per_acre
        ELSE 0.0
    END AS net_return,
    -- Water consumption (acre-feet)
    CASE
        WHEN es.parcel_acres_agriculture > 0
            THEN es.parcel_acres_agriculture * @crop_water_per_acre_af
        WHEN es.land_development_category = 'rural' AND es.acres_developed > 0
            THEN es.acres_developed * @crop_water_per_acre_af
        ELSE 0.0
    END AS water_consumption_af,
    -- Labor hours
    CASE
        WHEN es.parcel_acres_agriculture > 0
            THEN es.parcel_acres_agriculture * @crop_labor_hours_per_acre
        WHEN es.land_development_category = 'rural' AND es.acres_developed > 0
            THEN es.acres_developed * @crop_labor_hours_per_acre
        ELSE 0.0
    END AS labor_hours,
    -- Truck trips
    CASE
        WHEN es.parcel_acres_agriculture > 0
            THEN es.parcel_acres_agriculture * @crop_truck_trips_per_acre
        WHEN es.land_development_category = 'rural' AND es.acres_developed > 0
            THEN es.acres_developed * @crop_truck_trips_per_acre
        ELSE 0.0
    END AS truck_trips,
    es.geometry
FROM @{scenario_schema}.core_end_state AS es
WHERE
    es.parcel_acres_agriculture > 0
    OR (es.land_development_category = 'rural' AND es.acres_developed > 0);


-- ------------------------------------------------------------
-- Stormwater Runoff (S1)
--   Estimates stormwater runoff volume changes from land use
--   change and impervious surface increase using the Simple
--   Method (Schueler, 1987).
-- Source (dbt): brewgis/dbt_project/models/stormwater_runoff.sql
-- ------------------------------------------------------------

-- post_statements
  CREATE INDEX IF NOT EXISTS @snapshot_hash('idx_agriculture_geometry_')
  ON @this_model USING GIST (geometry);
  CREATE INDEX IF NOT EXISTS @snapshot_hash('idx_agriculture_parcel_id_')
  ON @this_model USING btree (parcel_id);
ANALYZE @this_model;


-- Publish this model's result view where the Layers, Martin and UI paths read
-- it. The view selects from this model's prod virtual view (never its physical
-- table), so promoting a non-prod environment never repoints it. See
-- sqlmesh/macros/analysis_blueprints.py.
ON_VIRTUAL_UPDATE_BEGIN;

CREATE SCHEMA IF NOT EXISTS "@{result_schema}";

CREATE OR REPLACE VIEW "@{result_schema}"."@{model_table}" AS
SELECT * FROM @{scenario_schema}."@{model_table}";

ON_VIRTUAL_UPDATE_END;
