MODEL (
  name brewgis.@{region}.base_canvas_reconciled,
  kind VIEW,
  description 'Parcel-level end state of the base canvas: base_canvas_imputed with aggregate DU and employment columns recomputed from their sub-column parts.',
  column_descriptions (
    parcel_id = 'Unique parcel identifier; one row per parcel in the base canvas.',
    geometry_key = 'Parcel identifier reused as the geometry join key (alias of parcel_id).',
    id_source = 'Always NULL in this model; placeholder for the upstream ID source label.',
    geography_id = 'Always NULL in this model; placeholder for a resolved geography identifier.',
    geometry = 'Parcel boundary geometry (MultiPolygon, EPSG:4326).',
    county = 'County the parcel falls in, carried from the parcel source.',
    land_development_category = 'Land development category carried from base_canvas_imputed.',
    built_form_key = 'Built form key describing the development pattern of the parcel.',
    intersection_density = 'Intersection density carried from base_canvas_imputed (intersections per km2).',
    area_gross = 'Gross parcel area including right-of-way (acres).',
    area_gross_acres = 'Gross parcel area including right-of-way (acres, explicit unit alias of area_gross).',
    area_parcel_acres = 'Parcel area inside the parcel boundary (acres).',
    area_parcel = 'Parcel area inside the parcel boundary (acres, alias of area_parcel_acres).',
    area_dev_condition_acres = 'Portion of the parcel in developed condition (acres).',
    area_dev_condition = 'Portion of the parcel in developed condition (acres, alias of area_dev_condition_acres).',
    area_row_acres = 'Portion of the parcel in public right-of-way (acres).',
    area_row = 'Portion of the parcel in public right-of-way (acres, alias of area_row_acres).',
    area_parcel_res = 'Total residential parcel area (acres).',
    area_parcel_res_acres = 'Total residential parcel area (acres, explicit unit alias of area_parcel_res).',
    area_parcel_res_detsf = 'Detached single-family parcel area (acres); zero placeholder, not allocated yet.',
    area_parcel_res_detsf_sl = 'Detached single-family small-lot parcel area (acres); zero placeholder.',
    area_parcel_res_detsf_ll = 'Detached single-family large-lot parcel area (acres); zero placeholder.',
    area_parcel_res_attsf = 'Attached single-family parcel area (acres); zero placeholder, not allocated yet.',
    area_parcel_res_mf = 'Multi-family parcel area (acres); zero placeholder, not allocated yet.',
    area_parcel_emp_ag = 'Agricultural employment parcel area (acres).',
    area_parcel_emp_ag_acres = 'Agricultural employment parcel area (acres, alias of area_parcel_emp_ag).',
    area_parcel_emp = 'Total employment parcel area (acres).',
    area_parcel_emp_acres = 'Total employment parcel area (acres, explicit unit alias of area_parcel_emp).',
    area_parcel_emp_ret = 'Retail employment parcel area (acres); zero placeholder, not allocated yet.',
    area_parcel_emp_off = 'Office employment parcel area (acres); zero placeholder, not allocated yet.',
    area_parcel_emp_pub = 'Public employment parcel area (acres); zero placeholder, not allocated yet.',
    area_parcel_emp_ind = 'Industrial employment parcel area (acres); zero placeholder, not allocated yet.',
    area_parcel_emp_military = 'Military employment parcel area (acres); zero placeholder, not allocated yet.',
    area_parcel_mixed_use = 'Mixed-use parcel area (acres).',
    area_parcel_mixed_use_acres = 'Mixed-use parcel area (acres, explicit unit alias of area_parcel_mixed_use).',
    area_parcel_no_use = 'Parcel area with no assigned use (acres).',
    area_parcel_no_use_acres = 'Parcel area with no assigned use (acres, explicit unit alias of area_parcel_no_use).',
    land_use = 'Land use label from the parcel source, matched against the regional land use crosswalk.',
    assessor_use_code = 'Assessor use code from the parcel source, matched on its first two digits.',
    pop = 'Total population carried from base_canvas_imputed (people).',
    pop_groupquarter = 'Group quarters population carried from base_canvas_imputed (people).',
    hh = 'Households carried from base_canvas_imputed (count).',
    du = 'Total dwelling units from base_canvas_imputed, the total the subtypes are scaled to (count).',
    du_detsf_sl = 'Detached single-family small-lot dwelling units scaled so subtypes sum to du (count).',
    du_detsf_ll = 'Detached single-family large-lot dwelling units scaled so subtypes sum to du (count).',
    du_detsf = 'Detached single-family dwelling units (small plus large lot) scaled so subtypes sum to du (count).',
    du_attsf = 'Attached single-family dwelling units scaled so subtypes sum to du (count).',
    du_mf2to4 = 'Multi-family 2-4 unit dwelling units scaled so subtypes sum to du (count).',
    du_mf5p = 'Multi-family 5+ unit dwelling units scaled so subtypes sum to du (count).',
    du_mf = 'Multi-family dwelling units (2-4 plus 5+ unit) scaled so subtypes sum to du (count).',
    du_subtype = 'Dwelling unit subtype key assigned to the parcel.',
    is_residential = 'Flag marking the parcel as residential.',
    residential_building_sqft = 'Residential building floor area carried from base_canvas_imputed (sq ft).',
    commercial_building_sqft = 'Commercial building floor area carried from base_canvas_imputed (sq ft).',
    industrial_building_sqft = 'Industrial building floor area carried from base_canvas_imputed (sq ft).',
    other_building_sqft = 'Other building floor area carried from base_canvas_imputed (sq ft).',
    total_footprint_sqft = 'Total building footprint area carried from base_canvas_imputed (sq ft).',
    building_count = 'Number of buildings on the parcel, carried from base_canvas_imputed (count).',
    footprint_ratio = 'Building footprint share of parcel area, carried from base_canvas_imputed (ratio, 0-1).',
    max_levels = 'Maximum building levels on the parcel, carried from base_canvas_imputed (count).',
    emp_ret = 'Retail employment recomputed as the sum of the five retail sub-sectors (jobs).',
    emp_retail_services = 'Retail services employment carried from base_canvas_imputed (jobs).',
    emp_restaurant = 'Restaurant employment carried from base_canvas_imputed (jobs).',
    emp_accommodation = 'Accommodation employment carried from base_canvas_imputed (jobs).',
    emp_arts_entertainment = 'Arts and entertainment employment carried from base_canvas_imputed (jobs).',
    emp_other_services = 'Other services employment carried from base_canvas_imputed (jobs).',
    emp_off = 'Office employment recomputed as office services plus medical services (jobs).',
    emp_office_services = 'Office services employment carried from base_canvas_imputed (jobs).',
    emp_medical_services = 'Medical services employment carried from base_canvas_imputed (jobs).',
    emp_pub = 'Public employment recomputed as public administration plus education (jobs).',
    emp_public_admin = 'Public administration employment carried from base_canvas_imputed (jobs).',
    emp_education = 'Education employment carried from base_canvas_imputed (jobs).',
    emp_ind = 'Industrial employment recomputed as the sum of its five sub-sectors (jobs).',
    emp_manufacturing = 'Manufacturing employment carried from base_canvas_imputed (jobs).',
    emp_wholesale = 'Wholesale employment carried from base_canvas_imputed (jobs).',
    emp_transport_warehousing = 'Transport and warehousing employment carried from base_canvas_imputed (jobs).',
    emp_utilities = 'Utilities employment carried from base_canvas_imputed (jobs).',
    emp_construction = 'Construction employment carried from base_canvas_imputed (jobs).',
    emp_ag = 'Agricultural employment recomputed as agriculture plus extraction (jobs).',
    emp_agriculture = 'Agriculture employment carried from base_canvas_imputed (jobs).',
    emp_extraction = 'Extraction employment carried from base_canvas_imputed (jobs).',
    emp = 'Total employment recomputed as the sum of the six sector groups (jobs).',
    emp_military = 'Military employment carried from base_canvas_imputed (jobs).',
    bldg_area_detsf_sl = 'Detached single-family small-lot building floor area (sq ft).',
    bldg_area_detsf_ll = 'Detached single-family large-lot building floor area (sq ft).',
    bldg_area_attsf = 'Attached single-family building floor area carried from base_canvas_imputed (sq ft).',
    bldg_area_mf = 'Multi-family building floor area carried from base_canvas_imputed (sq ft).',
    bldg_area_retail_services = 'Retail services building floor area carried from base_canvas_imputed (sq ft).',
    bldg_area_restaurant = 'Restaurant building floor area carried from base_canvas_imputed (sq ft).',
    bldg_area_accommodation = 'Accommodation building floor area carried from base_canvas_imputed (sq ft).',
    bldg_area_arts_entertainment = 'Arts and entertainment building floor area (sq ft).',
    bldg_area_other_services = 'Other services building floor area carried from base_canvas_imputed (sq ft).',
    bldg_area_office_services = 'Office services building floor area carried from base_canvas_imputed (sq ft).',
    bldg_area_public_admin = 'Public administration building floor area carried from base_canvas_imputed (sq ft).',
    bldg_area_education = 'Education building floor area carried from base_canvas_imputed (sq ft).',
    bldg_area_medical_services = 'Medical services building floor area carried from base_canvas_imputed (sq ft).',
    bldg_area_transport_warehousing = 'Transport and warehousing building floor area (sq ft).',
    bldg_area_wholesale = 'Wholesale building floor area carried from base_canvas_imputed (sq ft).',
    residential_irrigated_area = 'Residential irrigated area carried from base_canvas_imputed (acres).',
    commercial_irrigated_area = 'Commercial irrigated area carried from base_canvas_imputed (acres).',
    median_income = 'Median household income carried from base_canvas_imputed ($ per year).',
    rent_burden_pct = 'Rent-burdened household share carried from base_canvas_imputed (% as 0-100).',
    pct_minority = 'Share of people of color carried from base_canvas_imputed (% as 0-100).',
    pct_college_educated = 'College-educated adult share carried from base_canvas_imputed (% as 0-100).',
    cost_burden_pct = 'Cost-burdened household share carried from base_canvas_imputed (% as 0-100).',
    vacancy_rate = 'Housing vacancy rate carried from base_canvas_imputed (ratio, 0-1).',
    occupied_du = 'Occupied dwelling units carried from base_canvas_imputed (count).'
  ),
  audits (
    assert_du_subtype_sum_equals_du,
    is_base_canvas_compatible
  ),
  blueprints @region_blueprints()
);

-- Base Canvas Reconciled — recompute aggregate columns from sub-columns.
--
-- Reads from base_canvas_imputed and ensures that aggregate columns
-- equal the sum of their constituent sub-columns.
--
-- This is the final base_canvas equivalent — the end state of the
-- full 11-step ETL pipeline.

WITH imputed AS (
    SELECT * FROM brewgis.@{region}.base_canvas_imputed
),

-- Recompute DU sub-types proportionally to fit the total du.
-- With methodology Section 5, du_subtype is one-hot from built_form_key,
-- so reconciliation should scale proportionally within each subtype.
du_reconciled AS (
    SELECT
        *,
        (du_detsf_sl + du_detsf_ll) AS raw_detsf,
        (du_mf2to4 + du_mf5p) AS raw_mf,
        CASE
            WHEN COALESCE(du_detsf_sl + du_detsf_ll + du_attsf + du_mf2to4 + du_mf5p, 0) = 0 THEN 1.0
            ELSE du / NULLIF(du_detsf_sl + du_detsf_ll + du_attsf + du_mf2to4 + du_mf5p, 0)
        END AS du_scale
    FROM imputed
)

SELECT
    parcel_id,
    parcel_id AS geometry_key,
    NULL::text AS id_source,
    NULL::integer AS geography_id,
    geometry,
    county,
    land_development_category,
    built_form_key,
    intersection_density,
    area_gross,
    area_gross_acres,
    area_parcel_acres,
    area_parcel_acres AS area_parcel,
    area_dev_condition_acres,
    area_dev_condition_acres AS area_dev_condition,
    area_row_acres,
    area_row_acres AS area_row,
    area_parcel_res,
    area_parcel_res_acres,
    -- Residential sub-type area breakdown is not yet allocated by this
    -- pipeline (the legacy Python ETL never populated it either) — these
    -- are explicit zero placeholders, not real per-subtype allocations.
    0.0::double precision AS area_parcel_res_detsf,
    0.0::double precision AS area_parcel_res_detsf_sl,
    0.0::double precision AS area_parcel_res_detsf_ll,
    0.0::double precision AS area_parcel_res_attsf,
    0.0::double precision AS area_parcel_res_mf,
    area_parcel_emp_ag,
    area_parcel_emp_ag_acres,
    area_parcel_emp,
    area_parcel_emp_acres,
    -- Employment sub-type area breakdown — same caveat as residential above.
    0.0::double precision AS area_parcel_emp_ret,
    0.0::double precision AS area_parcel_emp_off,
    0.0::double precision AS area_parcel_emp_pub,
    0.0::double precision AS area_parcel_emp_ind,
    0.0::double precision AS area_parcel_emp_military,
    area_parcel_mixed_use,
    area_parcel_mixed_use_acres,
    area_parcel_no_use,
    area_parcel_no_use_acres,
    land_use,
    assessor_use_code,
    pop,
    pop_groupquarter,
    hh,
    du AS du,
    ROUND((COALESCE(du_detsf_sl, 0) * du_scale)::numeric, 4) AS du_detsf_sl,
    ROUND((COALESCE(du_detsf_ll, 0) * du_scale)::numeric, 4) AS du_detsf_ll,
    ROUND((COALESCE(raw_detsf, 0) * du_scale)::numeric, 4) AS du_detsf,
    ROUND((COALESCE(du_attsf, 0) * du_scale)::numeric, 4) AS du_attsf,
    ROUND((COALESCE(du_mf2to4, 0) * du_scale)::numeric, 4) AS du_mf2to4,
    ROUND((COALESCE(du_mf5p, 0) * du_scale)::numeric, 4) AS du_mf5p,
    ROUND((COALESCE(raw_mf, 0) * du_scale)::numeric, 4) AS du_mf,
    du_subtype,
    is_residential,
    residential_building_sqft,
    commercial_building_sqft,
    industrial_building_sqft,
    other_building_sqft,
    total_footprint_sqft,
    building_count,
    footprint_ratio,
    max_levels,
    COALESCE(emp_retail_services, 0) + COALESCE(emp_restaurant, 0)
        + COALESCE(emp_accommodation, 0) + COALESCE(emp_arts_entertainment, 0)
        + COALESCE(emp_other_services, 0) AS emp_ret,
    emp_retail_services,
    emp_restaurant,
    emp_accommodation,
    emp_arts_entertainment,
    emp_other_services,
    COALESCE(emp_office_services, 0) + COALESCE(emp_medical_services, 0) AS emp_off,
    emp_office_services,
    emp_medical_services,
    COALESCE(emp_public_admin, 0) + COALESCE(emp_education, 0) AS emp_pub,
    emp_public_admin,
    emp_education,
    COALESCE(emp_manufacturing, 0) + COALESCE(emp_wholesale, 0)
        + COALESCE(emp_transport_warehousing, 0) + COALESCE(emp_utilities, 0)
        + COALESCE(emp_construction, 0) AS emp_ind,
    emp_manufacturing,
    emp_wholesale,
    emp_transport_warehousing,
    emp_utilities,
    emp_construction,
    COALESCE(emp_agriculture, 0) + COALESCE(emp_extraction, 0) AS emp_ag,
    emp_agriculture,
    emp_extraction,
    COALESCE(emp_ret, 0) + COALESCE(emp_off, 0) + COALESCE(emp_pub, 0)
        + COALESCE(emp_ind, 0) + COALESCE(emp_ag, 0) + COALESCE(emp_military, 0) AS emp,
    emp_military,
    bldg_area_detsf_sl,
    bldg_area_detsf_ll,
    bldg_area_attsf,
    bldg_area_mf,
    bldg_area_retail_services,
    bldg_area_restaurant,
    bldg_area_accommodation,
    bldg_area_arts_entertainment,
    bldg_area_other_services,
    bldg_area_office_services,
    bldg_area_public_admin,
    bldg_area_education,
    bldg_area_medical_services,
    bldg_area_transport_warehousing,
    bldg_area_wholesale,
    residential_irrigated_area,
    commercial_irrigated_area,
    median_income,
    rent_burden_pct,
    pct_minority,
    pct_college_educated,
    cost_burden_pct,
    vacancy_rate,
    occupied_du
FROM du_reconciled;
