MODEL (
  name brewgis.tests.stage_test_parcels_base_canvas,
  kind VIEW,
  description 'Test fixture for the base_canvas_combined unit test: base canvas VIEW over the test_parcels seed.',
  column_descriptions (
    parcel_id = 'Parcel identifier passed through from the test_parcels seed.',
    id_source = 'Name of the source dataset the parcel identifier came from (ID Source).',
    geometry_key = 'Stable key identifying the parcel geometry (Geometry Key).',
    geometry = 'Parcel geometry passed through from the test_parcels seed (EPSG:4326).',
    land_development_category = 'Land development category, hard-coded to standard for every parcel in this fixture.',
    built_form_key = 'Built form key, hard-coded to 2 for every parcel in this fixture.',
    intersection_density = 'Intersection density from seed geometry area (per km2), clamped between 0.5 and 25.',
    area_gross = 'Gross parcel area (acres), ST_Area of the seed geometry divided by 4046.86.',
    area_parcel = 'Parcel area (acres).',
    area_dev_condition = 'Area of the parcel in developed condition (acres).',
    area_row = 'Right-of-way area (acres).',
    area_parcel_res_detsf = 'Residential detached single-family parcel area (acres).',
    area_parcel_res_detsf_sl = 'Residential detached single-family small lot parcel area (acres).',
    area_parcel_res_detsf_ll = 'Residential detached single-family large lot parcel area (acres).',
    area_parcel_res_attsf = 'Residential attached single-family parcel area (acres).',
    area_parcel_res_mf = 'Residential multi-family parcel area (acres).',
    area_parcel_res = 'Total residential parcel area (acres).',
    area_parcel_emp = 'Total employment parcel area (acres).',
    area_parcel_emp_ret = 'Retail employment parcel area (acres).',
    area_parcel_emp_off = 'Office employment parcel area (acres).',
    area_parcel_emp_pub = 'Public employment parcel area (acres).',
    area_parcel_emp_ind = 'Industrial employment parcel area (acres).',
    area_parcel_emp_ag = 'Agricultural employment parcel area (acres).',
    area_parcel_emp_military = 'Military parcel area (acres).',
    area_parcel_mixed_use = 'Mixed use parcel area (acres).',
    area_parcel_no_use = 'No use parcel area (acres).',
    pop = 'Population (people) assigned to the parcel.',
    pop_groupquarter = 'Group quarters population (people).',
    hh = 'Households (count) in the parcel.',
    du = 'Dwelling units (count) in the parcel.',
    du_detsf = 'Detached single-family dwelling units (count).',
    du_detsf_sl = 'Detached single-family small lot dwelling units (count).',
    du_detsf_ll = 'Detached single-family large lot dwelling units (count).',
    du_attsf = 'Attached single-family dwelling units (count).',
    du_mf = 'Multi-family dwelling units (count).',
    du_mf2to4 = 'Multi-family 2 to 4 unit dwelling units (count).',
    du_mf5p = 'Multi-family 5 plus unit dwelling units (count).',
    emp = 'Total employment (jobs) attributed to the parcel.',
    emp_ret = 'Retail employment total (jobs).',
    emp_retail_services = 'Retail services employment (jobs).',
    emp_restaurant = 'Restaurant employment (jobs).',
    emp_accommodation = 'Accommodation employment (jobs).',
    emp_arts_entertainment = 'Arts and entertainment employment (jobs).',
    emp_other_services = 'Other services employment (jobs).',
    emp_off = 'Office employment total (jobs).',
    emp_office_services = 'Office services employment (jobs).',
    emp_medical_services = 'Medical services employment (jobs).',
    emp_pub = 'Public employment total (jobs).',
    emp_public_admin = 'Public administration employment (jobs).',
    emp_education = 'Education employment (jobs).',
    emp_ind = 'Industrial employment total (jobs).',
    emp_manufacturing = 'Manufacturing employment (jobs).',
    emp_wholesale = 'Wholesale employment (jobs).',
    emp_transport_warehousing = 'Transport and warehousing employment (jobs).',
    emp_utilities = 'Utilities employment (jobs).',
    emp_construction = 'Construction employment (jobs).',
    emp_ag = 'Agricultural employment total (jobs).',
    emp_agriculture = 'Agriculture employment, detailed category (jobs).',
    emp_extraction = 'Extraction employment (jobs).',
    emp_military = 'Military employment (jobs).',
    bldg_area_detsf_sl = 'Building area for detached single-family small lot dwellings (sq ft).',
    bldg_area_detsf_ll = 'Building area for detached single-family large lot dwellings (sq ft).',
    bldg_area_attsf = 'Building area for attached single-family dwellings (sq ft).',
    bldg_area_mf = 'Building area for multi-family dwellings (sq ft).',
    bldg_area_retail_services = 'Building area for retail services employment (sq ft).',
    bldg_area_restaurant = 'Building area for restaurant employment (sq ft).',
    bldg_area_accommodation = 'Building area for accommodation employment (sq ft).',
    bldg_area_arts_entertainment = 'Building area for arts and entertainment employment (sq ft).',
    bldg_area_other_services = 'Building area for other services employment (sq ft).',
    bldg_area_office_services = 'Building area for office services employment (sq ft).',
    bldg_area_public_admin = 'Building area for public administration employment (sq ft).',
    bldg_area_education = 'Building area for education employment (sq ft).',
    bldg_area_medical_services = 'Building area for medical services employment (sq ft).',
    bldg_area_transport_warehousing = 'Building area for transport and warehousing employment (sq ft).',
    bldg_area_wholesale = 'Building area for wholesale employment (sq ft).',
    cost_burden_pct = 'Share of households that are cost burdened (percent).',
    median_income = 'Median household income in the parcel area ($ per year).',
    pct_college_educated = 'Share of the population with a college education (percent).',
    pct_minority = 'Share of the population that is people of color (percent).',
    rent_burden_pct = 'Share of households paying over 30 percent of income on rent (percent).',
    residential_irrigated_area = 'Residential area under irrigation (acres).',
    commercial_irrigated_area = 'Commercial area under irrigation (acres).'
  ),
  audits (
    not_null(columns := (parcel_id))
  )
);

SELECT
    parcel_id AS parcel_id,
    NULL::VARCHAR(64) AS id_source,
    NULL::VARCHAR(128) AS geometry_key,
    geometry AS geometry,
    'standard' AS land_development_category,
    2 AS built_form_key,
    CASE
        WHEN ST_Area(geometry) / 4046.86 > 0
            THEN LEAST(25.0, GREATEST(0.5, 10.0 / SQRT(ST_Area(geometry) / 4046.86)))
        ELSE 0.5
    END AS intersection_density,
    ST_Area(geometry) / 4046.86 AS area_gross,
    0.0 AS area_parcel,
    0.0 AS area_dev_condition,
    0.0 AS area_row,
    0.0 AS area_parcel_res_detsf,
    0.0 AS area_parcel_res_detsf_sl,
    0.0 AS area_parcel_res_detsf_ll,
    0.0 AS area_parcel_res_attsf,
    0.0 AS area_parcel_res_mf,
    0.0 AS area_parcel_res,
    0.0 AS area_parcel_emp,
    0.0 AS area_parcel_emp_ret,
    0.0 AS area_parcel_emp_off,
    0.0 AS area_parcel_emp_pub,
    0.0 AS area_parcel_emp_ind,
    0.0 AS area_parcel_emp_ag,
    0.0 AS area_parcel_emp_military,
    0.0 AS area_parcel_mixed_use,
    0.0 AS area_parcel_no_use,
    0.0 AS pop,
    0.0 AS pop_groupquarter,
    0.0 AS hh,
    0.0 AS du,
    0.0 AS du_detsf,
    0.0 AS du_detsf_sl,
    0.0 AS du_detsf_ll,
    0.0 AS du_attsf,
    0.0 AS du_mf,
    0.0 AS du_mf2to4,
    0.0 AS du_mf5p,
    0.0 AS emp,
    0.0 AS emp_ret,
    0.0 AS emp_retail_services,
    0.0 AS emp_restaurant,
    0.0 AS emp_accommodation,
    0.0 AS emp_arts_entertainment,
    0.0 AS emp_other_services,
    0.0 AS emp_off,
    0.0 AS emp_office_services,
    0.0 AS emp_medical_services,
    0.0 AS emp_pub,
    0.0 AS emp_public_admin,
    0.0 AS emp_education,
    0.0 AS emp_ind,
    0.0 AS emp_manufacturing,
    0.0 AS emp_wholesale,
    0.0 AS emp_transport_warehousing,
    0.0 AS emp_utilities,
    0.0 AS emp_construction,
    0.0 AS emp_ag,
    0.0 AS emp_agriculture,
    0.0 AS emp_extraction,
    0.0 AS emp_military,
    0.0 AS bldg_area_detsf_sl,
    0.0 AS bldg_area_detsf_ll,
    0.0 AS bldg_area_attsf,
    0.0 AS bldg_area_mf,
    0.0 AS bldg_area_retail_services,
    0.0 AS bldg_area_restaurant,
    0.0 AS bldg_area_accommodation,
    0.0 AS bldg_area_arts_entertainment,
    0.0 AS bldg_area_other_services,
    0.0 AS bldg_area_office_services,
    0.0 AS bldg_area_public_admin,
    0.0 AS bldg_area_education,
    0.0 AS bldg_area_medical_services,
    0.0 AS bldg_area_transport_warehousing,
    0.0 AS bldg_area_wholesale,
    0.0 AS cost_burden_pct,
    0.0 AS median_income,
    0.0 AS pct_college_educated,
    0.0 AS pct_minority,
    0.0 AS rent_burden_pct,
    0.0 AS residential_irrigated_area,
    0.0 AS commercial_irrigated_area
FROM brewgis.seeds.test_parcels
