MODEL (
  name brewgis.tests.stage_test_stage_full_base_canvas,
  kind VIEW,
  audits (
    not_null(columns := (id))
  )
);

SELECT
    id AS parcel_id,
    id AS id,
    NULL::VARCHAR(64) AS id_source,
    NULL::VARCHAR(128) AS geometry_key,
    geometry AS geometry,
    land_development_category,
    built_form_key,
    intersection_density,
    ST_Area(geometry) / 4046.86 AS area_gross,
    0.0 AS geography_id,
    0.0 AS area_parcel,
    0.0 AS area_dev_condition,
    0.0 AS area_row,
    0.0 AS area_parcel_res_detsf,
    0.0 AS area_parcel_res_detsf_sl,
    0.0 AS area_parcel_res_detsf_ll,
    0.0 AS area_parcel_res_attsf,
    0.0 AS area_parcel_res_mf,
    0.0 AS area_parcel_res,
    0.0 AS area_parcel_emp,
    0.0 AS area_parcel_emp_ret,
    0.0 AS area_parcel_emp_off,
    0.0 AS area_parcel_emp_pub,
    0.0 AS area_parcel_emp_ind,
    0.0 AS area_parcel_emp_ag,
    0.0 AS area_parcel_emp_military,
    0.0 AS area_parcel_mixed_use,
    0.0 AS area_parcel_no_use,
    0.0 AS pop,
    0.0 AS pop_groupquarter,
    0.0 AS hh,
    0.0 AS du,
    0.0 AS du_detsf,
    0.0 AS du_detsf_sl,
    0.0 AS du_detsf_ll,
    0.0 AS du_attsf,
    0.0 AS du_mf,
    0.0 AS du_mf2to4,
    0.0 AS du_mf5p,
    0.0 AS emp,
    0.0 AS emp_ret,
    0.0 AS emp_retail_services,
    0.0 AS emp_restaurant,
    0.0 AS emp_accommodation,
    0.0 AS emp_arts_entertainment,
    0.0 AS emp_other_services,
    0.0 AS emp_off,
    0.0 AS emp_office_services,
    0.0 AS emp_medical_services,
    0.0 AS emp_pub,
    0.0 AS emp_public_admin,
    0.0 AS emp_education,
    0.0 AS emp_ind,
    0.0 AS emp_manufacturing,
    0.0 AS emp_wholesale,
    0.0 AS emp_transport_warehousing,
    0.0 AS emp_utilities,
    0.0 AS emp_construction,
    0.0 AS emp_ag,
    0.0 AS emp_agriculture,
    0.0 AS emp_extraction,
    0.0 AS emp_military,
    0.0 AS bldg_area_detsf_sl,
    0.0 AS bldg_area_detsf_ll,
    0.0 AS bldg_area_attsf,
    0.0 AS bldg_area_mf,
    0.0 AS bldg_area_retail_services,
    0.0 AS bldg_area_restaurant,
    0.0 AS bldg_area_accommodation,
    0.0 AS bldg_area_arts_entertainment,
    0.0 AS bldg_area_other_services,
    0.0 AS bldg_area_office_services,
    0.0 AS bldg_area_public_admin,
    0.0 AS bldg_area_education,
    0.0 AS bldg_area_medical_services,
    0.0 AS bldg_area_transport_warehousing,
    0.0 AS bldg_area_wholesale,
    0.0 AS cost_burden_pct,
    0.0 AS median_income,
    0.0 AS pct_college_educated,
    0.0 AS pct_minority,
    0.0 AS rent_burden_pct,
    0.0 AS residential_irrigated_area,
    0.0 AS commercial_irrigated_area
FROM brewgis.seeds.test_base_canvas
