# Generated by Django 5.0.9 on 2026-05-07 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('mapbox_style', models.JSONField(blank=True, null=True)),
                ('geometry_type', models.CharField(choices=[('fill', 'Fill (Polygon)'), ('line', 'Line (Linestring)'), ('circle', 'Circle (Point)')], default='fill', help_text='Derived from the source geometry type; can be overridden.', max_length=16)),
                ('display_order', models.IntegerField(default=0)),
                ('layer_source', models.CharField(max_length=255)),
                ('db_table', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('db_connection', models.CharField(default='default', max_length=64)),
                ('db_schema', models.CharField(default='public', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SymbologyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbology_type', models.CharField(choices=[('single', 'Single Symbol'), ('categorical', 'Categorical'), ('graduated', 'Graduated / Quantitative')], default='single', max_length=16)),
                ('attribute_column', models.CharField(blank=True, default='', help_text='Feature column to style on (for categorical/graduated).', max_length=255)),
                ('default_color', models.CharField(default='#888888', max_length=16)),
                ('default_opacity', models.FloatField(default=0.7)),
                ('stroke_color', models.CharField(blank=True, default='', max_length=16)),
                ('stroke_width', models.FloatField(default=1.0)),
                ('line_width', models.FloatField(default=1.0)),
                ('circle_radius', models.FloatField(default=4.0)),
                ('palette_name', models.CharField(blank=True, default='', help_text='Named palette from palettes registry (blank = manual).', max_length=64)),
                ('reverse_palette', models.BooleanField(default=False)),
                ('num_classes', models.IntegerField(default=5)),
                ('classification_method', models.CharField(choices=[('natural_breaks', 'Natural Breaks (Jenks)'), ('equal_interval', 'Equal Interval'), ('quantile', 'Quantile'), ('jenks', 'Jenks'), ('logarithmic', 'Logarithmic'), ('std_deviation', 'Standard Deviation'), ('manual', 'Manual')], default='quantile', max_length=32)),
                ('null_handling', models.CharField(choices=[('hide', 'Hide nulls'), ('gray', 'Gray (#cccccc)'), ('custom_color', 'Custom color')], default='gray', max_length=16)),
                ('null_color', models.CharField(blank=True, default='', max_length=16)),
                ('zero_transparent', models.BooleanField(default=False, help_text='Make zero-values fully transparent.')),
                ('auto_generated', models.BooleanField(default=True, help_text='Was this auto-generated from column statistics?')),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='symbology', to='workspace.layer')),
            ],
        ),
        migrations.CreateModel(
            name='StyleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(default='#888888', max_length=16)),
                ('opacity', models.FloatField(blank=True, null=True)),
                ('stroke_color', models.CharField(blank=True, default='', max_length=16)),
                ('stroke_width', models.FloatField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('symbology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='workspace.symbologyconfig')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='layer',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='workspace.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('workspace', 'key')},
        ),
    ]
