# Generated by Django 5.0.9 on 2024-12-07 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapbox_style', models.JSONField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('db_connection', models.CharField(default='default', max_length=64)),
                ('db_schema', models.CharField(default='public', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_table', models.CharField(max_length=64)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.layer')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.scenario')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='layers',
            field=models.ManyToManyField(through='workspace.ScenarioLayer', to='workspace.layer'),
        ),
        migrations.CreateModel(
            name='UserDefinedViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('processed', models.DateTimeField(blank=True, null=True)),
                ('module', models.CharField(max_length=256)),
                ('config', models.JSONField()),
                ('db_view_result', models.CharField(max_length=64)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workspace.scenario')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='layer',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
    ]
