# Generated by Django 5.0.9 on 2026-05-07 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='mapbox_style',
        ),
    ]
