# Generated by Django 5.0.9 on 2026-05-07 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_remove_mapbox_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('du_per_acre', models.FloatField(blank=True, help_text='Residential density (net). Null = no residential.', null=True, verbose_name='Dwelling units per acre')),
                ('emp_per_acre', models.FloatField(blank=True, help_text='Job density (net). Null = no employment.', null=True, verbose_name='Employment per acre')),
                ('far', models.FloatField(blank=True, help_text='Gross floor area ÷ site area.', null=True, verbose_name='Floor area ratio')),
                ('household_size', models.FloatField(default=2.5, help_text='Average persons per household.', verbose_name='Household size')),
                ('tenure_owner_pct', models.FloatField(blank=True, null=True, verbose_name='Owner occupancy (%)')),
                ('tenure_renter_pct', models.FloatField(blank=True, null=True, verbose_name='Renter occupancy (%)')),
                ('vacancy_rate', models.FloatField(default=5.0, help_text='Percent of dwelling units vacant.', verbose_name='Vacancy rate (%)')),
                ('stories', models.IntegerField(blank=True, help_text='Typical number of stories.', null=True, verbose_name='Stories')),
                ('footprint_per_unit', models.FloatField(blank=True, help_text='Average building footprint per dwelling unit.', null=True, verbose_name='Footprint per unit (m²)')),
                ('building_coverage', models.FloatField(blank=True, help_text='Percent of site area covered by buildings.', null=True, verbose_name='Building coverage (%)')),
                ('jobs_by_sector', models.JSONField(blank=True, default=dict, help_text='Dict of sector → percentage of total employment.', verbose_name='Jobs by sector')),
                ('indoor_water_rate', models.FloatField(blank=True, null=True, verbose_name='Indoor water use (L/person/day)')),
                ('outdoor_water_rate', models.FloatField(blank=True, null=True, verbose_name='Outdoor water use (L/m²/year)')),
                ('irrigable_area_fraction', models.FloatField(blank=True, help_text='Fraction of open space that is irrigated.', null=True, verbose_name='Irrigable area fraction')),
                ('electricity_eui', models.FloatField(blank=True, help_text='Energy use intensity for electricity.', null=True, verbose_name='Electricity EUI (kWh/m²/yr)')),
                ('gas_eui', models.FloatField(blank=True, help_text='Energy use intensity for natural gas.', null=True, verbose_name='Gas EUI (kWh/m²/yr)')),
                ('vintage', models.CharField(blank=True, choices=[('pre_1970', 'Pre-1970'), ('1970_2000', '1970–2000'), ('post_2000', 'Post-2000'), ('new', 'New Construction')], default='', help_text='Approximate construction era for energy modeling.', max_length=32, verbose_name='Building vintage')),
                ('parking_spaces_per_unit', models.FloatField(blank=True, null=True, verbose_name='Parking spaces per dwelling unit')),
                ('parking_spaces_per_1000sqft', models.FloatField(blank=True, null=True, verbose_name='Parking spaces per 1,000 ft² of non-res floor area')),
                ('parking_sqft_per_space', models.FloatField(default=300.0, help_text='Square feet per parking space including aisles.', verbose_name='Parking area per space (ft²)')),
                ('ite_land_use_code', models.IntegerField(blank=True, help_text='ITE Trip Generation manual land use code.', null=True, verbose_name='ITE Land Use Code')),
                ('trip_rate_override', models.FloatField(blank=True, null=True, verbose_name='Trip rate override (trips/unit)')),
                ('pass_by_trip_pct', models.FloatField(default=0.0, help_text='Percent of trips that are pass-by (diverted from passing traffic).', verbose_name='Pass-by trip (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Building Type',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('row_allocation_pct', models.FloatField(default=25.0, help_text='Percent of parcel area dedicated to right-of-way.', verbose_name='ROW allocation (%)')),
                ('block_size', models.FloatField(blank=True, help_text='Average block length in meters.', null=True, verbose_name='Block size (m)')),
                ('street_pattern', models.CharField(blank=True, choices=[('grid', 'Grid'), ('cul_de_sac', 'Cul-de-Sac'), ('loop', 'Loop'), ('hybrid', 'Hybrid')], default='', max_length=32, verbose_name='Street pattern')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Place Type',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlaceTypeBuildingTypeMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(help_text='Percent of developable area allocated to this building type.', verbose_name='Mix percentage')),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_type_mixes', to='workspace.buildingtype')),
                ('place_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_type_mixes', to='workspace.placetype')),
            ],
            options={
                'verbose_name': 'Place Type - Building Type Mix',
                'verbose_name_plural': 'Place Type - Building Type Mixes',
                'ordering': ('place_type', 'building_type'),
            },
        ),
        migrations.AddConstraint(
            model_name='placetypebuildingtypemix',
            constraint=models.UniqueConstraint(fields=('place_type', 'building_type'), name='uq_place_type_building_type'),
        ),
    ]
