# Generated by Django 5.0.9 on 2026-05-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_built_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingtype',
            name='household_size',
            field=models.FloatField(blank=True, default=2.5, help_text='Average persons per household.', verbose_name='Household size'),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='parking_sqft_per_space',
            field=models.FloatField(blank=True, default=300.0, help_text='Square feet per parking space including aisles.', verbose_name='Parking area per space (ft²)'),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='pass_by_trip_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Percent of trips that are pass-by (diverted from passing traffic).', verbose_name='Pass-by trip (%)'),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='vacancy_rate',
            field=models.FloatField(blank=True, default=5.0, help_text='Percent of dwelling units vacant.', verbose_name='Vacancy rate (%)'),
        ),
    ]
