# Generated by Django 5.0.9 on 2026-05-07
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Add AnalysisRun model for tracking dbt analysis execution."""

    dependencies = [
        ("workspace", "0004_built_forms_blank_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modules",
                    models.JSONField(
                        default=list,
                        help_text="List of module names executed (e.g. ['env_constraint', 'core']).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "vars",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="dbt variables used for this run.",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "error_log",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="analysis_runs",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis Run",
                "ordering": ("-created_at",),
            },
        ),
    ]
