# Generated by Django 5.0.9 on 2026-05-07 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_analysis_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('census', 'Census ACS Demographics'), ('lehd', 'LEHD Employment'), ('poi', 'Points of Interest'), ('allocate', 'Spatial Allocation'), ('stitch', 'Column Stitching')], max_length=16)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Parameters for the import (FIPS codes, bounding box, etc.).')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Result metadata (layer key, table name, row count, etc.).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_import_runs', to='workspace.workspace')),
            ],
            options={
                'verbose_name': 'Data Import Run',
                'ordering': ('-created_at',),
            },
        ),
    ]
