# Generated by Django 5.0.9 on 2026-05-07 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_dataimportrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('scenario_type', models.CharField(choices=[('base', 'Base'), ('alternative', 'Alternative')], default='base', max_length=16)),
                ('base_year', models.IntegerField()),
                ('horizon_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternatives', to='workspace.scenario')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='workspace.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('workspace', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_runs', to='workspace.scenario'),
        ),
    ]
