# Generated by Django 5.0.9 on 2026-05-07 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_scenario_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintedCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(max_length=128)),
                ('column_name', models.CharField(max_length=128)),
                ('painted_value', models.FloatField(blank=True, null=True)),
                ('painted_at', models.DateTimeField(auto_now_add=True)),
                ('painted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painted_features', to='workspace.scenario')),
            ],
            options={
                'indexes': [models.Index(fields=['scenario', 'feature_id'], name='workspace_p_scenari_fabbba_idx')],
                'unique_together': {('scenario', 'feature_id', 'column_name')},
            },
        ),
    ]
