# Generated by Django 5.0.9 on 2026-05-08 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_scenario_schema_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=128)),
                ('operator', models.CharField(choices=[('lt', '<'), ('lte', '<='), ('gt', '>'), ('gte', '>='), ('eq', '='), ('neq', '!='), ('not_null', 'Not Null')], max_length=16)),
                ('value', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('block', 'Block'), ('warn', 'Warn')], default='block', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paint_constraints', to='workspace.workspace')),
            ],
            options={
                'verbose_name': 'Paint Constraint',
                'verbose_name_plural': 'Paint Constraints',
                'ordering': ('column', 'operator', 'value'),
            },
        ),
    ]
