# Generated by Django 5.0.9 on 2026-05-08 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_paint_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paintedcanvas',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status for merge operations.', max_length=16),
        ),
        migrations.CreateModel(
            name='MergeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows_copied', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_merges', to='workspace.scenario')),
                ('target_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_merges', to='workspace.scenario')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_audits', to='workspace.workspace')),
            ],
            options={
                'verbose_name': 'Merge Audit',
                'ordering': ('-created_at',),
            },
        ),
    ]
