# Generated by Django 6.0.5 on 2026-05-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_paint_event_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_fips', models.CharField(max_length=2)),
                ('county_fips', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ('state_fips', 'county_fips'),
            },
        ),
        migrations.RenameIndex(
            model_name='paintevent',
            new_name='workspace_p_scenari_e0b82a_idx',
            old_name='workspace_p_scenari_0968af_idx',
        ),
        migrations.RenameIndex(
            model_name='paintevent',
            new_name='workspace_p_batch_i_f7f321_idx',
            old_name='workspace_p_batch_i_0b2d9e_idx',
        ),
        migrations.AddField(
            model_name='workspace',
            name='county_fips_list',
            field=models.JSONField(blank=True, default=list, help_text='List of {state, county} FIPS objects for multi-county workspaces.'),
        ),
        migrations.AlterUniqueTogether(
            name='county',
            unique_together={('state_fips', 'county_fips')},
        ),
    ]
