# Generated by Django 6.0.5 on 2026-05-08 18:23

import csv
import os

from django.db import migrations


def seed_counties(apps, schema_editor):
    County = apps.get_model("workspace", "County")
    csv_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "fixtures",
        "county_fips.csv",
    )
    if not os.path.exists(csv_path):
        return
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        batch = []
        for row in reader:
            batch.append(
                County(
                    state_fips=row["state_fips"],
                    county_fips=row["county_fips"],
                    name=row["name"],
                )
            )
        County.objects.bulk_create(batch, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0014_county_model_and_workspace_fips"),
    ]

    operations = [
        migrations.RunPython(seed_counties, migrations.RunPython.noop),
    ]
