# Generated by Django 6.0.5 on 2026-05-09 05:18

import django.db.models.deletion
from django.db import migrations, models


def assign_orphaned_runs(apps, schema_editor):
    """Assign any AnalysisRun with NULL scenario to a legacy scenario per workspace."""
    AnalysisRun = apps.get_model("workspace", "AnalysisRun")
    Scenario = apps.get_model("workspace", "Scenario")
    Workspace = apps.get_model("workspace", "Workspace")

    orphaned = list(AnalysisRun.objects.filter(scenario__isnull=True).select_related("workspace"))
    if not orphaned:
        return

    # Collect unique workspaces with orphaned runs
    ws_ids = {r.workspace_id for r in orphaned}
    for ws_id in ws_ids:
        ws = Workspace.objects.get(pk=ws_id)
        # Reuse or create a "Legacy" scenario for this workspace
        legacy, _ = Scenario.objects.get_or_create(
            workspace=ws,
            slug="legacy",
            defaults={
                "name": "Legacy (auto-migrated)",
                "base_year": 2025,
                "horizon_year": 2050,
            },
        )
        AnalysisRun.objects.filter(
            workspace=ws,
            scenario__isnull=True,
        ).update(scenario=legacy)


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0015_seed_county_fips"),
    ]

    operations = [
        migrations.RunPython(
            assign_orphaned_runs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="analysisrun",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_runs",
                to="workspace.scenario",
            ),
        ),
    ]
