# Generated by Django 6.0.5 on 2026-05-09 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0016_scenario_fk_non_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Data Source Categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('provider', models.CharField(max_length=128)),
                ('provider_url', models.URLField(blank=True, default='', max_length=512)),
                ('data_format', models.CharField(blank=True, choices=[('parquet', 'GeoParquet'), ('shapefile', 'Shapefile'), ('geojson', 'GeoJSON'), ('geotiff', 'GeoTIFF'), ('csv', 'CSV'), ('api', 'REST API'), ('wms', 'WMS'), ('gtfs', 'GTFS')], default='', max_length=16)),
                ('update_frequency', models.CharField(blank=True, choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('continuous', 'Continuous'), ('periodic', 'Periodic'), ('biennial', 'Biennial'), ('five_year', '5-Year'), ('ten_year', '10-Year')], default='', max_length=16)),
                ('acquisition_priority', models.CharField(blank=True, choices=[('p0', 'P0 — Ship Now'), ('p1', 'P1 — Phase 1'), ('p2', 'P2 — Phase 2')], default='', max_length=4)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('import_type', models.CharField(blank=True, default='', help_text='Maps to DataImportRun import_type if import is supported', max_length=16)),
                ('is_importable', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='workspace.datasourcecategory')),
            ],
            options={
                'verbose_name': 'Data Source',
                'ordering': ('category__sort_order', 'sort_order', 'name'),
            },
        ),
    ]
