"""Seed the data catalog with 9 categories and 40+ US data sources."""

from __future__ import annotations

from django.db import migrations


def seed_catalog(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    DataSourceCategory = apps.get_model("workspace", "DataSourceCategory")
    DataSource = apps.get_model("workspace", "DataSource")

    # ── Categories ──────────────────────────────────────────────────

    boundaries = DataSourceCategory.objects.create(
        name="Boundaries",
        slug="boundaries",
        description="Administrative, political, and geographic boundaries: states, counties, tracts, districts.",
        icon="bi-bounding-box-circles",
        sort_order=10,
    )
    people = DataSourceCategory.objects.create(
        name="People",
        slug="people",
        description="Demographic data: population, age, income, education, and social vulnerability indicators.",
        icon="bi-people-fill",
        sort_order=20,
    )
    land_use = DataSourceCategory.objects.create(
        name="Land Use & Land Cover",
        slug="land-use",
        description="Classifications of land areas by usage type and physical surface characteristics.",
        icon="bi-grid-3x3-gap-fill",
        sort_order=30,
    )
    places = DataSourceCategory.objects.create(
        name="Places",
        slug="places",
        description="Points of interest such as schools, hospitals, parks, transit stops, and commercial amenities.",
        icon="bi-geo-alt-fill",
        sort_order=40,
    )
    transportation = DataSourceCategory.objects.create(
        name="Transportation",
        slug="transportation",
        description="Road networks, transit feeds, commute flows, and mobility infrastructure.",
        icon="bi-signpost-2-fill",
        sort_order=50,
    )
    environmental = DataSourceCategory.objects.create(
        name="Environmental & Hazard",
        slug="environmental-hazard",
        description="Flood zones, sea level rise, climate exposure, environmental justice, and ecosystem services.",
        icon="bi-exclamation-triangle-fill",
        sort_order=60,
    )
    housing = DataSourceCategory.objects.create(
        name="Housing & Neighborhoods",
        slug="housing-neighborhoods",
        description="Housing affordability, cost burden, subsidized housing, vacancy, and neighborhood conditions.",
        icon="bi-house-door-fill",
        sort_order=70,
    )
    economic = DataSourceCategory.objects.create(
        name="Economic & Fiscal",
        slug="economic-fiscal",
        description="Employment, wages, business activity, GDP, and fiscal indicators.",
        icon="bi-briefcase-fill",
        sort_order=80,
    )
    infrastructure = DataSourceCategory.objects.create(
        name="Infrastructure & Utilities",
        slug="infrastructure-utilities",
        description="Broadband, water systems, power grids, and critical facility locations.",
        icon="bi-lightning-charge-fill",
        sort_order=90,
    )

    # ── Data Sources ────────────────────────────────────────────────

    sources = [
        # -- Boundaries --
        DataSource(
            category=boundaries,
            name="TIGER/Line Shapefiles",
            slug="tiger-line",
            description="Census boundaries: states, counties, tracts, block groups, places, districts, ZCTAs.",
            provider="U.S. Census Bureau",
            provider_url="https://www.census.gov/geographies/mapping-files.html",
            data_format="shapefile",
            update_frequency="annual",
            acquisition_priority="p0",
            icon="bi-bounding-box-circles",
            sort_order=10,
        ),
        DataSource(
            category=boundaries,
            name="TIGERweb REST API",
            slug="tigerweb",
            description="Live GeoJSON boundary service suitable for lightweight MVT tile generation.",
            provider="U.S. Census Bureau",
            provider_url="https://tigerweb.geo.census.gov/tigerwebmain/TIGERweb_apps.html",
            data_format="api",
            update_frequency="annual",
            acquisition_priority="p0",
            icon="bi-bounding-box-circles",
            sort_order=20,
        ),
        DataSource(
            category=boundaries,
            name="School District Boundaries",
            slug="school-district-boundaries",
            description="Unified/elementary/secondary school district boundaries with crosswalks.",
            provider="NCES EDGE",
            provider_url="https://nces.ed.gov/programs/edge/Geographic/DistrictBoundaries",
            data_format="geojson",
            update_frequency="annual",
            acquisition_priority="p1",
            icon="bi-mortarboard-fill",
            sort_order=30,
        ),
        DataSource(
            category=boundaries,
            name="USPS ZIP ↔ Census Tract Crosswalk",
            slug="zip-tract-crosswalk",
            description="Quarterly crosswalk linking ZIP codes to Census tracts, counties, and other geographies.",
            provider="HUD USER",
            provider_url="https://www.huduser.gov/apps/public/uspscrosswalk/home",
            data_format="csv",
            update_frequency="semi_annual",
            acquisition_priority="p2",
            icon="bi-arrow-left-right",
            sort_order=40,
        ),
        # -- People --
        DataSource(
            category=people,
            name="American Community Survey 5-Year",
            slug="acs-5-year",
            description="~40K demographic, social, economic, housing tables at tract/block-group level.",
            provider="U.S. Census Bureau",
            provider_url="https://www.census.gov/programs-surveys/acs/data/data-via-api.html",
            data_format="api",
            update_frequency="annual",
            acquisition_priority="p0",
            icon="bi-people-fill",
            import_type="census",
            is_importable=True,
            sort_order=10,
        ),
        DataSource(
            category=people,
            name="ACS 1-Year Estimates",
            slug="acs-1-year",
            description="Current-year demographic profiles for jurisdictions with 65,000+ population.",
            provider="U.S. Census Bureau",
            provider_url="https://www.census.gov/programs-surveys/acs/data/data-tables/data-profiles.html",
            data_format="api",
            update_frequency="annual",
            acquisition_priority="p0",
            icon="bi-people-fill",
            sort_order=20,
        ),
        DataSource(
            category=people,
            name="Decennial Census (PL 94-171)",
            slug="decennial-census",
            description="Total population, race/ethnicity, voting age data for redistricting and apportionment.",
            provider="U.S. Census Bureau",
            provider_url="https://www.census.gov/programs-surveys/decennial-census/data.html",
            data_format="api",
            update_frequency="ten_year",
            acquisition_priority="p0",
            icon="bi-people-fill",
            sort_order=30,
        ),
        DataSource(
            category=people,
            name="Population Estimates Program",
            slug="census-population-estimates",
            description="Intercensal population estimates for counties and incorporated places.",
            provider="U.S. Census Bureau",
            provider_url="https://www.census.gov/programs-surveys/popest.html",
            data_format="api",
            update_frequency="annual",
            acquisition_priority="p0",
            icon="bi-people-fill",
            sort_order=40,
        ),
        DataSource(
            category=people,
            name="Social Vulnerability Index (SVI)",
            slug="cdc-svi",
            description="15 social vulnerability factors: socioeconomic, household, racial/ethnic, housing.",
            provider="CDC / ATSDR",
            provider_url="https://svi.cdc.gov/dataDownloads/data-download.html",
            data_format="shapefile",
            update_frequency="biennial",
            acquisition_priority="p0",
            icon="bi-shield-exclamation",
            sort_order=50,
        ),
        DataSource(
            category=people,
            name="County Health Rankings",
            slug="county-health-rankings",
            description="Health outcomes, clinical care, social/economic, and physical environment at county level.",
            provider="County Health Rankings & Roadmaps",
            provider_url="https://www.countyhealthrankings.org/explore-health-rankings/rankings-data-documentation",
            data_format="csv",
            update_frequency="annual",
            acquisition_priority="p0",
            icon="bi-heart-pulse-fill",
            sort_order=60,
        ),
        DataSource(
            category=people,
            name="Comprehensive Housing Affordability Strategy (CHAS)",
            slug="hud-chas",
            description="Cost-burdened households by AMI category for housing element and CDBG grant compliance.",
            provider="HUD USER",
            provider_url="https://www.huduser.gov/portal/datasets/cp.html",
            data_format="csv",
            update_frequency="five_year",
            acquisition_priority="p1",
            icon="bi-house-door-fill",
            sort_order=70,
        ),
        # -- Land Use & Land Cover --
        DataSource(
            category=land_use,
            name="National Land Cover Database (NLCD)",
            slug="nlcd-land-cover",
            description="16-class land cover at 30m for CONUS, Alaska, Hawaii, and territories. Annual.",
            provider="USGS MRLC",
            provider_url="https://www.mrlc.gov/data",
            data_format="geotiff",
            update_frequency="annual",
            acquisition_priority="p2",
            icon="bi-grid-3x3-gap-fill",
            sort_order=10,
        ),
        DataSource(
            category=land_use,
            name="NLCD Tree Canopy Cover (TCC)",
            slug="nlcd-tree-canopy",
            description="Percent tree canopy cover per 30m pixel across the conterminous United States.",
            provider="USGS MRLC",
            provider_url="https://www.mrlc.gov/data/type/land-cover",
            data_format="geotiff",
            update_frequency="periodic",
            acquisition_priority="p2",
            icon="bi-tree-fill",
            sort_order=20,
        ),
        DataSource(
            category=land_use,
            name="NLCD Impervious Surface",
            slug="nlcd-impervious",
            description="Percent impervious surface per 30m pixel for stormwater and urban heat island analysis.",
            provider="USGS MRLC",
            provider_url="https://www.mrlc.gov/data",
            data_format="geotiff",
            update_frequency="annual",
            acquisition_priority="p2",
            icon="bi-building-fill",
            sort_order=30,
        ),
        DataSource(
            category=land_use,
            name="EPA Smart Location Database (SLD)",
            slug="epa-smart-location",
            description="~90 built-environment variables: density, land use diversity, design, transit access.",
            provider="EPA",
            provider_url="https://www.epa.gov/smartgrowth/smart-location-mapping",
            data_format="csv",
            update_frequency="periodic",
            acquisition_priority="p1",
            icon="bi-geo-fill",
            sort_order=40,
        ),
        DataSource(
            category=land_use,
            name="Overture Land Use",
            slug="overture-land-use",
            description="Global land use polygons and land cover in GeoParquet format. DuckDB-native.",
            provider="Overture Maps Foundation",
            provider_url="https://docs.overturemaps.org/schema/reference",
            data_format="parquet",
            update_frequency="quarterly",
            acquisition_priority="p0",
            icon="bi-globe2",
            sort_order=50,
        ),
        # -- Places --
        DataSource(
            category=places,
            name="Overture Places",
            slug="overture-places",
            description="60M+ global POIs: restaurants, shops, healthcare, education, entertainment.",
            provider="Overture Maps Foundation",
            provider_url="https://docs.overturemaps.org/schema/reference/places/",
            data_format="parquet",
            update_frequency="quarterly",
            acquisition_priority="p0",
            icon="bi-geo-alt-fill",
            sort_order=10,
        ),
        DataSource(
            category=places,
            name="Overture Buildings",
            slug="overture-buildings",
            description="Building footprints with height, type, address: Microsoft, Google, OSM sources.",
            provider="Overture Maps Foundation",
            provider_url="https://docs.overturemaps.org/guides/buildings/",
            data_format="parquet",
            update_frequency="quarterly",
            acquisition_priority="p0",
            icon="bi-building-fill",
            sort_order=20,
        ),
        DataSource(
            category=places,
            name="OpenStreetMap Points of Interest",
            slug="osm-poi",
            description="Community global POIs: hospitals, schools, parks, transit stops, shops, services.",
            provider="OpenStreetMap",
            provider_url="https://wiki.openstreetmap.org/",
            data_format="api",
            update_frequency="continuous",
            acquisition_priority="p0",
            icon="bi-geo-alt-fill",
            import_type="poi",
            is_importable=True,
            sort_order=30,
        ),
        DataSource(
            category=places,
            name="Cleanups in My Community (CIMC)",
            slug="epa-cleanups",
            description="Superfund, brownfields, RCRA sites, and leaking underground storage tanks.",
            provider="EPA",
            provider_url="https://www.epa.gov/cleanups/cleanups-my-community-about-data",
            data_format="geojson",
            update_frequency="quarterly",
            acquisition_priority="p0",
            icon="bi-exclamation-triangle-fill",
            sort_order=40,
        ),
        DataSource(
            category=places,
            name="Toxics Release Inventory (TRI)",
            slug="epa-tri",
            description="Toxic chemical releases by facility for environmental justice analysis.",
            provider="EPA",
            provider_url="https://www.epa.gov/toxics-release-inventory-tri-program/mapping-data-tri-releases",
            data_format="geojson",
            update_frequency="annual",
            acquisition_priority="p0",
            icon="bi-biohazard",
            sort_order=50,
        ),
        DataSource(
            category=places,
            name="NPS Park Boundaries",
            slug="nps-parks",
            description="Federal park, trail, and conservation area boundaries from the National Park Service.",
            provider="National Park Service",
            provider_url="https://catalog.data.gov/dataset/?q=nps+boundary&sort=score+desc%2C+name+asc",
            data_format="shapefile",
            update_frequency="annual",
            acquisition_priority="p1",
            icon="bi-tree-fill",
            sort_order=60,
        ),
        DataSource(
            category=places,
            name="HIFLD Infrastructure Locations",
            slug="hifld-infrastructure",
            description="Infrastructure locations: schools, hospitals, fire/police stations, airports, ports.",
            provider="Homeland Infrastructure Foundation-Level Data",
            provider_url="https://hifld-geoplatform.opendata.arcgis.com/",
            data_format="geojson",
            update_frequency="periodic",
            acquisition_priority="p1",
            icon="bi-building-fill",
            sort_order=70,
        ),
        # -- Transportation --
        DataSource(
            category=transportation,
            name="Overture Transportation",
            slug="overture-transportation",
            description="Road segments: class, speed limits, restrictions, pedestrian/bike paths.",
            provider="Overture Maps Foundation",
            provider_url="https://docs.overturemaps.org/schema/concepts/by-theme/transportation",
            data_format="parquet",
            update_frequency="quarterly",
            acquisition_priority="p0",
            icon="bi-signpost-2-fill",
            sort_order=10,
        ),
        DataSource(
            category=transportation,
            name="GTFS Public Transit Feeds",
            slug="gtfs-transit",
            description="Schedules, routes, stops, real-time data for 800+ US transit agencies.",
            provider="Transitland / Mobility Database",
            provider_url="https://www.transit.land/",
            data_format="gtfs",
            update_frequency="continuous",
            acquisition_priority="p2",
            icon="bi-bus-front-fill",
            sort_order=20,
        ),
        DataSource(
            category=transportation,
            name="LODES Employment (LEHD)",
            slug="lodes-lehd",
            description="Origin-destination employment at census block: commuting flows, jobs, wages.",
            provider="U.S. Census Bureau",
            provider_url="https://lehd.ces.census.gov/data/",
            data_format="csv",
            update_frequency="annual",
            acquisition_priority="p1",
            icon="bi-briefcase-fill",
            import_type="lehd",
            is_importable=True,
            sort_order=30,
        ),
        DataSource(
            category=transportation,
            name="EPA Smart Location Transit Data",
            slug="epa-sld-transit",
            description="Transit frequency, commute mode shares, walkability, employment accessibility.",
            provider="EPA",
            provider_url="https://www.epa.gov/smartgrowth/smart-location-mapping",
            data_format="csv",
            update_frequency="periodic",
            acquisition_priority="p1",
            icon="bi-geo-fill",
            sort_order=40,
        ),
        DataSource(
            category=transportation,
            name="National Transportation Atlas Database (NTAD)",
            slug="ntad",
            description="Rail networks, airports, ports, bike routes, intermodal terminals, highways.",
            provider="Bureau of Transportation Statistics",
            provider_url="https://www.bts.gov/ntad",
            data_format="shapefile",
            update_frequency="annual",
            acquisition_priority="p1",
            icon="bi-train-front-fill",
            sort_order=50,
        ),
        # -- Environmental & Hazard --
        DataSource(
            category=environmental,
            name="National Flood Hazard Layer (NFHL)",
            slug="fema-nfhl",
            description="Flood zones, base flood elevations, and floodways for floodplain management.",
            provider="FEMA",
            provider_url="https://www.fema.gov/flood-maps/national-flood-hazard-layer",
            data_format="geojson",
            update_frequency="continuous",
            acquisition_priority="p0",
            icon="bi-water",
            sort_order=10,
        ),
        DataSource(
            category=environmental,
            name="NOAA Sea Level Rise Inundation",
            slug="noaa-slr",
            description="Sea level rise scenarios 1-10ft with coastal flood mapping and depth rasters.",
            provider="NOAA Office for Coastal Management",
            provider_url="https://coast.noaa.gov/digitalcoast/data/slr.html",
            data_format="geotiff",
            update_frequency="periodic",
            acquisition_priority="p1",
            icon="bi-water",
            sort_order=20,
        ),
        DataSource(
            category=environmental,
            name="NOAA Coastal Change Analysis (C-CAP)",
            slug="noaa-ccap",
            description="Coastal land cover and wetland change data at 30m resolution.",
            provider="NOAA Digital Coast",
            provider_url="https://coast.noaa.gov/digitalcoast/data/home.html",
            data_format="geotiff",
            update_frequency="periodic",
            acquisition_priority="p1",
            icon="bi-map-fill",
            sort_order=30,
        ),
        DataSource(
            category=environmental,
            name="EJScreen",
            slug="epa-ejscreen",
            description="13 EJ indices at block-group: PM2.5, ozone, traffic, lead paint, wastewater.",
            provider="EPA",
            provider_url="https://www.epa.gov/ejscreen/download-ejscreen-data",
            data_format="geojson",
            update_frequency="annual",
            acquisition_priority="p0",
            icon="bi-shield-exclamation",
            sort_order=40,
        ),
        DataSource(
            category=environmental,
            name="EnviroAtlas",
            slug="epa-enviroatlas",
            description="Ecosystem services, green space, tree buffers, impervious surfaces.",
            provider="EPA",
            provider_url="https://www.epa.gov/enviroatlas",
            data_format="api",
            update_frequency="periodic",
            acquisition_priority="p1",
            icon="bi-globe2",
            sort_order=50,
        ),
        DataSource(
            category=environmental,
            name="USDA Food Access Research Atlas",
            slug="usda-food-access",
            description="Low-income low-access areas (food deserts) at tract level with vehicle data.",
            provider="USDA Economic Research Service",
            provider_url="https://www.ers.usda.gov/data-products/food-access-research-atlas/download-the-data.aspx",
            data_format="shapefile",
            update_frequency="periodic",
            acquisition_priority="p1",
            icon="bi-shop",
            sort_order=60,
        ),
        DataSource(
            category=environmental,
            name="USDA Tree Canopy Cover (CONUS)",
            slug="usda-tree-canopy",
            description="30m tree canopy cover for the conterminous US for urban heat island analysis.",
            provider="USDA Forest Service",
            provider_url="https://data.fs.usda.gov/geodata/rastergateway/treecanopycover/",
            data_format="geotiff",
            update_frequency="periodic",
            acquisition_priority="p2",
            icon="bi-tree-fill",
            sort_order=70,
        ),
        DataSource(
            category=environmental,
            name="ParkServe",
            slug="tpl-parkserve",
            description="Park polygons and 10-min walk access from the Trust for Public Land.",
            provider="Trust for Public Land",
            provider_url="https://www.tpl.org/park-data-downloads",
            data_format="geojson",
            update_frequency="annual",
            acquisition_priority="p0",
            icon="bi-tree-fill",
            sort_order=80,
        ),
        # -- Housing & Neighborhoods --
        DataSource(
            category=housing,
            name="CHAS (Comprehensive Housing Affordability Strategy)",
            slug="hud-chas-housing",
            description="Housing problems by tenure, income, and household type for CDBG/HOME programs.",
            provider="HUD USER",
            provider_url="https://www.huduser.gov/portal/datasets/cp.html",
            data_format="csv",
            update_frequency="five_year",
            acquisition_priority="p1",
            icon="bi-house-door-fill",
            sort_order=10,
        ),
        DataSource(
            category=housing,
            name="Fair Market Rent (FMR)",
            slug="hud-fmr",
            description="40th/50th percentile gross rent by metro area for Housing Choice Voucher program.",
            provider="HUD USER",
            provider_url="https://www.huduser.gov/portal/datasets/fmr.html",
            data_format="csv",
            update_frequency="annual",
            acquisition_priority="p1",
            icon="bi-currency-dollar",
            sort_order=20,
        ),
        DataSource(
            category=housing,
            name="Low-Income Housing Tax Credit (LIHTC)",
            slug="hud-lihtc",
            description="Location and unit counts for federally subsidized affordable housing.",
            provider="HUD USER",
            provider_url="https://www.huduser.gov/portal/datasets/lihtc.html",
            data_format="csv",
            update_frequency="annual",
            acquisition_priority="p1",
            icon="bi-building-fill",
            sort_order=30,
        ),
        DataSource(
            category=housing,
            name="HUD GIS Open Data",
            slug="hud-gis",
            description="Public housing developments, Section 8 multifamily properties, and HUD program geographies.",
            provider="HUD",
            provider_url="https://hudgis-hud.opendata.arcgis.com/",
            data_format="geojson",
            update_frequency="periodic",
            acquisition_priority="p1",
            icon="bi-map-fill",
            sort_order=40,
        ),
        DataSource(
            category=housing,
            name="ACS Housing Tables",
            slug="acs-housing",
            description="Tenure, vacancy, crowding, cost burden, year built, housing units by type.",
            provider="U.S. Census Bureau",
            provider_url="https://www.census.gov/programs-surveys/acs/data/data-via-api.html",
            data_format="api",
            update_frequency="annual",
            acquisition_priority="p0",
            icon="bi-house-door-fill",
            sort_order=50,
        ),
        # -- Economic & Fiscal --
        DataSource(
            category=economic,
            name="Quarterly Census of Employment & Wages (QCEW)",
            slug="bls-qcew",
            description="Employment and wages by NAICS at county level from unemployment insurance records.",
            provider="Bureau of Labor Statistics",
            provider_url="https://www.bls.gov/cew/downloadable-data-files.htm",
            data_format="csv",
            update_frequency="quarterly",
            acquisition_priority="p1",
            icon="bi-briefcase-fill",
            sort_order=10,
        ),
        DataSource(
            category=economic,
            name="GDP by County",
            slug="bea-gdp-county",
            description="GDP by county and metro area for fiscal impact and economic development.",
            provider="Bureau of Economic Analysis",
            provider_url="https://www.bea.gov/data/gdp/gdp-county",
            data_format="csv",
            update_frequency="annual",
            acquisition_priority="p1",
            icon="bi-graph-up-arrow",
            sort_order=20,
        ),
        DataSource(
            category=economic,
            name="Economic Census",
            slug="census-economic",
            description="Business counts, sales, employment by NAICS at place and tract level.",
            provider="U.S. Census Bureau",
            provider_url="https://www.census.gov/programs-surveys/economic-census/data.html",
            data_format="csv",
            update_frequency="five_year",
            acquisition_priority="p2",
            icon="bi-shop",
            sort_order=30,
        ),
        DataSource(
            category=economic,
            name="County Health Rankings Economic Factors",
            slug="chr-economic",
            description="Median income, unemployment, SNAP receipt, and economic indicators at county level.",
            provider="County Health Rankings & Roadmaps",
            provider_url="https://www.countyhealthrankings.org/explore-health-rankings/rankings-data-documentation",
            data_format="csv",
            update_frequency="annual",
            acquisition_priority="p0",
            icon="bi-currency-dollar",
            sort_order=40,
        ),
        # -- Infrastructure & Utilities --
        DataSource(
            category=infrastructure,
            name="Overture Infrastructure",
            slug="overture-infrastructure",
            description="Power grids, telecom, and water infrastructure in GeoParquet format.",
            provider="Overture Maps Foundation",
            provider_url="https://docs.overturemaps.org/schema/reference/base/infrastructure/",
            data_format="parquet",
            update_frequency="quarterly",
            acquisition_priority="p2",
            icon="bi-lightning-charge-fill",
            sort_order=10,
        ),
        DataSource(
            category=infrastructure,
            name="FCC Broadband Data Collection",
            slug="fcc-broadband",
            description="Broadband availability by location for digital divide analysis.",
            provider="Federal Communications Commission",
            provider_url="https://broadbandmap.fcc.gov/",
            data_format="shapefile",
            update_frequency="semi_annual",
            acquisition_priority="p2",
            icon="bi-wifi",
            sort_order=20,
        ),
        DataSource(
            category=infrastructure,
            name="Safe Drinking Water Information System (SDWIS)",
            slug="epa-sdwis",
            description="Public water system boundaries, service areas, and drinking water quality violations.",
            provider="EPA",
            provider_url="https://www.epa.gov/enviroatlas",
            data_format="csv",
            update_frequency="annual",
            acquisition_priority="p2",
            icon="bi-droplet-fill",
            sort_order=30,
        ),
        DataSource(
            category=infrastructure,
            name="HIFLD Infrastructure (Dams, Pipelines, Electric)",
            slug="hifld-critical-infrastructure",
            description="Critical infrastructure: dams, pipelines, substations, airports, ports, rail.",
            provider="Homeland Infrastructure Foundation-Level Data",
            provider_url="https://hifld-geoplatform.opendata.arcgis.com/",
            data_format="geojson",
            update_frequency="periodic",
            acquisition_priority="p1",
            icon="bi-lightning-charge-fill",
            sort_order=40,
        ),
    ]

    # Bulk create (sorted by sort_order within each category)
    for src in sources:
        src.full_clean = lambda: None  # skip validation during migration
    DataSource.objects.bulk_create(sources)


def clear_catalog(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    DataSource = apps.get_model("workspace", "DataSource")
    DataSourceCategory = apps.get_model("workspace", "DataSourceCategory")
    DataSource.objects.all().delete()
    DataSourceCategory.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0017_datasourcecategory_datasource"),
    ]

    operations = [
        migrations.RunPython(seed_catalog, clear_catalog),
    ]
