# Generated by Django 5.0.9 on 2026-05-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0020_acs_equity_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbologyconfig",
            name="min_zoom",
            field=models.FloatField(
                default=0.0,
                help_text="Minimum zoom level at which this layer is visible (MapLibre minzoom).",
            ),
        ),
        migrations.AddField(
            model_name="symbologyconfig",
            name="max_zoom",
            field=models.FloatField(
                default=22.0,
                help_text="Maximum zoom level at which this layer is visible (MapLibre maxzoom).",
            ),
        ),
    ]
