# Generated by Django 6.0.5 on 2026-05-09 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0021_symbology_zoom_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimportrun",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("allocate", "Spatial Allocation"),
                    ("census", "Census ACS Demographics"),
                    ("ejscreen", "EJScreen Environmental Justice"),
                    ("health_rankings", "County Health Rankings"),
                    ("lehd", "LEHD Employment"),
                    ("parkserve", "ParkServe Park Data"),
                    ("poi", "Points of Interest"),
                    ("stitch", "Column Stitching"),
                    ("svi", "Social Vulnerability Index"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ScenarioReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("scenario_comparison", "Scenario Comparison"),
                            ("paint_tracking", "Paint Tracking"),
                            ("map_export", "Map Export"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="reports/"
                    ),
                ),
                (
                    "error_log",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "export_options",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="workspace.scenario",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scenario Report",
                "verbose_name_plural": "Scenario Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
