# Generated by django-manage makemigrations
"""Add LayerFilter model for saved filter expressions per layer."""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Create LayerFilter model for expression-tree filter builder."""

    dependencies = [
        ("workspace", "0022_alter_dataimportrun_import_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayerFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "filter_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Expression tree: {"type": "group", "operator": "AND"|"OR", "children": [...]}',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="When active, this filter is applied to the layer on the map.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filters",
                        to="workspace.layer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Layer Filter",
                "verbose_name_plural": "Layer Filters",
                "ordering": ("name",),
            },
        ),
    ]
