# Generated by Django 6.0.5 on 2026-05-09 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0023_layerfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('basemap_type', models.CharField(choices=[('vector', 'Vector'), ('raster', 'Raster')], default='vector', max_length=8)),
                ('style_url', models.URLField(blank=True, default='', help_text='MapLibre style JSON URL (for vector basemaps)', max_length=1024)),
                ('tile_url', models.URLField(blank=True, default='', help_text='Tile URL template with {z}/{x}/{y} (for raster basemaps)', max_length=1024)),
                ('attribution', models.CharField(blank=True, default='', max_length=512)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1024)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Layer Filter',
                'verbose_name_plural': 'Layer Filters',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='layerfilter',
            options={},
        ),
        migrations.AlterField(
            model_name='datasource',
            name='acquisition_priority',
            field=models.CharField(blank=True, choices=[('p0', 'P0 - Ship Now'), ('p1', 'P1 - Phase 1'), ('p2', 'P2 - Phase 2')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='import_type',
            field=models.CharField(blank=True, default='', help_text='Maps to DataImportRun type', max_length=16),
        ),
        migrations.CreateModel(
            name='LayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('display_order', models.IntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_groups', to='workspace.workspace')),
            ],
            options={
                'ordering': ('display_order', 'name'),
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.AddField(
            model_name='layer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layers', to='workspace.layergroup'),
        ),
        migrations.CreateModel(
            name='ExternalMapService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('service_type', models.CharField(choices=[('wms', 'WMS'), ('wmts', 'WMTS'), ('wfs', 'WFS'), ('xyz', 'XYZ Tiles')], default='wms', max_length=4)),
                ('url', models.URLField(max_length=1024)),
                ('layers_param', models.CharField(blank=True, default='', help_text='Layers parameter for WMS (comma-separated)', max_length=512)),
                ('attribution', models.CharField(blank=True, default='', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_services', to='workspace.workspace')),
            ],
            options={
                'verbose_name': 'External Map Service',
                'ordering': ('display_order', 'name'),
                'unique_together': {('workspace', 'name')},
            },
        ),
    ]
