# Generated by Django 6.0.5 on 2026-05-09 21:00

from django.db import migrations


DEFAULT_BASEMAPS = [
    {
        "name": "OpenStreetMap",
        "basemap_type": "raster",
        "tile_url": "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
        "attribution": "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors",
        "is_default": True,
        "sort_order": 0,
    },
    {
        "name": "Light (CartoDB)",
        "basemap_type": "raster",
        "tile_url": "https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png",
        "attribution": "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OSM</a> &copy; <a href=\"https://carto.com/\">CARTO</a>",
        "is_default": False,
        "sort_order": 1,
    },
    {
        "name": "Dark (CartoDB)",
        "basemap_type": "raster",
        "tile_url": "https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png",
        "attribution": "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OSM</a> &copy; <a href=\"https://carto.com/\">CARTO</a>",
        "is_default": False,
        "sort_order": 2,
    },
    {
        "name": "Streets (OpenFreeMap)",
        "basemap_type": "vector",
        "style_url": "https://tiles.openfreemap.org/styles/liberty",
        "attribution": "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OSM</a>",
        "is_default": False,
        "sort_order": 3,
    },
    {
        "name": "Satellite",
        "basemap_type": "raster",
        "tile_url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        "attribution": "&copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community",
        "is_default": False,
        "sort_order": 4,
    },
]


def seed_basemaps(apps, schema_editor):
    Basemap = apps.get_model("workspace", "Basemap")
    for data in DEFAULT_BASEMAPS:
        Basemap.objects.get_or_create(name=data["name"], defaults=data)


def unseed_basemaps(apps, schema_editor):
    Basemap = apps.get_model("workspace", "Basemap")
    Basemap.objects.filter(name__in=[b["name"] for b in DEFAULT_BASEMAPS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0024_external_basemap_layer_group"),
    ]

    operations = [
        migrations.RunPython(seed_basemaps, unseed_basemaps),
    ]
