# Generated by Django 6.0.5 on 2026-05-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0025_seed_default_basemaps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemap',
            options={'ordering': ('sort_order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='layerfilter',
            options={'ordering': ('name',), 'verbose_name': 'Layer Filter', 'verbose_name_plural': 'Layer Filters'},
        ),
    ]
