# Generated by Django 6.0.5 on 2026-05-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0026_fix_layerfilter_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="User-specified column name mappings (e.g. {'pop': 'population'})."),
        ),
    ]
