# Generated by Django 6.0.5 on 2026-05-10 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0027_analysisrun_column_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='POICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Cache identifier (e.g. 'food_poi').", max_length=128)),
                ('geojson_data', models.JSONField(help_text='GeoJSON FeatureCollection of POI data.')),
                ('source', models.CharField(default='osm', help_text='Original data source.', max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poi_caches', to='workspace.workspace')),
            ],
            options={
                'verbose_name': 'POI Cache',
                'unique_together': {('workspace', 'name')},
            },
        ),
    ]
