# Generated by Django 6.0.5 on 2026-05-10 04:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0028_poicache'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='public_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='UUID token for public sharing link.', null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='published',
            field=models.BooleanField(default=False, help_text='Make this scenario publicly viewable.'),
        ),
    ]
