# Generated by Django 6.0.5 on 2026-05-10
# Migration to add Postgres helper functions for area calculation and clamping

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0029_scenario_public_token_scenario_published"),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                CREATE OR REPLACE FUNCTION public.acres(geom geometry)
                  RETURNS double precision
                  LANGUAGE sql IMMUTABLE PARALLEL SAFE
                  AS $$ SELECT ST_Area($1) / 4046.86 $$;

                CREATE OR REPLACE FUNCTION public.sqm_to_acres(sqm double precision)
                  RETURNS double precision
                  LANGUAGE sql IMMUTABLE PARALLEL SAFE
                  AS $$ SELECT $1 / 4046.86 $$;

                CREATE OR REPLACE FUNCTION public.intersection_acres(a geometry, b geometry)
                  RETURNS double precision
                  LANGUAGE sql IMMUTABLE PARALLEL SAFE
                  AS $$ SELECT COALESCE(ST_Area(ST_Intersection($1, $2)) / 4046.86, 0.0) $$;

                CREATE OR REPLACE FUNCTION public.clamp_non_negative(val double precision)
                  RETURNS double precision
                  LANGUAGE sql IMMUTABLE PARALLEL SAFE
                  AS $$ SELECT GREATEST(0.0, $1) $$;
            ''',
            reverse_sql='''
                DROP FUNCTION IF EXISTS public.acres(geom geometry);
                DROP FUNCTION IF EXISTS public.sqm_to_acres(sqm double precision);
                DROP FUNCTION IF EXISTS public.intersection_acres(a geometry, b geometry);
                DROP FUNCTION IF EXISTS public.clamp_non_negative(val double precision);
            ''',
        ),
    ]
