# Generated by Django 6.0.5 on 2026-05-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0030_add_acres_and_clamp_functions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimportrun',
            name='import_type',
            field=models.CharField(choices=[('allocate', 'Spatial Allocation'), ('census', 'Census ACS Demographics'), ('ejscreen', 'EJScreen Environmental Justice'), ('health_rankings', 'County Health Rankings'), ('lehd', 'LEHD Employment'), ('parkserve', 'ParkServe Park Data'), ('poi', 'Points of Interest'), ('raster', 'Raster Data'), ('stitch', 'Column Stitching'), ('svi', 'Social Vulnerability Index')], max_length=16),
        ),
    ]
