# Generated by Django 6.0.5 on 2026-05-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0032_basecanvas'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecanvas',
            name='assessor_use_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='basecanvas',
            name='land_use',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
