# Generated by Django 6.0.7 on 2026-07-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0033_basecanvas_assessor_use_code_basecanvas_land_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltFormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('built_form_category', models.CharField(max_length=64)),
                ('du_per_acre', models.FloatField(default=0)),
                ('pop_per_acre', models.FloatField(default=0)),
                ('hh_per_acre', models.FloatField(default=0)),
                ('emp_per_acre', models.FloatField(default=0)),
                ('du_detsf_sl_per_acre', models.FloatField(default=0)),
                ('du_detsf_ll_per_acre', models.FloatField(default=0)),
                ('du_attsf_per_acre', models.FloatField(default=0)),
                ('du_mf2to4_per_acre', models.FloatField(default=0)),
                ('du_mf5p_per_acre', models.FloatField(default=0)),
                ('emp_ret_per_acre', models.FloatField(default=0)),
                ('emp_off_per_acre', models.FloatField(default=0)),
                ('emp_pub_per_acre', models.FloatField(default=0)),
                ('emp_ind_per_acre', models.FloatField(default=0)),
                ('emp_ag_per_acre', models.FloatField(default=0)),
                ('intersection_density', models.FloatField(default=0)),
                ('building_sqft_per_acre', models.FloatField(default=0)),
                ('footprint_ratio', models.FloatField(default=0)),
                ('max_levels', models.IntegerField(default=1)),
                ('area_parcel_res', models.FloatField(default=0)),
                ('area_parcel_emp', models.FloatField(default=0)),
                ('area_parcel_mixed_use', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
    ]
