# Generated by Django 6.0.7 on 2026-07-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0034_builtformdefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='center_lat',
            field=models.FloatField(default=0.0, help_text='Default map center latitude.'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='center_lng',
            field=models.FloatField(default=0.0, help_text='Default map center longitude.'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='zoom',
            field=models.FloatField(default=10.0, help_text='Default map zoom level.'),
        ),
    ]
