# Generated by Django 6.0.7 on 2026-09-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0035_add_workspace_center_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='db_schema',
            field=models.CharField(blank=True, default='', help_text='Schema holding db_table; blank inherits the workspace schema.', max_length=64),
        ),
    ]
