# Generated by Django 6.0.8 on 2026-09-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0036_layer_db_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='base_table',
            field=models.CharField(blank=True, default='public.base_canvas', help_text="schema.table for this workspace's base canvas — the parcel/feature table that scenarios paint over. Defaults to the shared public.base_canvas table; can point at a SQLMesh-generated table with the required columns.", max_length=128),
        ),
    ]
