# Generated by Django 6.0.8 on 2026-09-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0042_data_source_remaining_import_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='tile_server_backend',
            field=models.CharField(choices=[('tipg', 'tipg'), ('martin', 'Martin')], default='tipg', help_text="Vector tile server used to render this workspace's layers.", max_length=16),
        ),
    ]
