# Generated by Django 6.0.8 on 2026-09-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0043_workspace_tile_server_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
