# Generated by Django 6.0.5 on 2026-09-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0044_layer_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingtype',
            name='electricity_eui',
            field=models.FloatField(blank=True, default=100.0, help_text='Energy use intensity for electricity. Defaults to 100 kWh/m²/yr.', null=True, verbose_name='Electricity EUI (kWh/m²/yr)'),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='gas_eui',
            field=models.FloatField(blank=True, default=50.0, help_text='Energy use intensity for natural gas. Defaults to 50 kWh/m²/yr.', null=True, verbose_name='Gas EUI (kWh/m²/yr)'),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='indoor_water_rate',
            field=models.FloatField(blank=True, default=200.0, help_text='Defaults to 200 L/person/day (typical US residential indoor use).', null=True, verbose_name='Indoor water use (L/person/day)'),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='irrigable_area_fraction',
            field=models.FloatField(blank=True, default=0.3, help_text='Fraction of open space that is irrigated. Defaults to 0.3.', null=True, verbose_name='Irrigable area fraction'),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='outdoor_water_rate',
            field=models.FloatField(blank=True, default=100.0, help_text='Defaults to 100 L/m²/yr (typical turf irrigation rate).', null=True, verbose_name='Outdoor water use (L/m²/year)'),
        ),
    ]
