# Generated by Django 6.0.8 on 2026-09-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0045_alter_buildingtype_electricity_eui_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintedcanvas',
            name='painted_text_value',
            field=models.CharField(blank=True, help_text='Override value for text-valued columns (e.g. built_form_key). painted_value is used for every other (numeric) paintable column.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paintedcanvas',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Approval status for merge operations.', max_length=16),
        ),
    ]
