# Generated by Django 6.0.8 on 2026-09-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0046_paintedcanvas_painted_text_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintevent',
            name='new_text_value',
            field=models.CharField(blank=True, help_text='New value for text-valued columns (e.g. built_form_key); new_value is used for every other (numeric) column.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='paintevent',
            name='old_text_value',
            field=models.CharField(blank=True, help_text='Old value for text-valued columns (e.g. built_form_key); old_value is used for every other (numeric) column.', max_length=128, null=True),
        ),
    ]
