# Generated by Django 6.0.8 on 2026-09-13 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0047_paintevent_new_text_value_paintevent_old_text_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('direct', 'Direct Column Paint'), ('built_form', 'Built Form Paint'), ('match', 'Match Closest Built Form'), ('fill', 'Fill From Built Form')], max_length=16)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Validated request body (features, plus column/value or bf_type/bf_id).')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Final response body once complete (painted_count, warnings, etc.).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paint_runs', to='workspace.scenario')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paint_runs', to='workspace.workspace')),
            ],
            options={
                'verbose_name': 'Paint Run',
                'ordering': ('-created_at',),
            },
        ),
    ]
