# Generated by Django 6.0.5 on 2026-09-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0048_paintrun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ('group__display_order', 'group__name', 'display_order')},
        ),
    ]
