# Generated by Django 6.0.8 on 2026-09-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0049_alter_layer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='log_output',
            field=models.TextField(blank=True, default='', help_text="Captured INFO+ log output from the SQLMesh run (progress, warnings, and the real per-node error when a plan fails — SQLMesh's own exception discards that detail)."),
        ),
    ]
