# Generated by Django 6.0.8 on 2026-09-21 14:26

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0050_analysisrun_log_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingtype",
            name="pass_by_trip_pct",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Percent of trips that are pass-by (diverted from passing traffic).",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="Pass-by trip (%)",
            ),
        ),
    ]
