# Generated by Django 6.0.8 on 2026-09-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0052_base_canvas_parcel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="failure_cause",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short, human-readable cause of a failed run (failing model plus the database error underneath it), recovered from the SQLMesh plan log. Empty when the failure produced no parseable per-node error.",
            ),
        ),
    ]
