# Generated by Django 6.0.8 on 2026-09-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0053_analysisrun_failure_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Analysis column mapping {canonical_name: user_column} for this scenario's parcel source (see module_registry.CANONICAL_COLUMN_NAMES)."),
        ),
        migrations.AddField(
            model_name='scenario',
            name='constraints',
            field=models.JSONField(blank=True, default=list, help_text="Analysis constraint layers: [{table, discount_pct, geom_col}]. Baked into this scenario's analysis model blueprints."),
        ),
    ]
