# Generated by Django 6.0.8 on 2026-09-22 22:08
#
# The trailing RunSQL creates the sequence the grid tool takes synthetic cell
# ids from (`str(-nextval('parcel_geometry_edit_id_seq'))`): a negative integer
# is collision-free against real parcel ids, which are positive BIGINT (sacog)
# or APN strings (fresno). It ships in the same migration as the model it keys.

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0057_zero_transparent_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintevent',
            name='operation_type',
            field=models.CharField(choices=[('paint', 'Paint'), ('clear', 'Clear'), ('built_form', 'Built Form Paint'), ('grid', 'Grid'), ('merge', 'Merge'), ('undo', 'Undo')], max_length=16),
        ),
        migrations.AlterField(
            model_name='paintrun',
            name='operation',
            field=models.CharField(choices=[('direct', 'Direct Column Paint'), ('built_form', 'Built Form Paint'), ('match', 'Match Closest Built Form'), ('fill', 'Fill From Built Form'), ('grid', 'Grid Parcels'), ('merge', 'Merge Parcels')], max_length=16),
        ),
        migrations.CreateModel(
            name='ParcelGeometryEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(help_text="Result feature id: a negative-integer string for a grid cell, the surviving parcel's id for a merge. Matches PaintedCanvas.feature_id, so paint overrides join to edited features.", max_length=128)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('values', models.JSONField(default=dict, help_text='Every base canvas column except parcel_id and geometry, allocated from the replaced parcels (extensive totals conserved).')),
                ('source_parcel_ids', models.JSONField(default=list, help_text='Base feature ids (strings) this row replaces; the canvas view hides these rows for as long as this edit exists.')),
                ('operation', models.CharField(choices=[('grid', 'Grid'), ('merge', 'Merge')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.CharField(db_index=True, max_length=64)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_geometry_edits', to='workspace.scenario')),
            ],
            options={
                'verbose_name': 'parcel geometry edit',
                'indexes': [models.Index(fields=['scenario', 'parcel_id'], name='workspace_p_scenari_021e28_idx')],
            },
        ),
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS parcel_geometry_edit_id_seq START 1",
            reverse_sql="DROP SEQUENCE IF EXISTS parcel_geometry_edit_id_seq",
        ),
    ]
