# Generated by Django 6.0.8 on 2026-09-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0058_parcelgeometryedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='analysis_params',
            field=models.JSONField(blank=True, default=dict, help_text="Analysis parameter overrides for this scenario's analysis models (see module_registry.ANALYSIS_PARAMETERS). Baked into the scenario's analysis model blueprints."),
        ),
    ]
