# Generated by Django 6.0.8 on 2026-09-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0059_scenario_analysis_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='fill_built_form',
            field=models.BooleanField(default=False, help_text='Fill NULL built-form columns (built_form_key, du, pop, hh, emp) on the base layer from the closest-matching Building Type. Materializes a new table; base_table itself is never modified.'),
        ),
    ]
