# Generated by Django 6.0.8 on 2026-09-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0060_workspace_fill_built_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='fill_built_form',
            field=models.BooleanField(default=False, help_text='Assign every parcel the closest-matching Building Type and fill NULL built-form columns (du, pop, hh, emp). built_form_key is reassigned from the match, replacing any key already set. Materializes a new table; base_table itself is never modified.'),
        ),
    ]
