# Generated by Django 6.0.8 on 2026-09-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0061_alter_workspace_fill_built_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='failure_cause',
            field=models.TextField(blank=True, default='', help_text='Short, human-readable cause of a failed run (failing model plus the database error underneath it), recovered from the SQLMesh plan log — or, when the plan never reached a node, from the exception chain. Populated whenever the run fails.'),
        ),
    ]
