# Generated by Django 6.0.8 on 2026-09-25 04:47
# Drop BuiltFormDefinition: superseded by built_forms.BuildingType, whose rows
# are what nearest-prototype matching reads (views/paint.py match/fill and
# sqlmesh/models/base_canvas/built_form_fill.py). The public table below was
# the export target of the removed BuiltFormDefinition -> SQLMesh bridge
# (services/built_form_definitions.py, consumed by the removed parcel_bft_match
# model), so nothing writes or reads it any more.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0062_alter_analysisrun_failure_cause"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BuiltFormDefinition",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS public.built_form_definitions CASCADE",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
