# Generated by Django 6.0.8 on 2026-09-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0063_delete_builtformdefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='land_development_category',
            field=models.CharField(blank=True, choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial'), ('undeveloped', 'Undeveloped'), ('conservation', 'Conservation')], default='', help_text='Development category used to prefer same-category matches when assigning built forms.', max_length=32, verbose_name='Land development category'),
        ),
    ]
