# Generated by Django 6.0.8 on 2026-09-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0065_seed_default_built_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingtype',
            name='household_size',
            field=models.FloatField(blank=True, default=2.5, help_text='Average persons per household. Null = the type has no housing.', null=True, verbose_name='Household size'),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='vacancy_rate',
            field=models.FloatField(blank=True, default=5.0, help_text='Percent of dwelling units vacant. Null = the type has no housing.', null=True, verbose_name='Vacancy rate (%)'),
        ),
    ]
