# Generated by Django 6.0.8 on 2026-09-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0066_alter_buildingtype_household_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingtype',
            name='land_development_category',
            field=models.CharField(blank=True, choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial'), ('undeveloped', 'Undeveloped'), ('conservation', 'Conservation')], default='', help_text='Category closest-matching requires: this type is only ever assigned to a parcel whose own land development category is the same value. A type left blank is never assigned to a parcel that names a category.', max_length=32, verbose_name='Land development category'),
        ),
    ]
