# Generated by Django 6.0.8 on 2026-09-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0067_alter_buildingtype_land_development_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='base_table',
            field=models.CharField(blank=True, default='public.base_canvas', help_text="schema.table for this workspace's base canvas — the parcel/feature table that scenarios paint over. Defaults to the shared public.base_canvas table; can point at any loaded table with the required base-canvas columns, a SQLMesh model's view or an imported one alike.", max_length=128),
        ),
    ]
