# Generated by Django 6.0.8 on 2026-09-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0068_alter_workspace_base_table_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, help_text='Wall-clock of the last liveness ping from whoever is executing this run. A pending/running run whose ping has gone quiet has no executor left — see brewgis.workspace.analysis.run_health.', null=True),
        ),
    ]
