# Generated by Django 6.0.8 on 2026-09-29 18:27
"""Restate the fill toggle's help text: a real built form key is kept.

The fill now keeps a ``built_form_key`` that names one of the workspace's
Building Types, and only replaces the keys that name none — the pipeline's
``mixed_use`` placeholder, a blank, a NULL. Metadata only; no data changes.
"""

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0072_seed_poi_built_forms_library_entries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="fill_built_form",
            field=models.BooleanField(
                default=False,
                help_text="Assign every parcel the closest-matching Building Type where its built_form_key names none of this workspace's Building Types — the pipeline's mixed_use placeholder, a blank and a NULL — and fill NULL built-form columns (du, pop, hh, emp). A key that already names a Building Type is kept. Materializes a new table; base_table itself is never modified.",
            ),
        ),
    ]
