# Generated by Django 6.0.9 on 2026-10-08 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0073_alter_workspace_fill_built_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerfilter',
            name='is_active',
        ),
        migrations.AddField(
            model_name='layer',
            name='source_filter',
            field=models.OneToOneField(blank=True, help_text='The filter whose matching rows this layer draws: applying a LayerFilter materializes a new table and registers it as this new layer, leaving the filtered layer untouched. Deleting the filter deletes this layer; deleting this layer un-applies the filter.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_layer', to='workspace.layerfilter'),
        ),
    ]
