MODEL (
  name brewgis.seeds.test_base_canvas,
  kind SEED (
    path '../../seeds/test_base_canvas.csv'
  ),
  columns (
    id TEXT,
    geometry geometry(Geometry,4326),
    id_source TEXT,
    geometry_key TEXT,
    land_development_category TEXT,
    built_form_key TEXT,
    intersection_density DOUBLE PRECISION,
    area_gross DOUBLE PRECISION,
    area_parcel DOUBLE PRECISION,
    area_dev_condition DOUBLE PRECISION,
    area_row DOUBLE PRECISION,
    pop DOUBLE PRECISION,
    hh DOUBLE PRECISION,
    du DOUBLE PRECISION,
    emp DOUBLE PRECISION,
    bldg_area_detsf_sl DOUBLE PRECISION,
    bldg_area_detsf_ll DOUBLE PRECISION,
    bldg_area_attsf DOUBLE PRECISION,
    bldg_area_mf DOUBLE PRECISION,
    bldg_area_retail_services DOUBLE PRECISION,
    bldg_area_restaurant DOUBLE PRECISION,
    bldg_area_accommodation DOUBLE PRECISION,
    bldg_area_arts_entertainment DOUBLE PRECISION,
    bldg_area_other_services DOUBLE PRECISION,
    bldg_area_office_services DOUBLE PRECISION,
    bldg_area_public_admin DOUBLE PRECISION,
    bldg_area_education DOUBLE PRECISION,
    bldg_area_medical_services DOUBLE PRECISION,
    bldg_area_transport_warehousing DOUBLE PRECISION,
    bldg_area_wholesale DOUBLE PRECISION,
    residential_irrigated_area DOUBLE PRECISION,
    commercial_irrigated_area DOUBLE PRECISION
  )
);
