MODEL (
  name brewgis.seeds.test_base_canvas,
  kind SEED (
    path '../../seeds/test_base_canvas.csv'
  ),
  description 'Test fixture: 12 synthetic base canvas rows for the stage_test_stage_full unit test.',
  column_descriptions (
    parcel_id = 'Identifier of the fixture base canvas row.',
    geometry = 'Base canvas geometry stored as a point in EPSG:4326 (WGS 84).',
    id_source = 'Source the parcel identifier came from (text).',
    geometry_key = 'Key identifying the geometry variant of the row.',
    land_development_category = 'Land development category of the base canvas row.',
    built_form_key = 'Built form key of the base canvas row.',
    intersection_density = 'Intersection density at the row (intersections per km2).',
    area_gross = 'Gross area of the base canvas row (acres).',
    area_parcel = 'Parcel area (acres).',
    area_dev_condition = 'Development condition area (acres).',
    area_row = 'Right-of-way area (acres).',
    pop = 'Population assigned to the row (people).',
    hh = 'Household count of the row.',
    du = 'Dwelling unit count of the row.',
    emp = 'Employment assigned to the row (jobs).',
    bldg_area_detsf_sl = 'Detached single-family small-lot building area (sq ft).',
    bldg_area_detsf_ll = 'Detached single-family large-lot building area (sq ft).',
    bldg_area_attsf = 'Attached single-family building area (sq ft).',
    bldg_area_mf = 'Multi-family building area (sq ft).',
    bldg_area_retail_services = 'Retail services building area (sq ft).',
    bldg_area_restaurant = 'Restaurant building area (sq ft).',
    bldg_area_accommodation = 'Accommodation building area (sq ft).',
    bldg_area_arts_entertainment = 'Arts and entertainment building area (sq ft).',
    bldg_area_other_services = 'Other services building area (sq ft).',
    bldg_area_office_services = 'Office services building area (sq ft).',
    bldg_area_public_admin = 'Public administration building area (sq ft).',
    bldg_area_education = 'Education building area (sq ft).',
    bldg_area_medical_services = 'Medical services building area (sq ft).',
    bldg_area_transport_warehousing = 'Transport and warehousing building area (sq ft).',
    bldg_area_wholesale = 'Wholesale building area (sq ft).',
    residential_irrigated_area = 'Residential irrigated area of the base canvas row (acres).',
    commercial_irrigated_area = 'Commercial irrigated area of the base canvas row (acres).'
  ),
  columns (
    parcel_id TEXT,
    geometry geometry(Geometry,4326),
    id_source TEXT,
    geometry_key TEXT,
    land_development_category TEXT,
    built_form_key TEXT,
    intersection_density DOUBLE PRECISION,
    area_gross DOUBLE PRECISION,
    area_parcel DOUBLE PRECISION,
    area_dev_condition DOUBLE PRECISION,
    area_row DOUBLE PRECISION,
    pop DOUBLE PRECISION,
    hh DOUBLE PRECISION,
    du DOUBLE PRECISION,
    emp DOUBLE PRECISION,
    bldg_area_detsf_sl DOUBLE PRECISION,
    bldg_area_detsf_ll DOUBLE PRECISION,
    bldg_area_attsf DOUBLE PRECISION,
    bldg_area_mf DOUBLE PRECISION,
    bldg_area_retail_services DOUBLE PRECISION,
    bldg_area_restaurant DOUBLE PRECISION,
    bldg_area_accommodation DOUBLE PRECISION,
    bldg_area_arts_entertainment DOUBLE PRECISION,
    bldg_area_other_services DOUBLE PRECISION,
    bldg_area_office_services DOUBLE PRECISION,
    bldg_area_public_admin DOUBLE PRECISION,
    bldg_area_education DOUBLE PRECISION,
    bldg_area_medical_services DOUBLE PRECISION,
    bldg_area_transport_warehousing DOUBLE PRECISION,
    bldg_area_wholesale DOUBLE PRECISION,
    residential_irrigated_area DOUBLE PRECISION,
    commercial_irrigated_area DOUBLE PRECISION
  )
);
