MODEL (
  name brewgis.seeds.test_parcels,
  kind SEED (
    path '../../seeds/test_parcels.csv'
  ),
  description 'Test fixture: 16 synthetic parcels for the stage_test_parcels staging view unit test.',
  column_descriptions (
    parcel_id = 'Identifier of the fixture parcel (text).',
    geometry = 'Parcel polygon geometry in EPSG:4326 (WGS 84).',
    county = 'County name the parcel lies in.',
    pop_observed = 'Observed population of the parcel before estimation (people).',
    hh_observed = 'Observed household count of the parcel before estimation.',
    du_observed = 'Observed dwelling unit count of the parcel before estimation.',
    emp_observed = 'Observed employment count of the parcel before estimation (jobs).',
    pop = 'Modeled population assigned to the parcel (people).',
    hh = 'Modeled household count assigned to the parcel.',
    du = 'Modeled dwelling unit count assigned to the parcel.',
    emp = 'Modeled employment assigned to the parcel (jobs).',
    land_development_category = 'Land development category of the parcel used by the calibration seeds.',
    built_form_key = 'Built form key classifying the parcel built form.',
    intersection_density = 'Intersection density at the parcel (intersections per km2).',
    land_use = 'Land use label of the parcel (text).',
    assessor_use_code = 'Assessor use code of the parcel, mapped to a category by the assessor_use_codes seed.',
    bldg_area_detsf_sl = 'Detached single-family small-lot building area (sq ft).',
    bldg_area_detsf_ll = 'Detached single-family large-lot building area (sq ft).',
    bldg_area_attsf = 'Attached single-family building area (sq ft).',
    bldg_area_mf = 'Multi-family building area (sq ft).',
    bldg_area_retail_services = 'Retail services building area (sq ft).',
    bldg_area_restaurant = 'Restaurant building area (sq ft).',
    bldg_area_accommodation = 'Accommodation building area (sq ft).',
    bldg_area_arts_entertainment = 'Arts and entertainment building area (sq ft).',
    bldg_area_other_services = 'Other services building area (sq ft).',
    bldg_area_office_services = 'Office services building area (sq ft).',
    bldg_area_public_admin = 'Public administration building area (sq ft).',
    bldg_area_education = 'Education building area (sq ft).',
    bldg_area_medical_services = 'Medical services building area (sq ft).',
    bldg_area_transport_warehousing = 'Transport and warehousing building area (sq ft).',
    bldg_area_wholesale = 'Wholesale building area (sq ft).',
    residential_irrigated_area = 'Residential irrigated area of the base canvas row (acres).',
    commercial_irrigated_area = 'Commercial irrigated area of the base canvas row (acres).',
    area_parcel_res = 'Total residential parcel area (acres).',
    area_parcel_emp_ag = 'Agricultural employment parcel area (acres).',
    area_parcel_emp = 'Total employment parcel area (acres).',
    area_parcel_mixed_use = 'Mixed use parcel area (acres).',
    area_parcel_no_use = 'Parcel area with no assigned use (acres).'
  ),
  columns (
    parcel_id TEXT,
    geometry geometry(Geometry,4326),
    county TEXT,
    pop_observed DOUBLE PRECISION,
    hh_observed DOUBLE PRECISION,
    du_observed DOUBLE PRECISION,
    emp_observed DOUBLE PRECISION,
    pop DOUBLE PRECISION,
    hh DOUBLE PRECISION,
    du DOUBLE PRECISION,
    emp DOUBLE PRECISION,
    land_development_category TEXT,
    built_form_key TEXT,
    intersection_density DOUBLE PRECISION,
    land_use TEXT,
    assessor_use_code TEXT,
    bldg_area_detsf_sl DOUBLE PRECISION,
    bldg_area_detsf_ll DOUBLE PRECISION,
    bldg_area_attsf DOUBLE PRECISION,
    bldg_area_mf DOUBLE PRECISION,
    bldg_area_retail_services DOUBLE PRECISION,
    bldg_area_restaurant DOUBLE PRECISION,
    bldg_area_accommodation DOUBLE PRECISION,
    bldg_area_arts_entertainment DOUBLE PRECISION,
    bldg_area_other_services DOUBLE PRECISION,
    bldg_area_office_services DOUBLE PRECISION,
    bldg_area_public_admin DOUBLE PRECISION,
    bldg_area_education DOUBLE PRECISION,
    bldg_area_medical_services DOUBLE PRECISION,
    bldg_area_transport_warehousing DOUBLE PRECISION,
    bldg_area_wholesale DOUBLE PRECISION,
    residential_irrigated_area DOUBLE PRECISION,
    commercial_irrigated_area DOUBLE PRECISION,
    area_parcel_res DOUBLE PRECISION,
    area_parcel_emp_ag DOUBLE PRECISION,
    area_parcel_emp DOUBLE PRECISION,
    area_parcel_mixed_use DOUBLE PRECISION,
    area_parcel_no_use DOUBLE PRECISION
  )
);
