MODEL (
  name brewgis.seeds.test_parcels,
  kind SEED (
    path '../../seeds/test_parcels.csv'
  ),
  columns (
    parcel_id TEXT,
    geometry geometry(Geometry,4326),
    county TEXT,
    pop_observed TEXT,
    hh_observed TEXT,
    du_observed TEXT,
    emp_observed TEXT,
    pop TEXT,
    hh TEXT,
    du TEXT,
    emp TEXT,
    land_development_category TEXT,
    built_form_key TEXT,
    intersection_density TEXT,
    land_use TEXT,
    assessor_use_code TEXT,
    bldg_area_detsf_sl TEXT,
    bldg_area_detsf_ll TEXT,
    bldg_area_attsf TEXT,
    bldg_area_mf TEXT,
    bldg_area_retail_services TEXT,
    bldg_area_restaurant TEXT,
    bldg_area_accommodation TEXT,
    bldg_area_arts_entertainment TEXT,
    bldg_area_other_services TEXT,
    bldg_area_office_services TEXT,
    bldg_area_public_admin TEXT,
    bldg_area_education TEXT,
    bldg_area_medical_services TEXT,
    bldg_area_transport_warehousing TEXT,
    bldg_area_wholesale TEXT,
    residential_irrigated_area TEXT,
    commercial_irrigated_area TEXT,
    area_parcel_res TEXT,
    area_parcel_emp_ag TEXT,
    area_parcel_emp TEXT,
    area_parcel_mixed_use TEXT,
    area_parcel_no_use TEXT
  )
);
