MODEL (
  name brewgis.seeds.test_parcels,
  kind SEED (
    path '../../seeds/test_parcels.csv'
  ),
  columns (
    parcel_id TEXT,
    geometry geometry(Geometry,4326),
    county TEXT,
    pop_observed DOUBLE PRECISION,
    hh_observed DOUBLE PRECISION,
    du_observed DOUBLE PRECISION,
    emp_observed DOUBLE PRECISION,
    pop DOUBLE PRECISION,
    hh DOUBLE PRECISION,
    du DOUBLE PRECISION,
    emp DOUBLE PRECISION,
    land_development_category TEXT,
    built_form_key TEXT,
    intersection_density DOUBLE PRECISION,
    land_use TEXT,
    assessor_use_code TEXT,
    bldg_area_detsf_sl DOUBLE PRECISION,
    bldg_area_detsf_ll DOUBLE PRECISION,
    bldg_area_attsf DOUBLE PRECISION,
    bldg_area_mf DOUBLE PRECISION,
    bldg_area_retail_services DOUBLE PRECISION,
    bldg_area_restaurant DOUBLE PRECISION,
    bldg_area_accommodation DOUBLE PRECISION,
    bldg_area_arts_entertainment DOUBLE PRECISION,
    bldg_area_other_services DOUBLE PRECISION,
    bldg_area_office_services DOUBLE PRECISION,
    bldg_area_public_admin DOUBLE PRECISION,
    bldg_area_education DOUBLE PRECISION,
    bldg_area_medical_services DOUBLE PRECISION,
    bldg_area_transport_warehousing DOUBLE PRECISION,
    bldg_area_wholesale DOUBLE PRECISION,
    residential_irrigated_area DOUBLE PRECISION,
    commercial_irrigated_area DOUBLE PRECISION,
    area_parcel_res DOUBLE PRECISION,
    area_parcel_emp_ag DOUBLE PRECISION,
    area_parcel_emp DOUBLE PRECISION,
    area_parcel_mixed_use DOUBLE PRECISION,
    area_parcel_no_use DOUBLE PRECISION
  )
);
