MODEL (
  name brewgis.seeds.test_wac_block,
  kind SEED (
    path '../../seeds/test_wac_block.csv'
  ),
  description 'Test fixture: 3 synthetic WAC blocks for the test_stage_wac_blocks staging view unit test.',
  column_descriptions (
    geoid = 'Census block GEOID (15-digit FIPS).',
    emp = 'Total employment in the block (jobs).',
    emp_retail_services = 'Retail services employment in the block (jobs).',
    emp_restaurant = 'Restaurant employment in the block (jobs).',
    emp_accommodation = 'Accommodation employment in the block (jobs).',
    emp_arts_entertainment = 'Arts and entertainment employment in the block (jobs).',
    emp_other_services = 'Other services employment in the block (jobs).',
    emp_office_services = 'Office services employment in the block (jobs).',
    emp_medical_services = 'Medical services employment in the block (jobs).',
    emp_public_admin = 'Public administration employment in the block (jobs).',
    emp_education = 'Education employment in the block (jobs).',
    emp_manufacturing = 'Manufacturing employment in the block (jobs).',
    emp_wholesale = 'Wholesale employment in the block (jobs).',
    emp_transport_warehousing = 'Transport and warehousing employment in the block (jobs).',
    emp_utilities = 'Utilities employment in the block (jobs).',
    emp_construction = 'Construction employment in the block (jobs).',
    emp_agriculture = 'Agriculture employment in the block (jobs).',
    emp_extraction = 'Extraction employment in the block (jobs).',
    emp_military = 'Military employment in the block (jobs).',
    emp_ret = 'Rolled-up retail employment in the block (jobs), the five retail sub-sectors summed.',
    emp_off = 'Rolled-up office employment in the block (jobs), office plus medical services.',
    emp_pub = 'Rolled-up public employment in the block (jobs), education plus public administration.',
    emp_ind = 'Rolled-up industrial employment in the block (jobs), the five industrial sub-sectors summed.',
    emp_ag = 'Rolled-up agricultural employment in the block (jobs), agriculture plus extraction.',
    geometry = 'Block boundary polygon in EPSG:4326 (WGS 84).'
  ),
  columns (
    geoid TEXT,
    emp INTEGER,
    emp_retail_services INTEGER,
    emp_restaurant INTEGER,
    emp_accommodation INTEGER,
    emp_arts_entertainment INTEGER,
    emp_other_services INTEGER,
    emp_office_services INTEGER,
    emp_medical_services INTEGER,
    emp_public_admin INTEGER,
    emp_education INTEGER,
    emp_manufacturing INTEGER,
    emp_wholesale INTEGER,
    emp_transport_warehousing INTEGER,
    emp_utilities INTEGER,
    emp_construction INTEGER,
    emp_agriculture INTEGER,
    emp_extraction INTEGER,
    emp_military INTEGER,
    emp_ret INTEGER,
    emp_off INTEGER,
    emp_pub INTEGER,
    emp_ind INTEGER,
    emp_ag INTEGER,
    geometry geometry(Geometry,4326)
  )
);
