MODEL (
  name brewgis.sacog.comparison,
  kind FULL,
  description 'SACOG comparison view of reconciled base canvas parcels, plus geography_id and NULL area columns.',
  column_descriptions (
    parcel_id = 'Parcel identifier from the reconciled base canvas (Feature ID).',
    geometry = 'Parcel geometry (MultiPolygon, EPSG:4326).',
    county = 'County name assigned to the parcel by the region blueprint (Sacramento for SACOG).',
    land_development_category = 'Land development category (land use class) assigned by the base canvas.',
    built_form_key = 'Built form key classifying the development form of the parcel.',
    intersection_density = 'Intersection density around the parcel (intersections per km2).',
    area_gross = 'Gross area of the parcel (acres).',
    area_gross_acres = 'Gross area of the parcel (acres; rounded duplicate of area_gross).',
    area_parcel_acres = 'Parcel area (acres).',
    area_dev_condition_acres = 'Development condition area of the parcel (acres).',
    area_row_acres = 'Right-of-way area of the parcel (acres).',
    area_parcel_res = 'Residential parcel area (acres).',
    area_parcel_res_acres = 'Residential parcel area (acres; duplicate of area_parcel_res).',
    area_parcel_emp_ag = 'Agricultural employment parcel area (acres).',
    area_parcel_emp_ag_acres = 'Agricultural employment parcel area (acres; duplicate of area_parcel_emp_ag).',
    area_parcel_emp = 'Employment parcel area (acres).',
    area_parcel_emp_acres = 'Employment parcel area (acres; duplicate of area_parcel_emp).',
    area_parcel_mixed_use = 'Mixed-use parcel area (acres).',
    area_parcel_mixed_use_acres = 'Mixed-use parcel area (acres; duplicate of area_parcel_mixed_use).',
    area_parcel_no_use = 'No-use parcel area (acres).',
    area_parcel_no_use_acres = 'No-use parcel area (acres; duplicate of area_parcel_no_use).',
    pop = 'Population of the parcel (people).',
    pop_groupquarter = 'Group quarters population of the parcel (people).',
    hh = 'Households in the parcel (count).',
    du = 'Dwelling units in the parcel (count).',
    du_detsf = 'Detached sf dwelling units in the parcel (count).',
    du_detsf_sl = 'Detached sf small-lot dwelling units in the parcel (count).',
    du_detsf_ll = 'Detached sf large-lot dwelling units in the parcel (count).',
    du_attsf = 'Attached sf dwelling units in the parcel (count).',
    du_mf = 'Multi-family dwelling units in the parcel (count).',
    du_mf2to4 = 'Multi-family 2-4 unit dwelling units in the parcel (count).',
    du_mf5p = 'Multi-family 5+ unit dwelling units in the parcel (count).',
    emp_ret = 'Retail employment: sum of the five retail services employment subtypes (count).',
    emp_retail_services = 'Retail services employment in the parcel (count).',
    emp_restaurant = 'Restaurant employment in the parcel (count).',
    emp_accommodation = 'Accommodation employment in the parcel (count).',
    emp_arts_entertainment = 'Arts and entertainment employment in the parcel (count).',
    emp_other_services = 'Other services employment in the parcel (count).',
    emp_off = 'Office employment: office services plus medical services employment (count).',
    emp_office_services = 'Office services employment in the parcel (count).',
    emp_medical_services = 'Medical services employment in the parcel (count).',
    emp_pub = 'Public employment: public administration plus education employment (count).',
    emp_public_admin = 'Public administration employment in the parcel (count).',
    emp_education = 'Education employment in the parcel (count).',
    emp_ind = 'Industrial employment: sum of the five industrial employment subtypes (count).',
    emp_manufacturing = 'Manufacturing employment in the parcel (count).',
    emp_wholesale = 'Wholesale employment in the parcel (count).',
    emp_transport_warehousing = 'Transport/warehousing employment in the parcel (count).',
    emp_utilities = 'Utilities employment in the parcel (count).',
    emp_construction = 'Construction employment in the parcel (count).',
    emp_ag = 'Agricultural employment: agriculture plus extraction employment (count).',
    emp_agriculture = 'Agriculture employment in the parcel (count; detailed subtype).',
    emp_extraction = 'Extraction employment in the parcel (count).',
    emp = 'Total employment of the parcel (count; sum of all employment subtypes).',
    emp_military = 'Military employment of the parcel (count).',
    bldg_area_detsf_sl = 'Detached sf small-lot building floor area of the parcel (sq ft).',
    bldg_area_detsf_ll = 'Detached sf large-lot building floor area of the parcel (sq ft).',
    bldg_area_attsf = 'Attached sf building floor area of the parcel (sq ft).',
    bldg_area_mf = 'Multi-family building floor area of the parcel (sq ft).',
    bldg_area_retail_services = 'Retail services building floor area of the parcel (sq ft).',
    bldg_area_restaurant = 'Restaurant building floor area of the parcel (sq ft).',
    bldg_area_accommodation = 'Accommodation building floor area of the parcel (sq ft).',
    bldg_area_arts_entertainment = 'Arts and entertainment building floor area of the parcel (sq ft).',
    bldg_area_other_services = 'Other services building floor area of the parcel (sq ft).',
    bldg_area_office_services = 'Office services building floor area of the parcel (sq ft).',
    bldg_area_public_admin = 'Public administration building floor area of the parcel (sq ft).',
    bldg_area_education = 'Education building floor area of the parcel (sq ft).',
    bldg_area_medical_services = 'Medical services building floor area of the parcel (sq ft).',
    bldg_area_transport_warehousing = 'Transport and warehousing building floor area of the parcel (sq ft).',
    bldg_area_wholesale = 'Wholesale building floor area of the parcel (sq ft).',
    residential_irrigated_area = 'Residential irrigated area of the parcel (acres).',
    commercial_irrigated_area = 'Commercial irrigated area of the parcel (acres).',
    median_income = 'Household median income of the parcel ($ per year).',
    rent_burden_pct = 'Share of households paying more than 30 percent of income on rent (% as 0-100).',
    pct_minority = 'Percent people of color in the parcel (% as 0-100).',
    pct_college_educated = 'Percent college-educated residents in the parcel (% as 0-100).',
    cost_burden_pct = 'Share of households paying more than 30 percent of income on housing (% as 0-100).',
    area_parcel_res_detsf = 'Not populated: detached SF parcel area is a NULL placeholder (acres).',
    area_parcel_res_detsf_sl = 'Not populated: detached SF small-lot parcel area is a NULL placeholder (acres).',
    area_parcel_res_detsf_ll = 'Not populated: detached SF large-lot parcel area is a NULL placeholder (acres).',
    area_parcel_res_attsf = 'Not populated: attached SF parcel area is a NULL placeholder (acres).',
    area_parcel_res_mf = 'Not populated: multi-family parcel area is a NULL placeholder (acres).',
    area_parcel_emp_ret = 'Not populated: retail employment parcel area is a NULL placeholder (acres).',
    area_parcel_emp_off = 'Not populated: office employment parcel area is a NULL placeholder (acres).',
    area_parcel_emp_pub = 'Not populated: public employment parcel area is a NULL placeholder (acres).',
    area_parcel_emp_ind = 'Not populated: industrial employment parcel area is a NULL placeholder (acres).',
    area_parcel_emp_military = 'Not populated: military employment parcel area is a NULL placeholder (acres).',
    geography_id = 'SACOG geography id assigned to the parcel by public.sacog_comparison_parcels.'
  ),
  audits (
    not_null(columns := (parcel_id))
  )
);

-- SACOG BrewGIS Comparison View — wraps base_canvas_reconciled with geography_id
-- and NULL columns for detailed area breakdowns needed by correlation models.

SELECT
    bcr.parcel_id,
    bcr.geometry,
    bcr.county,
    bcr.land_development_category,
    bcr.built_form_key,
    bcr.intersection_density,
    bcr.area_gross,
    bcr.area_gross_acres,
    bcr.area_parcel_acres,
    bcr.area_dev_condition_acres,
    bcr.area_row_acres,
    bcr.area_parcel_res,
    bcr.area_parcel_res_acres,
    bcr.area_parcel_emp_ag,
    bcr.area_parcel_emp_ag_acres,
    bcr.area_parcel_emp,
    bcr.area_parcel_emp_acres,
    bcr.area_parcel_mixed_use,
    bcr.area_parcel_mixed_use_acres,
    bcr.area_parcel_no_use,
    bcr.area_parcel_no_use_acres,
    bcr.pop,
    bcr.pop_groupquarter,
    bcr.hh,
    bcr.du,
    bcr.du_detsf,
    bcr.du_detsf_sl,
    bcr.du_detsf_ll,
    bcr.du_attsf,
    bcr.du_mf,
    bcr.du_mf2to4,
    bcr.du_mf5p,
    bcr.emp_ret,
    bcr.emp_retail_services,
    bcr.emp_restaurant,
    bcr.emp_accommodation,
    bcr.emp_arts_entertainment,
    bcr.emp_other_services,
    bcr.emp_off,
    bcr.emp_office_services,
    bcr.emp_medical_services,
    bcr.emp_pub,
    bcr.emp_public_admin,
    bcr.emp_education,
    bcr.emp_ind,
    bcr.emp_manufacturing,
    bcr.emp_wholesale,
    bcr.emp_transport_warehousing,
    bcr.emp_utilities,
    bcr.emp_construction,
    bcr.emp_ag,
    bcr.emp_agriculture,
    bcr.emp_extraction,
    bcr.emp,
    bcr.emp_military,
    bcr.bldg_area_detsf_sl,
    bcr.bldg_area_detsf_ll,
    bcr.bldg_area_attsf,
    bcr.bldg_area_mf,
    bcr.bldg_area_retail_services,
    bcr.bldg_area_restaurant,
    bcr.bldg_area_accommodation,
    bcr.bldg_area_arts_entertainment,
    bcr.bldg_area_other_services,
    bcr.bldg_area_office_services,
    bcr.bldg_area_public_admin,
    bcr.bldg_area_education,
    bcr.bldg_area_medical_services,
    bcr.bldg_area_transport_warehousing,
    bcr.bldg_area_wholesale,
    bcr.residential_irrigated_area,
    bcr.commercial_irrigated_area,
    bcr.median_income,
    bcr.rent_burden_pct,
    bcr.pct_minority,
    bcr.pct_college_educated,
    bcr.cost_burden_pct,
    NULL::double precision AS area_parcel_res_detsf,
    NULL::double precision AS area_parcel_res_detsf_sl,
    NULL::double precision AS area_parcel_res_detsf_ll,
    NULL::double precision AS area_parcel_res_attsf,
    NULL::double precision AS area_parcel_res_mf,
    NULL::double precision AS area_parcel_emp_ret,
    NULL::double precision AS area_parcel_emp_off,
    NULL::double precision AS area_parcel_emp_pub,
    NULL::double precision AS area_parcel_emp_ind,
    NULL::double precision AS area_parcel_emp_military,
    sp.geography_id
FROM brewgis.sacog.base_canvas_reconciled bcr
LEFT JOIN public.sacog_comparison_parcels sp
    ON bcr.parcel_id = sp.parcel_id;

-- post_statements
  CREATE INDEX IF NOT EXISTS @snapshot_hash('idx_sacog_comparison_geom_')
  ON @this_model USING GIST (geometry);
  CREATE INDEX IF NOT EXISTS @snapshot_hash('idx_comparison_view_parcel_id_')
  ON @this_model USING btree (parcel_id);
  CREATE INDEX IF NOT EXISTS @snapshot_hash('idx_comparison_view_geography_id_')
  ON @this_model USING btree (geography_id);
  ANALYZE @this_model;
