MODEL (
  name brewgis.sacog.correlations,
  kind FULL,
  description 'Area-weighted Pearson correlation R per base-canvas metric, brewgis against the SACOG v1 reference.',
  column_descriptions (
    area_gross = 'Area-weighted Pearson R: Gross Area (unitless).',
    area_parcel = 'Area-weighted Pearson R: Parcel Area (unitless).',
    area_parcel_res_detsf = 'Area-weighted Pearson R: Residential Detached SF Parcel Area (unitless).',
    area_parcel_res_detsf_sl = 'Area-weighted Pearson R: Residential Detached SF Small Lot Parcel Area (unitless).',
    area_parcel_res_detsf_ll = 'Area-weighted Pearson R: Residential Detached SF Large Lot Parcel Area (unitless).',
    area_parcel_res_attsf = 'Area-weighted Pearson R: Residential Attached SF Parcel Area (unitless).',
    area_parcel_res_mf = 'Area-weighted Pearson R: Residential Multi-Family Parcel Area (unitless).',
    area_parcel_res = 'Area-weighted Pearson R: Total Residential Parcel Area (unitless).',
    area_parcel_emp = 'Area-weighted Pearson R: Total Employment Parcel Area (unitless).',
    area_parcel_emp_ret = 'Area-weighted Pearson R: Retail Employment Parcel Area (unitless).',
    area_parcel_emp_off = 'Area-weighted Pearson R: Office Employment Parcel Area (unitless).',
    area_parcel_emp_pub = 'Area-weighted Pearson R: Public Employment Parcel Area (unitless).',
    area_parcel_emp_ind = 'Area-weighted Pearson R: Industrial Employment Parcel Area (unitless).',
    area_parcel_emp_ag = 'Area-weighted Pearson R: Agricultural Employment Parcel Area (unitless).',
    area_parcel_emp_military = 'Area-weighted Pearson R: Military Parcel Area (unitless).',
    area_parcel_mixed_use = 'Area-weighted Pearson R: Mixed Use Parcel Area (unitless).',
    area_parcel_no_use = 'Area-weighted Pearson R: No Use Parcel Area (unitless).',
    intersection_density = 'Area-weighted Pearson R: Intersection Density (unitless).',
    pop = 'Area-weighted Pearson R: Population (unitless).',
    hh = 'Area-weighted Pearson R: Households (unitless).',
    du = 'Area-weighted Pearson R: Dwelling Units (unitless).',
    du_detsf = 'Area-weighted Pearson R: Detached SF Dwelling Units (unitless).',
    du_detsf_sl = 'Area-weighted Pearson R: Detached SF Small Lot Dwelling Units (unitless).',
    du_detsf_ll = 'Area-weighted Pearson R: Detached SF Large Lot Dwelling Units (unitless).',
    du_attsf = 'Area-weighted Pearson R: Attached SF Dwelling Units (unitless).',
    du_mf = 'Area-weighted Pearson R: Multi-Family Dwelling Units (unitless).',
    du_mf2to4 = 'Area-weighted Pearson R: Multi-Family 2-4 Unit Dwelling Units (unitless).',
    du_mf5p = 'Area-weighted Pearson R: Multi-Family 5+ Unit Dwelling Units (unitless).',
    emp = 'Area-weighted Pearson R: Total Employment (unitless).',
    emp_ret = 'Area-weighted Pearson R: Retail Employment (unitless).',
    emp_retail_services = 'Area-weighted Pearson R: Retail Services Employment (unitless).',
    emp_restaurant = 'Area-weighted Pearson R: Restaurant Employment (unitless).',
    emp_accommodation = 'Area-weighted Pearson R: Accommodation Employment (unitless).',
    emp_arts_entertainment = 'Area-weighted Pearson R: Arts & Entertainment Employment (unitless).',
    emp_other_services = 'Area-weighted Pearson R: Other Services Employment (unitless).',
    emp_off = 'Area-weighted Pearson R: Office Employment (unitless).',
    emp_office_services = 'Area-weighted Pearson R: Office Services Employment (unitless).',
    emp_medical_services = 'Area-weighted Pearson R: Medical Services Employment (unitless).',
    emp_pub = 'Area-weighted Pearson R: Public Employment (unitless).',
    emp_public_admin = 'Area-weighted Pearson R: Public Administration Employment (unitless).',
    emp_education = 'Area-weighted Pearson R: Education Employment (unitless).',
    emp_ind = 'Area-weighted Pearson R: Industrial Employment (unitless).',
    emp_manufacturing = 'Area-weighted Pearson R: Manufacturing Employment (unitless).',
    emp_wholesale = 'Area-weighted Pearson R: Wholesale Employment (unitless).',
    emp_transport_warehousing = 'Area-weighted Pearson R: Transport & Warehousing Employment (unitless).',
    emp_utilities = 'Area-weighted Pearson R: Utilities Employment (unitless).',
    emp_construction = 'Area-weighted Pearson R: Construction Employment (unitless).',
    emp_ag = 'Area-weighted Pearson R: Agricultural Employment (unitless).',
    emp_agriculture = 'Area-weighted Pearson R: Agriculture Employment (Detailed) (unitless).',
    emp_extraction = 'Area-weighted Pearson R: Extraction Employment (unitless).',
    emp_military = 'Area-weighted Pearson R: Military Employment (unitless).',
    bldg_area_detsf_sl = 'Area-weighted Pearson R: Detached SF Small Lot Building Area (unitless).',
    bldg_area_detsf_ll = 'Area-weighted Pearson R: Detached SF Large Lot Building Area (unitless).',
    bldg_area_attsf = 'Area-weighted Pearson R: Attached SF Building Area (unitless).',
    bldg_area_mf = 'Area-weighted Pearson R: Multi-Family Building Area (unitless).',
    bldg_area_retail_services = 'Area-weighted Pearson R: Retail Services Building Area (unitless).',
    bldg_area_restaurant = 'Area-weighted Pearson R: Restaurant Building Area (unitless).',
    bldg_area_accommodation = 'Area-weighted Pearson R: Accommodation Building Area (unitless).',
    bldg_area_arts_entertainment = 'Area-weighted Pearson R: Arts & Entertainment Building Area (unitless).',
    bldg_area_other_services = 'Area-weighted Pearson R: Other Services Building Area (unitless).',
    bldg_area_office_services = 'Area-weighted Pearson R: Office Services Building Area (unitless).',
    bldg_area_public_admin = 'Area-weighted Pearson R: Public Administration Building Area (unitless).',
    bldg_area_education = 'Area-weighted Pearson R: Education Building Area (unitless).',
    bldg_area_medical_services = 'Area-weighted Pearson R: Medical Services Building Area (unitless).',
    bldg_area_transport_warehousing = 'Area-weighted Pearson R: Transport & Warehousing Building Area (unitless).',
    bldg_area_wholesale = 'Area-weighted Pearson R: Wholesale Building Area (unitless).',
    residential_irrigated_area = 'Area-weighted Pearson R: Residential Irrigated Area (unitless).',
    commercial_irrigated_area = 'Area-weighted Pearson R: Commercial Irrigated Area (unitless).'
  )
);

-- pre_statements
  CREATE INDEX IF NOT EXISTS idx_ref_geography_id
  ON public.sac_cnty_region_base_canvas (geography_id);
  ANALYZE public.sac_cnty_region_base_canvas;

-- SACOG Correlations — per-column area-weighted Pearson R between brewgis and reference.
--
-- Architecture: no custom Python macros. Uses SQLMesh built-in @EACH with
-- inline tuples and template substitution (@m, ref_@m, xy_@m) over metric names.
--
-- The `raw` CTE aliases all ref columns as `ref_<metric>` and precomputes
-- `xy_<metric>` = brew * ref products. This lets @EACH use @m for brew,
-- ref_@m for ref, and xy_@m for cross-products.

WITH raw AS (
    SELECT
        COALESCE(NULLIF(area_gross, 0), NULLIF(acres_gross * 4046.86, 0), 1.0) AS w,
        -- Brew columns — no aliasing needed, names match metric names
        area_gross,
        area_parcel_acres AS area_parcel,
        area_parcel_res_detsf,
        area_parcel_res_detsf_sl,
        area_parcel_res_detsf_ll,
        area_parcel_res_attsf,
        area_parcel_res_mf,
        area_parcel_res_acres AS area_parcel_res,
        area_parcel_emp_acres AS area_parcel_emp,
        area_parcel_emp_ret,
        area_parcel_emp_off,
        area_parcel_emp_pub,
        area_parcel_emp_ind,
        area_parcel_emp_ag,
        area_parcel_emp_military,
        area_parcel_mixed_use_acres AS area_parcel_mixed_use,
        area_parcel_no_use_acres AS area_parcel_no_use,
        intersection_density,
        bc.pop,
        bc.hh,
        bc.du,
        bc.du_detsf,
        bc.du_detsf_sl,
        bc.du_detsf_ll,
        bc.du_attsf,
        bc.du_mf,
        bc.du_mf2to4,
        bc.du_mf5p,
        bc.emp,
        bc.emp_ret,
        bc.emp_retail_services,
        bc.emp_restaurant,
        bc.emp_accommodation,
        bc.emp_arts_entertainment,
        bc.emp_other_services,
        bc.emp_off,
        bc.emp_office_services,
        bc.emp_medical_services,
        bc.emp_pub,
        bc.emp_public_admin,
        bc.emp_education,
        bc.emp_ind,
        bc.emp_manufacturing,
        bc.emp_wholesale,
        bc.emp_transport_warehousing,
        bc.emp_utilities,
        bc.emp_construction,
        bc.emp_ag,
        bc.emp_agriculture,
        bc.emp_extraction,
        bc.emp_military,
        bldg_area_detsf_sl,
        bldg_area_detsf_ll,
        bldg_area_attsf,
        bldg_area_mf,
        bldg_area_retail_services,
        bldg_area_restaurant,
        bldg_area_accommodation,
        bldg_area_arts_entertainment,
        bldg_area_other_services,
        bldg_area_office_services,
        bldg_area_public_admin,
        bldg_area_education,
        bldg_area_medical_services,
        bldg_area_transport_warehousing,
        bldg_area_wholesale,
        residential_irrigated_area,
        commercial_irrigated_area,
        -- Ref columns — aliased as ref_<metric> for @EACH template substitution (ref_@m)
        ref.acres_gross AS ref_area_gross,
        ref.acres_parcel AS ref_area_parcel,
        ref.acres_parcel_res_detsf AS ref_area_parcel_res_detsf,
        ref.acres_parcel_res_detsf_sl AS ref_area_parcel_res_detsf_sl,
        ref.acres_parcel_res_detsf_ll AS ref_area_parcel_res_detsf_ll,
        ref.acres_parcel_res_attsf AS ref_area_parcel_res_attsf,
        ref.acres_parcel_res_mf AS ref_area_parcel_res_mf,
        ref.acres_parcel_res AS ref_area_parcel_res,
        ref.acres_parcel_emp AS ref_area_parcel_emp,
        ref.acres_parcel_emp_ret AS ref_area_parcel_emp_ret,
        ref.acres_parcel_emp_off AS ref_area_parcel_emp_off,
        ref.acres_parcel_emp_pub AS ref_area_parcel_emp_pub,
        ref.acres_parcel_emp_ind AS ref_area_parcel_emp_ind,
        ref.acres_parcel_emp_ag AS ref_area_parcel_emp_ag,
        ref.acres_parcel_emp_military AS ref_area_parcel_emp_military,
        ref.acres_parcel_mixed_use AS ref_area_parcel_mixed_use,
        ref.acres_parcel_no_use AS ref_area_parcel_no_use,
        ref.intersection_density_sqmi AS ref_intersection_density,
        ref.pop AS ref_pop,
        ref.hh AS ref_hh,
        ref.du AS ref_du,
        ref.du_detsf AS ref_du_detsf,
        ref.du_detsf_sl AS ref_du_detsf_sl,
        ref.du_detsf_ll AS ref_du_detsf_ll,
        ref.du_attsf AS ref_du_attsf,
        ref.du_mf AS ref_du_mf,
        ref.du_mf2to4 AS ref_du_mf2to4,
        ref.du_mf5p AS ref_du_mf5p,
        ref.emp AS ref_emp,
        ref.emp_ret AS ref_emp_ret,
        ref.emp_retail_services AS ref_emp_retail_services,
        ref.emp_restaurant AS ref_emp_restaurant,
        ref.emp_accommodation AS ref_emp_accommodation,
        ref.emp_arts_entertainment AS ref_emp_arts_entertainment,
        ref.emp_other_services AS ref_emp_other_services,
        ref.emp_off AS ref_emp_off,
        ref.emp_office_services AS ref_emp_office_services,
        ref.emp_medical_services AS ref_emp_medical_services,
        ref.emp_pub AS ref_emp_pub,
        ref.emp_public_admin AS ref_emp_public_admin,
        ref.emp_education AS ref_emp_education,
        ref.emp_ind AS ref_emp_ind,
        ref.emp_manufacturing AS ref_emp_manufacturing,
        ref.emp_wholesale AS ref_emp_wholesale,
        ref.emp_transport_warehousing AS ref_emp_transport_warehousing,
        ref.emp_utilities AS ref_emp_utilities,
        ref.emp_construction AS ref_emp_construction,
        ref.emp_ag AS ref_emp_ag,
        ref.emp_agriculture AS ref_emp_agriculture,
        ref.emp_extraction AS ref_emp_extraction,
        ref.emp_military AS ref_emp_military,
        ref.bldg_sqft_detsf_sl AS ref_bldg_area_detsf_sl,
        ref.bldg_sqft_detsf_ll AS ref_bldg_area_detsf_ll,
        ref.bldg_sqft_attsf AS ref_bldg_area_attsf,
        ref.bldg_sqft_mf AS ref_bldg_area_mf,
        ref.bldg_sqft_retail_services AS ref_bldg_area_retail_services,
        ref.bldg_sqft_restaurant AS ref_bldg_area_restaurant,
        ref.bldg_sqft_accommodation AS ref_bldg_area_accommodation,
        ref.bldg_sqft_arts_entertainment AS ref_bldg_area_arts_entertainment,
        ref.bldg_sqft_other_services AS ref_bldg_area_other_services,
        ref.bldg_sqft_office_services AS ref_bldg_area_office_services,
        ref.bldg_sqft_public_admin AS ref_bldg_area_public_admin,
        ref.bldg_sqft_education AS ref_bldg_area_education,
        ref.bldg_sqft_medical_services AS ref_bldg_area_medical_services,
        ref.bldg_sqft_transport_warehousing AS ref_bldg_area_transport_warehousing,
        ref.bldg_sqft_wholesale AS ref_bldg_area_wholesale,
        ref.residential_irrigated_sqft AS ref_residential_irrigated_area,
        ref.commercial_irrigated_sqft AS ref_commercial_irrigated_area,
        -- xy product columns (brew * ref) for swxy computation
        area_gross * ref.acres_gross AS xy_area_gross,
        area_parcel_acres * ref.acres_parcel AS xy_area_parcel,
        area_parcel_res_detsf * ref.acres_parcel_res_detsf AS xy_area_parcel_res_detsf,
        area_parcel_res_detsf_sl * ref.acres_parcel_res_detsf_sl AS xy_area_parcel_res_detsf_sl,
        area_parcel_res_detsf_ll * ref.acres_parcel_res_detsf_ll AS xy_area_parcel_res_detsf_ll,
        area_parcel_res_attsf * ref.acres_parcel_res_attsf AS xy_area_parcel_res_attsf,
        area_parcel_res_mf * ref.acres_parcel_res_mf AS xy_area_parcel_res_mf,
        area_parcel_res_acres * ref.acres_parcel_res AS xy_area_parcel_res,
        area_parcel_emp_acres * ref.acres_parcel_emp AS xy_area_parcel_emp,
        area_parcel_emp_ret * ref.acres_parcel_emp_ret AS xy_area_parcel_emp_ret,
        area_parcel_emp_off * ref.acres_parcel_emp_off AS xy_area_parcel_emp_off,
        area_parcel_emp_pub * ref.acres_parcel_emp_pub AS xy_area_parcel_emp_pub,
        area_parcel_emp_ind * ref.acres_parcel_emp_ind AS xy_area_parcel_emp_ind,
        area_parcel_emp_ag * ref.acres_parcel_emp_ag AS xy_area_parcel_emp_ag,
        area_parcel_emp_military * ref.acres_parcel_emp_military AS xy_area_parcel_emp_military,
        area_parcel_mixed_use_acres * ref.acres_parcel_mixed_use AS xy_area_parcel_mixed_use,
        area_parcel_no_use_acres * ref.acres_parcel_no_use AS xy_area_parcel_no_use,
        intersection_density * ref.intersection_density_sqmi AS xy_intersection_density,
        bc.pop * ref.pop AS xy_pop,
        bc.hh * ref.hh AS xy_hh,
        bc.du * ref.du AS xy_du,
        bc.du_detsf * ref.du_detsf AS xy_du_detsf,
        bc.du_detsf_sl * ref.du_detsf_sl AS xy_du_detsf_sl,
        bc.du_detsf_ll * ref.du_detsf_ll AS xy_du_detsf_ll,
        bc.du_attsf * ref.du_attsf AS xy_du_attsf,
        bc.du_mf * ref.du_mf AS xy_du_mf,
        bc.du_mf2to4 * ref.du_mf2to4 AS xy_du_mf2to4,
        bc.du_mf5p * ref.du_mf5p AS xy_du_mf5p,
        bc.emp * ref.emp AS xy_emp,
        bc.emp_ret * ref.emp_ret AS xy_emp_ret,
        bc.emp_retail_services * ref.emp_retail_services AS xy_emp_retail_services,
        bc.emp_restaurant * ref.emp_restaurant AS xy_emp_restaurant,
        bc.emp_accommodation * ref.emp_accommodation AS xy_emp_accommodation,
        bc.emp_arts_entertainment * ref.emp_arts_entertainment AS xy_emp_arts_entertainment,
        bc.emp_other_services * ref.emp_other_services AS xy_emp_other_services,
        bc.emp_off * ref.emp_off AS xy_emp_off,
        bc.emp_office_services * ref.emp_office_services AS xy_emp_office_services,
        bc.emp_medical_services * ref.emp_medical_services AS xy_emp_medical_services,
        bc.emp_pub * ref.emp_pub AS xy_emp_pub,
        bc.emp_public_admin * ref.emp_public_admin AS xy_emp_public_admin,
        bc.emp_education * ref.emp_education AS xy_emp_education,
        bc.emp_ind * ref.emp_ind AS xy_emp_ind,
        bc.emp_manufacturing * ref.emp_manufacturing AS xy_emp_manufacturing,
        bc.emp_wholesale * ref.emp_wholesale AS xy_emp_wholesale,
        bc.emp_transport_warehousing * ref.emp_transport_warehousing AS xy_emp_transport_warehousing,
        bc.emp_utilities * ref.emp_utilities AS xy_emp_utilities,
        bc.emp_construction * ref.emp_construction AS xy_emp_construction,
        bc.emp_ag * ref.emp_ag AS xy_emp_ag,
        bc.emp_agriculture * ref.emp_agriculture AS xy_emp_agriculture,
        bc.emp_extraction * ref.emp_extraction AS xy_emp_extraction,
        bc.emp_military * ref.emp_military AS xy_emp_military,
        bldg_area_detsf_sl * ref.bldg_sqft_detsf_sl AS xy_bldg_area_detsf_sl,
        bldg_area_detsf_ll * ref.bldg_sqft_detsf_ll AS xy_bldg_area_detsf_ll,
        bldg_area_attsf * ref.bldg_sqft_attsf AS xy_bldg_area_attsf,
        bldg_area_mf * ref.bldg_sqft_mf AS xy_bldg_area_mf,
        bldg_area_retail_services * ref.bldg_sqft_retail_services AS xy_bldg_area_retail_services,
        bldg_area_restaurant * ref.bldg_sqft_restaurant AS xy_bldg_area_restaurant,
        bldg_area_accommodation * ref.bldg_sqft_accommodation AS xy_bldg_area_accommodation,
        bldg_area_arts_entertainment * ref.bldg_sqft_arts_entertainment AS xy_bldg_area_arts_entertainment,
        bldg_area_other_services * ref.bldg_sqft_other_services AS xy_bldg_area_other_services,
        bldg_area_office_services * ref.bldg_sqft_office_services AS xy_bldg_area_office_services,
        bldg_area_public_admin * ref.bldg_sqft_public_admin AS xy_bldg_area_public_admin,
        bldg_area_education * ref.bldg_sqft_education AS xy_bldg_area_education,
        bldg_area_medical_services * ref.bldg_sqft_medical_services AS xy_bldg_area_medical_services,
        bldg_area_transport_warehousing * ref.bldg_sqft_transport_warehousing AS xy_bldg_area_transport_warehousing,
        bldg_area_wholesale * ref.bldg_sqft_wholesale AS xy_bldg_area_wholesale,
        residential_irrigated_area * ref.residential_irrigated_sqft AS xy_residential_irrigated_area,
        commercial_irrigated_area * ref.commercial_irrigated_sqft AS xy_commercial_irrigated_area
    FROM brewgis.sacog.comparison bc
    INNER JOIN public.sac_cnty_region_base_canvas ref ON bc.geography_id = ref.geography_id
    WHERE bc.geography_id IS NOT NULL
),

stats AS (
    SELECT
        SUM(w) AS sw,
        @EACH((area_gross, area_parcel, area_parcel_res_detsf, area_parcel_res_detsf_sl, area_parcel_res_detsf_ll, area_parcel_res_attsf, area_parcel_res_mf, area_parcel_res, area_parcel_emp, area_parcel_emp_ret, area_parcel_emp_off, area_parcel_emp_pub, area_parcel_emp_ind, area_parcel_emp_ag, area_parcel_emp_military, area_parcel_mixed_use, area_parcel_no_use, intersection_density, pop, hh, du, du_detsf, du_detsf_sl, du_detsf_ll, du_attsf, du_mf, du_mf2to4, du_mf5p, emp, emp_ret, emp_retail_services, emp_restaurant, emp_accommodation, emp_arts_entertainment, emp_other_services, emp_off, emp_office_services, emp_medical_services, emp_pub, emp_public_admin, emp_education, emp_ind, emp_manufacturing, emp_wholesale, emp_transport_warehousing, emp_utilities, emp_construction, emp_ag, emp_agriculture, emp_extraction, emp_military, bldg_area_detsf_sl, bldg_area_detsf_ll, bldg_area_attsf, bldg_area_mf, bldg_area_retail_services, bldg_area_restaurant, bldg_area_accommodation, bldg_area_arts_entertainment, bldg_area_other_services, bldg_area_office_services, bldg_area_public_admin, bldg_area_education, bldg_area_medical_services, bldg_area_transport_warehousing, bldg_area_wholesale, residential_irrigated_area, commercial_irrigated_area), m -> SUM(w * @m) AS swx_@m),
        @EACH((area_gross, area_parcel, area_parcel_res_detsf, area_parcel_res_detsf_sl, area_parcel_res_detsf_ll, area_parcel_res_attsf, area_parcel_res_mf, area_parcel_res, area_parcel_emp, area_parcel_emp_ret, area_parcel_emp_off, area_parcel_emp_pub, area_parcel_emp_ind, area_parcel_emp_ag, area_parcel_emp_military, area_parcel_mixed_use, area_parcel_no_use, intersection_density, pop, hh, du, du_detsf, du_detsf_sl, du_detsf_ll, du_attsf, du_mf, du_mf2to4, du_mf5p, emp, emp_ret, emp_retail_services, emp_restaurant, emp_accommodation, emp_arts_entertainment, emp_other_services, emp_off, emp_office_services, emp_medical_services, emp_pub, emp_public_admin, emp_education, emp_ind, emp_manufacturing, emp_wholesale, emp_transport_warehousing, emp_utilities, emp_construction, emp_ag, emp_agriculture, emp_extraction, emp_military, bldg_area_detsf_sl, bldg_area_detsf_ll, bldg_area_attsf, bldg_area_mf, bldg_area_retail_services, bldg_area_restaurant, bldg_area_accommodation, bldg_area_arts_entertainment, bldg_area_other_services, bldg_area_office_services, bldg_area_public_admin, bldg_area_education, bldg_area_medical_services, bldg_area_transport_warehousing, bldg_area_wholesale, residential_irrigated_area, commercial_irrigated_area), m -> SUM(w * @m * @m) AS swxx_@m),
        @EACH((area_gross, area_parcel, area_parcel_res_detsf, area_parcel_res_detsf_sl, area_parcel_res_detsf_ll, area_parcel_res_attsf, area_parcel_res_mf, area_parcel_res, area_parcel_emp, area_parcel_emp_ret, area_parcel_emp_off, area_parcel_emp_pub, area_parcel_emp_ind, area_parcel_emp_ag, area_parcel_emp_military, area_parcel_mixed_use, area_parcel_no_use, intersection_density, pop, hh, du, du_detsf, du_detsf_sl, du_detsf_ll, du_attsf, du_mf, du_mf2to4, du_mf5p, emp, emp_ret, emp_retail_services, emp_restaurant, emp_accommodation, emp_arts_entertainment, emp_other_services, emp_off, emp_office_services, emp_medical_services, emp_pub, emp_public_admin, emp_education, emp_ind, emp_manufacturing, emp_wholesale, emp_transport_warehousing, emp_utilities, emp_construction, emp_ag, emp_agriculture, emp_extraction, emp_military, bldg_area_detsf_sl, bldg_area_detsf_ll, bldg_area_attsf, bldg_area_mf, bldg_area_retail_services, bldg_area_restaurant, bldg_area_accommodation, bldg_area_arts_entertainment, bldg_area_other_services, bldg_area_office_services, bldg_area_public_admin, bldg_area_education, bldg_area_medical_services, bldg_area_transport_warehousing, bldg_area_wholesale, residential_irrigated_area, commercial_irrigated_area), m -> SUM(w * ref_@m) AS swy_@m),
        @EACH((area_gross, area_parcel, area_parcel_res_detsf, area_parcel_res_detsf_sl, area_parcel_res_detsf_ll, area_parcel_res_attsf, area_parcel_res_mf, area_parcel_res, area_parcel_emp, area_parcel_emp_ret, area_parcel_emp_off, area_parcel_emp_pub, area_parcel_emp_ind, area_parcel_emp_ag, area_parcel_emp_military, area_parcel_mixed_use, area_parcel_no_use, intersection_density, pop, hh, du, du_detsf, du_detsf_sl, du_detsf_ll, du_attsf, du_mf, du_mf2to4, du_mf5p, emp, emp_ret, emp_retail_services, emp_restaurant, emp_accommodation, emp_arts_entertainment, emp_other_services, emp_off, emp_office_services, emp_medical_services, emp_pub, emp_public_admin, emp_education, emp_ind, emp_manufacturing, emp_wholesale, emp_transport_warehousing, emp_utilities, emp_construction, emp_ag, emp_agriculture, emp_extraction, emp_military, bldg_area_detsf_sl, bldg_area_detsf_ll, bldg_area_attsf, bldg_area_mf, bldg_area_retail_services, bldg_area_restaurant, bldg_area_accommodation, bldg_area_arts_entertainment, bldg_area_other_services, bldg_area_office_services, bldg_area_public_admin, bldg_area_education, bldg_area_medical_services, bldg_area_transport_warehousing, bldg_area_wholesale, residential_irrigated_area, commercial_irrigated_area), m -> SUM(w * ref_@m * ref_@m) AS swyy_@m),
        @EACH((area_gross, area_parcel, area_parcel_res_detsf, area_parcel_res_detsf_sl, area_parcel_res_detsf_ll, area_parcel_res_attsf, area_parcel_res_mf, area_parcel_res, area_parcel_emp, area_parcel_emp_ret, area_parcel_emp_off, area_parcel_emp_pub, area_parcel_emp_ind, area_parcel_emp_ag, area_parcel_emp_military, area_parcel_mixed_use, area_parcel_no_use, intersection_density, pop, hh, du, du_detsf, du_detsf_sl, du_detsf_ll, du_attsf, du_mf, du_mf2to4, du_mf5p, emp, emp_ret, emp_retail_services, emp_restaurant, emp_accommodation, emp_arts_entertainment, emp_other_services, emp_off, emp_office_services, emp_medical_services, emp_pub, emp_public_admin, emp_education, emp_ind, emp_manufacturing, emp_wholesale, emp_transport_warehousing, emp_utilities, emp_construction, emp_ag, emp_agriculture, emp_extraction, emp_military, bldg_area_detsf_sl, bldg_area_detsf_ll, bldg_area_attsf, bldg_area_mf, bldg_area_retail_services, bldg_area_restaurant, bldg_area_accommodation, bldg_area_arts_entertainment, bldg_area_other_services, bldg_area_office_services, bldg_area_public_admin, bldg_area_education, bldg_area_medical_services, bldg_area_transport_warehousing, bldg_area_wholesale, residential_irrigated_area, commercial_irrigated_area), m -> SUM(w * xy_@m) AS swxy_@m)
    FROM raw
)

SELECT
    @EACH((area_gross, area_parcel, area_parcel_res_detsf, area_parcel_res_detsf_sl, area_parcel_res_detsf_ll, area_parcel_res_attsf, area_parcel_res_mf, area_parcel_res, area_parcel_emp, area_parcel_emp_ret, area_parcel_emp_off, area_parcel_emp_pub, area_parcel_emp_ind, area_parcel_emp_ag, area_parcel_emp_military, area_parcel_mixed_use, area_parcel_no_use, intersection_density, pop, hh, du, du_detsf, du_detsf_sl, du_detsf_ll, du_attsf, du_mf, du_mf2to4, du_mf5p, emp, emp_ret, emp_retail_services, emp_restaurant, emp_accommodation, emp_arts_entertainment, emp_other_services, emp_off, emp_office_services, emp_medical_services, emp_pub, emp_public_admin, emp_education, emp_ind, emp_manufacturing, emp_wholesale, emp_transport_warehousing, emp_utilities, emp_construction, emp_ag, emp_agriculture, emp_extraction, emp_military, bldg_area_detsf_sl, bldg_area_detsf_ll, bldg_area_attsf, bldg_area_mf, bldg_area_retail_services, bldg_area_restaurant, bldg_area_accommodation, bldg_area_arts_entertainment, bldg_area_other_services, bldg_area_office_services, bldg_area_public_admin, bldg_area_education, bldg_area_medical_services, bldg_area_transport_warehousing, bldg_area_wholesale, residential_irrigated_area, commercial_irrigated_area), m -> (sw * swxy_@m - swx_@m * swy_@m) / NULLIF(SQRT((sw * swxx_@m - swx_@m * swx_@m) * (sw * swyy_@m - swy_@m * swy_@m)), 0) AS @m)
FROM stats
