MODEL (
  name brewgis.sacog.reference_totals,
  kind FULL,
  description 'SACOG v1 reference totals: every numeric metric of sac_cnty_region_base_canvas summed over all rows.',
  column_descriptions (
    source = 'Source label for the row (literal reference).',
    acres_gross = 'Total Gross Area in the reference (acres).',
    acres_parcel = 'Total Parcel Area in the reference (acres).',
    acres_parcel_res = 'Total Total Residential Parcel Area in the reference (acres).',
    acres_parcel_emp = 'Total Total Employment Parcel Area in the reference (acres).',
    acres_parcel_mixed_use = 'Total Mixed Use Parcel Area in the reference (acres).',
    acres_parcel_no_use = 'Total No Use Parcel Area in the reference (acres).',
    pop = 'Total Population in the reference (count).',
    hh = 'Total Households in the reference (count).',
    du = 'Total Dwelling Units in the reference (count).',
    du_detsf = 'Total Detached SF Dwelling Units in the reference (count).',
    du_detsf_sl = 'Total Detached SF Small Lot Dwelling Units in the reference (count).',
    du_detsf_ll = 'Total Detached SF Large Lot Dwelling Units in the reference (count).',
    du_attsf = 'Total Attached SF Dwelling Units in the reference (count).',
    du_mf = 'Total Multi-Family Dwelling Units in the reference (count).',
    du_mf2to4 = 'Total Multi-Family 2-4 Unit Dwelling Units in the reference (count).',
    du_mf5p = 'Total Multi-Family 5+ Unit Dwelling Units in the reference (count).',
    emp = 'Total Total Employment in the reference (count).',
    emp_ret = 'Total Retail Employment in the reference (count).',
    emp_off = 'Total Office Employment in the reference (count).',
    emp_pub = 'Total Public Employment in the reference (count).',
    emp_ind = 'Total Industrial Employment in the reference (count).',
    emp_ag = 'Total Agricultural Employment in the reference (count).',
    emp_military = 'Total Military Employment in the reference (count).',
    emp_retail_services = 'Total Retail Services Employment in the reference (count).',
    emp_restaurant = 'Total Restaurant Employment in the reference (count).',
    emp_accommodation = 'Total Accommodation Employment in the reference (count).',
    emp_arts_entertainment = 'Total Arts & Entertainment Employment in the reference (count).',
    emp_other_services = 'Total Other Services Employment in the reference (count).',
    emp_office_services = 'Total Office Services Employment in the reference (count).',
    emp_medical_services = 'Total Medical Services Employment in the reference (count).',
    emp_public_admin = 'Total Public Administration Employment in the reference (count).',
    emp_education = 'Total Education Employment in the reference (count).',
    emp_manufacturing = 'Total Manufacturing Employment in the reference (count).',
    emp_wholesale = 'Total Wholesale Employment in the reference (count).',
    emp_transport_warehousing = 'Total Transport & Warehousing Employment in the reference (count).',
    emp_utilities = 'Total Utilities Employment in the reference (count).',
    emp_construction = 'Total Construction Employment in the reference (count).',
    emp_agriculture = 'Total Agriculture Employment (Detailed) in the reference (count).',
    emp_extraction = 'Total Extraction Employment in the reference (count).',
    bldg_sqft_detsf_sl = 'Total Detached SF Small Lot Building Area in the reference (sq ft).',
    bldg_sqft_detsf_ll = 'Total Detached SF Large Lot Building Area in the reference (sq ft).',
    bldg_sqft_attsf = 'Total Attached SF Building Area in the reference (sq ft).',
    bldg_sqft_mf = 'Total Multi-Family Building Area in the reference (sq ft).',
    bldg_sqft_retail_services = 'Total Retail Services Building Area in the reference (sq ft).',
    bldg_sqft_restaurant = 'Total Restaurant Building Area in the reference (sq ft).',
    bldg_sqft_accommodation = 'Total Accommodation Building Area in the reference (sq ft).',
    bldg_sqft_arts_entertainment = 'Total Arts & Entertainment Building Area in the reference (sq ft).',
    bldg_sqft_other_services = 'Total Other Services Building Area in the reference (sq ft).',
    bldg_sqft_office_services = 'Total Office Services Building Area in the reference (sq ft).',
    bldg_sqft_public_admin = 'Total Public Administration Building Area in the reference (sq ft).',
    bldg_sqft_education = 'Total Education Building Area in the reference (sq ft).',
    bldg_sqft_medical_services = 'Total Medical Services Building Area in the reference (sq ft).',
    bldg_sqft_transport_warehousing = 'Total Transport & Warehousing Building Area in the reference (sq ft).',
    bldg_sqft_wholesale = 'Total Wholesale Building Area in the reference (sq ft).',
    residential_irrigated_sqft = 'Total Residential Irrigated Area in the reference (sq ft).',
    commercial_irrigated_sqft = 'Total Commercial Irrigated Area in the reference (sq ft).',
    intersection_density_sqmi = 'Total Intersection Density in the reference (intersections per square mile).'
  )
);

-- SACOG Reference Totals — aggregate sums from the v1 reference base canvas.
--
-- Reads from sac_cnty_region_base_canvas (the SACOG v1 reference table).

WITH totals AS (
    SELECT
        COALESCE(SUM(acres_gross), 0)::double precision AS acres_gross,
        COALESCE(SUM(acres_parcel), 0)::double precision AS acres_parcel,
        COALESCE(SUM(acres_parcel_res), 0)::double precision AS acres_parcel_res,
        COALESCE(SUM(acres_parcel_emp), 0)::double precision AS acres_parcel_emp,
        COALESCE(SUM(acres_parcel_mixed_use), 0)::double precision AS acres_parcel_mixed_use,
        COALESCE(SUM(acres_parcel_no_use), 0)::double precision AS acres_parcel_no_use,
        COALESCE(SUM(pop), 0)::double precision AS pop,
        COALESCE(SUM(hh), 0)::double precision AS hh,
        COALESCE(SUM(du), 0)::double precision AS du,
        COALESCE(SUM(du_detsf), 0)::double precision AS du_detsf,
        COALESCE(SUM(du_detsf_sl), 0)::double precision AS du_detsf_sl,
        COALESCE(SUM(du_detsf_ll), 0)::double precision AS du_detsf_ll,
        COALESCE(SUM(du_attsf), 0)::double precision AS du_attsf,
        COALESCE(SUM(du_mf), 0)::double precision AS du_mf,
        COALESCE(SUM(du_mf2to4), 0)::double precision AS du_mf2to4,
        COALESCE(SUM(du_mf5p), 0)::double precision AS du_mf5p,
        COALESCE(SUM(emp), 0)::double precision AS emp,
        COALESCE(SUM(emp_ret), 0)::double precision AS emp_ret,
        COALESCE(SUM(emp_off), 0)::double precision AS emp_off,
        COALESCE(SUM(emp_pub), 0)::double precision AS emp_pub,
        COALESCE(SUM(emp_ind), 0)::double precision AS emp_ind,
        COALESCE(SUM(emp_ag), 0)::double precision AS emp_ag,
        COALESCE(SUM(emp_military), 0)::double precision AS emp_military,
        COALESCE(SUM(emp_retail_services), 0)::double precision AS emp_retail_services,
        COALESCE(SUM(emp_restaurant), 0)::double precision AS emp_restaurant,
        COALESCE(SUM(emp_accommodation), 0)::double precision AS emp_accommodation,
        COALESCE(SUM(emp_arts_entertainment), 0)::double precision AS emp_arts_entertainment,
        COALESCE(SUM(emp_other_services), 0)::double precision AS emp_other_services,
        COALESCE(SUM(emp_office_services), 0)::double precision AS emp_office_services,
        COALESCE(SUM(emp_medical_services), 0)::double precision AS emp_medical_services,
        COALESCE(SUM(emp_public_admin), 0)::double precision AS emp_public_admin,
        COALESCE(SUM(emp_education), 0)::double precision AS emp_education,
        COALESCE(SUM(emp_manufacturing), 0)::double precision AS emp_manufacturing,
        COALESCE(SUM(emp_wholesale), 0)::double precision AS emp_wholesale,
        COALESCE(SUM(emp_transport_warehousing), 0)::double precision AS emp_transport_warehousing,
        COALESCE(SUM(emp_utilities), 0)::double precision AS emp_utilities,
        COALESCE(SUM(emp_construction), 0)::double precision AS emp_construction,
        COALESCE(SUM(emp_agriculture), 0)::double precision AS emp_agriculture,
        COALESCE(SUM(emp_extraction), 0)::double precision AS emp_extraction,
        COALESCE(SUM(bldg_sqft_detsf_sl), 0)::double precision AS bldg_sqft_detsf_sl,
        COALESCE(SUM(bldg_sqft_detsf_ll), 0)::double precision AS bldg_sqft_detsf_ll,
        COALESCE(SUM(bldg_sqft_attsf), 0)::double precision AS bldg_sqft_attsf,
        COALESCE(SUM(bldg_sqft_mf), 0)::double precision AS bldg_sqft_mf,
        COALESCE(SUM(bldg_sqft_retail_services), 0)::double precision AS bldg_sqft_retail_services,
        COALESCE(SUM(bldg_sqft_restaurant), 0)::double precision AS bldg_sqft_restaurant,
        COALESCE(SUM(bldg_sqft_accommodation), 0)::double precision AS bldg_sqft_accommodation,
        COALESCE(SUM(bldg_sqft_arts_entertainment), 0)::double precision AS bldg_sqft_arts_entertainment,
        COALESCE(SUM(bldg_sqft_other_services), 0)::double precision AS bldg_sqft_other_services,
        COALESCE(SUM(bldg_sqft_office_services), 0)::double precision AS bldg_sqft_office_services,
        COALESCE(SUM(bldg_sqft_public_admin), 0)::double precision AS bldg_sqft_public_admin,
        COALESCE(SUM(bldg_sqft_education), 0)::double precision AS bldg_sqft_education,
        COALESCE(SUM(bldg_sqft_medical_services), 0)::double precision AS bldg_sqft_medical_services,
        COALESCE(SUM(bldg_sqft_transport_warehousing), 0)::double precision AS bldg_sqft_transport_warehousing,
        COALESCE(SUM(bldg_sqft_wholesale), 0)::double precision AS bldg_sqft_wholesale,
        COALESCE(SUM(residential_irrigated_sqft), 0)::double precision AS residential_irrigated_sqft,
        COALESCE(SUM(commercial_irrigated_sqft), 0)::double precision AS commercial_irrigated_sqft,
        COALESCE(SUM(intersection_density_sqmi), 0)::double precision AS intersection_density_sqmi
    FROM public.sac_cnty_region_base_canvas
)
SELECT
    'reference'::text AS source,
    acres_gross,
    acres_parcel,
    acres_parcel_res,
    acres_parcel_emp,
    acres_parcel_mixed_use,
    acres_parcel_no_use,
    pop,
    hh,
    du,
    du_detsf,
    du_detsf_sl,
    du_detsf_ll,
    du_attsf,
    du_mf,
    du_mf2to4,
    du_mf5p,
    emp,
    emp_ret,
    emp_off,
    emp_pub,
    emp_ind,
    emp_ag,
    emp_military,
    emp_retail_services,
    emp_restaurant,
    emp_accommodation,
    emp_arts_entertainment,
    emp_other_services,
    emp_office_services,
    emp_medical_services,
    emp_public_admin,
    emp_education,
    emp_manufacturing,
    emp_wholesale,
    emp_transport_warehousing,
    emp_utilities,
    emp_construction,
    emp_agriculture,
    emp_extraction,
    bldg_sqft_detsf_sl,
    bldg_sqft_detsf_ll,
    bldg_sqft_attsf,
    bldg_sqft_mf,
    bldg_sqft_retail_services,
    bldg_sqft_restaurant,
    bldg_sqft_accommodation,
    bldg_sqft_arts_entertainment,
    bldg_sqft_other_services,
    bldg_sqft_office_services,
    bldg_sqft_public_admin,
    bldg_sqft_education,
    bldg_sqft_medical_services,
    bldg_sqft_transport_warehousing,
    bldg_sqft_wholesale,
    residential_irrigated_sqft,
    commercial_irrigated_sqft,
    intersection_density_sqmi
FROM totals
