MODEL (
  name brewgis.sacog.totals,
  kind FULL,
  description 'Brewgis base-canvas totals: numeric metrics of base_canvas_reconciled summed into one row.',
  column_descriptions (
    source = 'Source label for the row (literal brewgis).',
    area_gross_acres = 'Total Gross Area across brewgis (acres).',
    area_parcel_acres = 'Total Parcel Area across brewgis (acres).',
    area_parcel_res_acres = 'Total Total Residential Parcel Area across brewgis (acres).',
    area_parcel_emp_acres = 'Total Total Employment Parcel Area across brewgis (acres).',
    area_parcel_mixed_use_acres = 'Total Mixed Use Parcel Area across brewgis (acres).',
    area_parcel_no_use_acres = 'Total No Use Parcel Area across brewgis (acres).',
    pop = 'Total Population across brewgis (count).',
    hh = 'Total Households across brewgis (count).',
    du = 'Total Dwelling Units across brewgis (count).',
    du_detsf = 'Total Detached SF Dwelling Units across brewgis (count).',
    du_detsf_sl = 'Total Detached SF Small Lot Dwelling Units across brewgis (count).',
    du_detsf_ll = 'Total Detached SF Large Lot Dwelling Units across brewgis (count).',
    du_attsf = 'Total Attached SF Dwelling Units across brewgis (count).',
    du_mf = 'Total Multi-Family Dwelling Units across brewgis (count).',
    du_mf2to4 = 'Total Multi-Family 2-4 Unit Dwelling Units across brewgis (count).',
    du_mf5p = 'Total Multi-Family 5+ Unit Dwelling Units across brewgis (count).',
    emp = 'Total Total Employment across brewgis (count).',
    emp_ret = 'Total Retail Employment across brewgis (count).',
    emp_off = 'Total Office Employment across brewgis (count).',
    emp_pub = 'Total Public Employment across brewgis (count).',
    emp_ind = 'Total Industrial Employment across brewgis (count).',
    emp_ag = 'Total Agricultural Employment across brewgis (count).',
    emp_military = 'Total Military Employment across brewgis (count).',
    emp_retail_services = 'Total Retail Services Employment across brewgis (count).',
    emp_restaurant = 'Total Restaurant Employment across brewgis (count).',
    emp_accommodation = 'Total Accommodation Employment across brewgis (count).',
    emp_arts_entertainment = 'Total Arts & Entertainment Employment across brewgis (count).',
    emp_other_services = 'Total Other Services Employment across brewgis (count).',
    emp_office_services = 'Total Office Services Employment across brewgis (count).',
    emp_medical_services = 'Total Medical Services Employment across brewgis (count).',
    emp_public_admin = 'Total Public Administration Employment across brewgis (count).',
    emp_education = 'Total Education Employment across brewgis (count).',
    emp_manufacturing = 'Total Manufacturing Employment across brewgis (count).',
    emp_wholesale = 'Total Wholesale Employment across brewgis (count).',
    emp_transport_warehousing = 'Total Transport & Warehousing Employment across brewgis (count).',
    emp_utilities = 'Total Utilities Employment across brewgis (count).',
    emp_construction = 'Total Construction Employment across brewgis (count).',
    emp_agriculture = 'Total Agriculture Employment (Detailed) across brewgis (count).',
    emp_extraction = 'Total Extraction Employment across brewgis (count).',
    bldg_area_detsf_sl = 'Total Detached SF Small Lot Building Area across brewgis (sq ft).',
    bldg_area_detsf_ll = 'Total Detached SF Large Lot Building Area across brewgis (sq ft).',
    bldg_area_attsf = 'Total Attached SF Building Area across brewgis (sq ft).',
    bldg_area_mf = 'Total Multi-Family Building Area across brewgis (sq ft).',
    bldg_area_retail_services = 'Total Retail Services Building Area across brewgis (sq ft).',
    bldg_area_restaurant = 'Total Restaurant Building Area across brewgis (sq ft).',
    bldg_area_accommodation = 'Total Accommodation Building Area across brewgis (sq ft).',
    bldg_area_arts_entertainment = 'Total Arts & Entertainment Building Area across brewgis (sq ft).',
    bldg_area_other_services = 'Total Other Services Building Area across brewgis (sq ft).',
    bldg_area_office_services = 'Total Office Services Building Area across brewgis (sq ft).',
    bldg_area_public_admin = 'Total Public Administration Building Area across brewgis (sq ft).',
    bldg_area_education = 'Total Education Building Area across brewgis (sq ft).',
    bldg_area_medical_services = 'Total Medical Services Building Area across brewgis (sq ft).',
    bldg_area_transport_warehousing = 'Total Transport & Warehousing Building Area across brewgis (sq ft).',
    bldg_area_wholesale = 'Total Wholesale Building Area across brewgis (sq ft).',
    residential_irrigated_area = 'Total Residential Irrigated Area across brewgis (acres).',
    commercial_irrigated_area = 'Total Commercial Irrigated Area across brewgis (acres).',
    intersection_density = 'Total Intersection Density across brewgis (intersections per km2).',
    median_income = 'Total Median Household Income across brewgis ($ per year).',
    pct_minority = 'Total Percent People of Color across brewgis (% as 0-100).',
    pct_college_educated = 'Total Percent College-Educated across brewgis (% as 0-100).',
    cost_burden_pct = 'Total Cost-Burdened Households across brewgis (% as 0-100).',
    rent_burden_pct = 'Total Rent Burden (HH >30% income on rent) across brewgis (% as 0-100).'
  )
);

-- SACOG BrewGIS Totals — aggregate sums from the brewgis base canvas.
--
-- Computes COALESCE(SUM(col), 0) for every numeric BaseCanvasSchema column
-- in the brewgis base_canvas_reconciled output.

WITH totals AS (
    SELECT
        COALESCE(SUM(area_gross_acres), 0)::double precision AS area_gross_acres,
        COALESCE(SUM(area_parcel_acres), 0)::double precision AS area_parcel_acres,
        COALESCE(SUM(area_parcel_res_acres), 0)::double precision AS area_parcel_res_acres,
        COALESCE(SUM(area_parcel_emp_acres), 0)::double precision AS area_parcel_emp_acres,
        COALESCE(SUM(area_parcel_mixed_use_acres), 0)::double precision AS area_parcel_mixed_use_acres,
        COALESCE(SUM(area_parcel_no_use_acres), 0)::double precision AS area_parcel_no_use_acres,
        COALESCE(SUM(pop), 0)::double precision AS pop,
        COALESCE(SUM(hh), 0)::double precision AS hh,
        COALESCE(SUM(du), 0)::double precision AS du,
        COALESCE(SUM(du_detsf), 0)::double precision AS du_detsf,
        COALESCE(SUM(du_detsf_sl), 0)::double precision AS du_detsf_sl,
        COALESCE(SUM(du_detsf_ll), 0)::double precision AS du_detsf_ll,
        COALESCE(SUM(du_attsf), 0)::double precision AS du_attsf,
        COALESCE(SUM(du_mf), 0)::double precision AS du_mf,
        COALESCE(SUM(du_mf2to4), 0)::double precision AS du_mf2to4,
        COALESCE(SUM(du_mf5p), 0)::double precision AS du_mf5p,
        COALESCE(SUM(emp), 0)::double precision AS emp,
        COALESCE(SUM(emp_ret), 0)::double precision AS emp_ret,
        COALESCE(SUM(emp_off), 0)::double precision AS emp_off,
        COALESCE(SUM(emp_pub), 0)::double precision AS emp_pub,
        COALESCE(SUM(emp_ind), 0)::double precision AS emp_ind,
        COALESCE(SUM(emp_ag), 0)::double precision AS emp_ag,
        COALESCE(SUM(emp_military), 0)::double precision AS emp_military,
        COALESCE(SUM(emp_retail_services), 0)::double precision AS emp_retail_services,
        COALESCE(SUM(emp_restaurant), 0)::double precision AS emp_restaurant,
        COALESCE(SUM(emp_accommodation), 0)::double precision AS emp_accommodation,
        COALESCE(SUM(emp_arts_entertainment), 0)::double precision AS emp_arts_entertainment,
        COALESCE(SUM(emp_other_services), 0)::double precision AS emp_other_services,
        COALESCE(SUM(emp_office_services), 0)::double precision AS emp_office_services,
        COALESCE(SUM(emp_medical_services), 0)::double precision AS emp_medical_services,
        COALESCE(SUM(emp_public_admin), 0)::double precision AS emp_public_admin,
        COALESCE(SUM(emp_education), 0)::double precision AS emp_education,
        COALESCE(SUM(emp_manufacturing), 0)::double precision AS emp_manufacturing,
        COALESCE(SUM(emp_wholesale), 0)::double precision AS emp_wholesale,
        COALESCE(SUM(emp_transport_warehousing), 0)::double precision AS emp_transport_warehousing,
        COALESCE(SUM(emp_utilities), 0)::double precision AS emp_utilities,
        COALESCE(SUM(emp_construction), 0)::double precision AS emp_construction,
        COALESCE(SUM(emp_agriculture), 0)::double precision AS emp_agriculture,
        COALESCE(SUM(emp_extraction), 0)::double precision AS emp_extraction,
        COALESCE(SUM(bldg_area_detsf_sl), 0)::double precision AS bldg_area_detsf_sl,
        COALESCE(SUM(bldg_area_detsf_ll), 0)::double precision AS bldg_area_detsf_ll,
        COALESCE(SUM(bldg_area_attsf), 0)::double precision AS bldg_area_attsf,
        COALESCE(SUM(bldg_area_mf), 0)::double precision AS bldg_area_mf,
        COALESCE(SUM(bldg_area_retail_services), 0)::double precision AS bldg_area_retail_services,
        COALESCE(SUM(bldg_area_restaurant), 0)::double precision AS bldg_area_restaurant,
        COALESCE(SUM(bldg_area_accommodation), 0)::double precision AS bldg_area_accommodation,
        COALESCE(SUM(bldg_area_arts_entertainment), 0)::double precision AS bldg_area_arts_entertainment,
        COALESCE(SUM(bldg_area_other_services), 0)::double precision AS bldg_area_other_services,
        COALESCE(SUM(bldg_area_office_services), 0)::double precision AS bldg_area_office_services,
        COALESCE(SUM(bldg_area_public_admin), 0)::double precision AS bldg_area_public_admin,
        COALESCE(SUM(bldg_area_education), 0)::double precision AS bldg_area_education,
        COALESCE(SUM(bldg_area_medical_services), 0)::double precision AS bldg_area_medical_services,
        COALESCE(SUM(bldg_area_transport_warehousing), 0)::double precision AS bldg_area_transport_warehousing,
        COALESCE(SUM(bldg_area_wholesale), 0)::double precision AS bldg_area_wholesale,
        COALESCE(SUM(residential_irrigated_area), 0)::double precision AS residential_irrigated_area,
        COALESCE(SUM(commercial_irrigated_area), 0)::double precision AS commercial_irrigated_area,
        COALESCE(SUM(intersection_density), 0)::double precision AS intersection_density,
        COALESCE(SUM(median_income), 0)::double precision AS median_income,
        COALESCE(SUM(pct_minority), 0)::double precision AS pct_minority,
        COALESCE(SUM(pct_college_educated), 0)::double precision AS pct_college_educated,
        COALESCE(SUM(cost_burden_pct), 0)::double precision AS cost_burden_pct,
        COALESCE(SUM(rent_burden_pct), 0)::double precision AS rent_burden_pct
    FROM brewgis.sacog.base_canvas_reconciled
)
SELECT
    'brewgis'::text AS source,
    area_gross_acres,
    area_parcel_acres,
    area_parcel_res_acres,
    area_parcel_emp_acres,
    area_parcel_mixed_use_acres,
    area_parcel_no_use_acres,
    pop,
    hh,
    du,
    du_detsf,
    du_detsf_sl,
    du_detsf_ll,
    du_attsf,
    du_mf,
    du_mf2to4,
    du_mf5p,
    emp,
    emp_ret,
    emp_off,
    emp_pub,
    emp_ind,
    emp_ag,
    emp_military,
    emp_retail_services,
    emp_restaurant,
    emp_accommodation,
    emp_arts_entertainment,
    emp_other_services,
    emp_office_services,
    emp_medical_services,
    emp_public_admin,
    emp_education,
    emp_manufacturing,
    emp_wholesale,
    emp_transport_warehousing,
    emp_utilities,
    emp_construction,
    emp_agriculture,
    emp_extraction,
    bldg_area_detsf_sl,
    bldg_area_detsf_ll,
    bldg_area_attsf,
    bldg_area_mf,
    bldg_area_retail_services,
    bldg_area_restaurant,
    bldg_area_accommodation,
    bldg_area_arts_entertainment,
    bldg_area_other_services,
    bldg_area_office_services,
    bldg_area_public_admin,
    bldg_area_education,
    bldg_area_medical_services,
    bldg_area_transport_warehousing,
    bldg_area_wholesale,
    residential_irrigated_area,
    commercial_irrigated_area,
    intersection_density,
    median_income,
    pct_minority,
    pct_college_educated,
    cost_burden_pct,
    rent_burden_pct
FROM totals
