"""Tests for the SACOG base canvas comparison report, including equity validation."""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path
from unittest.mock import MagicMock
from unittest.mock import patch

import pytest

# Stubs for modules that the management command imports but are not needed
# at test time (we only test report text generation).
# These are installed during the test class lifecycle and restored after.
# NOTE: pandas, geopandas, shapely, and pyogrio are NOT stubbed — they are
# available in the Docker test environment and must be importable for
# dlt/pandas isinstance checks to work.
_STUB_MODS: dict[str, MagicMock] = {
    "dbt.cli.main": MagicMock(),
    "dbt.contracts.results": MagicMock(),
    "brewgis.workspace.analysis.dbt_runner": MagicMock(),
    "soda_core.contracts": MagicMock(),
}


@pytest.mark.django_db
class TestCompareSacogReport:
    """Tests for the comparison report generated by compare_sacog_basemap."""

    _ORIG_MODS: dict[str, object] = {}

    @classmethod
    def setup_class(cls) -> None:
        """Install stub modules before importing Command."""
        for mod_name in _STUB_MODS:
            cls._ORIG_MODS[mod_name] = sys.modules.get(mod_name)
        sys.modules.update(_STUB_MODS)
        # pylint: disable-next=import-outside-toplevel
        from brewgis.workspace.management.commands.compare_sacog_basemap import Command

        cls._cmd_cls = Command

    @classmethod
    def teardown_class(cls) -> None:
        """Restore original modules to avoid polluting subsequent tests."""
        for mod_name, mod in cls._ORIG_MODS.items():
            if mod is None:
                sys.modules.pop(mod_name, None)
            else:
                sys.modules[mod_name] = mod
        cls._ORIG_MODS.clear()

    def _build_report(
        self,
        ref: dict[str, float],
        brew: dict[str, float],
        report_path: Path,
    ) -> str:
        """Run _generate_report through the management command with test data."""
        cmd = self._cmd_cls()
        with (
            patch.object(cmd, "stdout", create=True),
            patch(
                "brewgis.workspace.management.commands.compare_sacog_basemap.REPORT_PATH",
                report_path,
            ),
        ):
            weighted_means: dict[str, float] = {
                "median_income": 75430.0,
                "pct_minority": 55.2,
                "pct_college_educated": 34.8,
                "cost_burden_pct": 42.0,
                "rent_burden_pct": 35.0,
            }
            cmd._generate_report(  # noqa: SLF001
                ref=ref,
                brew=brew,
                etl_result={},
                quick=False,
                limit=None,
                correlations=None,
                weighted_means=weighted_means,
            )
        return report_path.read_text(encoding="utf-8")

    def test_equity_validation_section_has_header(self) -> None:
        """Equity validation section header is present."""
        ref: dict[str, float] = {}
        brew: dict[str, float] = {"pop": 100000.0}

        with tempfile.NamedTemporaryFile(suffix=".md", delete=False, mode="w") as f:
            path = Path(f.name)

        try:
            text = self._build_report(ref, brew, path)
            assert "## 5. Equity Column Validation" in text
        finally:
            path.unlink(missing_ok=True)

    def test_equity_validation_with_acs_comparison(self) -> None:
        """Equity columns produce expected ACS comparison rows with correct values."""
        ref: dict[str, float] = {}
        # brew values simulate pop-weighted sums across all parcels.
        # pct columns are stored as 0-100 percentage values.
        # brew_val / pop gives the pop-weighted average.
        brew: dict[str, float] = {
            "pop": 500000.0,
            "median_income": 35_000_000_000.0,  # → $70,000
            "pct_minority": 27_500_000.0,  # → 55.0%
            "pct_college_educated": 15_000_000.0,  # → 30.0%
            "cost_burden_pct": 20_000_000.0,  # → 40.0%
        }

        with tempfile.NamedTemporaryFile(suffix=".md", delete=False, mode="w") as f:
            path = Path(f.name)

        try:
            text = self._build_report(ref, brew, path)
            assert (
                "| median_income | $75,430 | $75,430 | $+0 | ACS B19013 (2022), median $ |"
                in text
            )
            assert (
                "| pct_minority | 55.2% | 55.2% | +0.0pp | ACS B03002 (2022), % non-White |"
                in text
            )
            assert (
                "| pct_college_educated | 34.8% | 34.8% | +0.0pp | ACS B15003 (2022), % Bachelor's+ |"
                in text
            )
            assert (
                "| cost_burden_pct | 42.0% | 42.0% | +0.0pp | ACS B25070+B25091 (2022), % >30% income |"
                in text
            )
        finally:
            path.unlink(missing_ok=True)

    def test_equity_validation_shows_brew_wavg(self) -> None:
        """Equity columns show area-weighted average values alongside ACS estimates."""
        ref: dict[str, float] = {}
        brew: dict[str, float] = {
            "median_income": 50000.0,
            "pct_minority": 100.0,
        }

        with tempfile.NamedTemporaryFile(suffix=".md", delete=False, mode="w") as f:
            path = Path(f.name)

        try:
            text = self._build_report(ref, brew, path)
            assert "| median_income | $75,430 | $75,430 | $+0 |" in text
            assert "| pct_minority | 55.2% | 55.2% | +0.0pp |" in text
        finally:
            path.unlink(missing_ok=True)

    def test_equity_validation_all_acs_columns_present(self) -> None:
        """All ACS comparison columns appear."""
        ref: dict[str, float] = {}
        brew: dict[str, float] = {
            "pop": 100000.0,
            "median_income": 7_000_000_000.0,
        }

        with tempfile.NamedTemporaryFile(suffix=".md", delete=False, mode="w") as f:
            path = Path(f.name)

        try:
            text = self._build_report(ref, brew, path)
            assert "| median_income |" in text
            assert "| pct_minority |" in text
            assert "| pct_college_educated |" in text
            assert "| cost_burden_pct |" in text
        finally:
            path.unlink(missing_ok=True)

    def test_notes_renumbered_to_section_6(self) -> None:
        """Notes section is renumbered from 5 to 6 after equity section insertion."""
        ref: dict[str, float] = {}
        brew: dict[str, float] = {"pop": 100000.0}

        with tempfile.NamedTemporaryFile(suffix=".md", delete=False, mode="w") as f:
            path = Path(f.name)

        try:
            text = self._build_report(ref, brew, path)
            assert "## 6. Notes" in text
            assert "## 5. Notes" not in text
        finally:
            path.unlink(missing_ok=True)

    def test_equity_shows_raw_values(self) -> None:
        """Zero population does not affect equity section display (pop not used)."""
        ref: dict[str, float] = {}
        brew: dict[str, float] = {
            "pop": 0.0,
            "median_income": 50000.0,
            "pct_minority": 100.0,
        }

        with tempfile.NamedTemporaryFile(suffix=".md", delete=False, mode="w") as f:
            path = Path(f.name)

        try:
            text = self._build_report(ref, brew, path)
            assert "| median_income | $75,430 | $75,430 | $+0 |" in text
            assert "| pct_minority | 55.2% | 55.2% | +0.0pp |" in text
        finally:
            path.unlink(missing_ok=True)
