"""Tests for the SACOG base canvas comparison report, including equity validation."""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path
from unittest.mock import MagicMock
from unittest.mock import patch

# Prevent import chain failures: the management command transitively imports
# brewgis.workspace.services → spatial_allocator → geopandas/pandas/shapely,
# none of which are installed in the test environment.
_STUB_MODS = {
    "geopandas": MagicMock(),
    "geopandas.io": MagicMock(),
    "pandas": MagicMock(),
    "shapely": MagicMock(),
    "shapely.geometry": MagicMock(),
    "shapely.ops": MagicMock(),
    "shapely.strtree": MagicMock(),
    "shapely.wkt": MagicMock(),
    "pyogrio": MagicMock(),
}


class _StubGeoDataFrame:
    """GeoDataFrame stub that accepts constructor args and creates mock attrs on demand."""

    def __init__(self, data=None, *args, geometry=None, crs=None, **kwargs):
        pass

    def __getattr__(self, name):
        if name.startswith("_"):
            raise AttributeError(name)
        from unittest.mock import MagicMock

        return MagicMock()

    def set_geometry(self, col, inplace=None):
        return self

    def set_crs(self, crs, inplace=None):
        return self


_GEO_DF_CLS = _StubGeoDataFrame
_STUB_MODS["geopandas"].GeoDataFrame = _GEO_DF_CLS
_STUB_MODS["geopandas"].geodataframe = MagicMock()
_STUB_MODS["geopandas"].geodataframe.GeoDataFrame = _GEO_DF_CLS
# Save originals and install stubs temporarily
_ORIG_MODS = {}
for mod_name in _STUB_MODS:
    _ORIG_MODS[mod_name] = sys.modules.get(mod_name)
sys.modules.update(_STUB_MODS)

# Now safe to import — these will re-use our stubs
from brewgis.workspace.management.commands.compare_sacog_basemap import Command  # noqa: E402 I001


class TestCompareSacogReport:
    """Tests for the comparison report generated by compare_sacog_basemap."""

    def _fake_etl_result(self) -> dict:
        return {"elapsed": 42.5, "rows": 1000}

    def _build_report(
        self,
        ref: dict[str, float],
        brew: dict[str, float],
        report_path: Path,
    ) -> str:
        """Run _generate_report with patched REPORT_PATH and return text."""
        cmd = Command()
        with (
            patch.object(cmd, "stdout", create=True),
            patch(
                "brewgis.workspace.management.commands.compare_sacog_basemap.REPORT_PATH",
                report_path,
            ),
        ):
            cmd._generate_report(  # noqa: SLF001
                ref=ref,
                brew=brew,
                etl_result=self._fake_etl_result(),
                quick=False,
                limit=None,
            )
        return report_path.read_text(encoding="utf-8")

    def test_equity_validation_section_has_header(self) -> None:
        """Equity validation section header is present."""
        ref: dict[str, float] = {}
        brew: dict[str, float] = {"pop": 100000.0}

        with tempfile.NamedTemporaryFile(suffix=".md", delete=False, mode="w") as f:
            path = Path(f.name)

        try:
            text = self._build_report(ref, brew, path)
            assert "## 5. Equity Column Validation" in text
        finally:
            path.unlink(missing_ok=True)

    def test_equity_validation_with_acs_comparison(self) -> None:
        """Equity columns produce expected ACS comparison rows with correct values."""
        ref: dict[str, float] = {}
        # brew values simulate pop-weighted sums across all parcels.
        # pct columns are stored as 0-100 percentage values.
        # brew_val / pop gives the pop-weighted average.
        brew: dict[str, float] = {
            "pop": 500000.0,
            "median_income": 35_000_000_000.0,  # → $70,000
            "pct_minority": 27_500_000.0,  # → 55.0%
            "pct_college_educated": 15_000_000.0,  # → 30.0%
            "cost_burden_pct": 20_000_000.0,  # → 40.0%
        }

        with tempfile.NamedTemporaryFile(suffix=".md", delete=False, mode="w") as f:
            path = Path(f.name)

        try:
            text = self._build_report(ref, brew, path)
            assert (
                "| median_income | $35,000,000,000 | $75,430 | ACS B19013 (2022), median $ |"
                in text
            )
            assert (
                "| pct_minority | 27,500,000.0 | 55.2% | ACS B03002 (2022), % non-White |"
                in text
            )
            assert (
                "| pct_college_educated | 15,000,000.0 | 34.8% | ACS B15003 (2022), % Bachelor's+ |"
                in text
            )
            assert (
                "| cost_burden_pct | 20,000,000.0 | 42.0% | ACS B25070+B25091 (2022), % >30% income |"
                in text
            )
        finally:
            path.unlink(missing_ok=True)

    def test_equity_validation_shows_raw_sum(self) -> None:
        """Equity columns show raw SUM values directly."""
        ref: dict[str, float] = {}
        brew: dict[str, float] = {
            "median_income": 50000.0,
            "pct_minority": 100.0,
        }

        with tempfile.NamedTemporaryFile(suffix=".md", delete=False, mode="w") as f:
            path = Path(f.name)

        try:
            text = self._build_report(ref, brew, path)
            assert "| median_income ⚠ | $50,000 | $75,430 |" in text
            assert "| pct_minority | 100.0 | 55.2% |" in text
        finally:
            path.unlink(missing_ok=True)

    def test_equity_validation_skips_missing_columns(self) -> None:
        """Missing equity columns are skipped from the report."""
        ref: dict[str, float] = {}
        brew: dict[str, float] = {
            "pop": 100000.0,
            "median_income": 7_000_000_000.0,
        }

        with tempfile.NamedTemporaryFile(suffix=".md", delete=False, mode="w") as f:
            path = Path(f.name)

        try:
            text = self._build_report(ref, brew, path)
            assert "| median_income |" in text
            assert "| pct_minority |" not in text
            assert "| pct_college_educated |" not in text
            assert "| cost_burden_pct |" not in text
        finally:
            path.unlink(missing_ok=True)

    def test_notes_renumbered_to_section_6(self) -> None:
        """Notes section is renumbered from 5 to 6 after equity section insertion."""
        ref: dict[str, float] = {}
        brew: dict[str, float] = {"pop": 100000.0}

        with tempfile.NamedTemporaryFile(suffix=".md", delete=False, mode="w") as f:
            path = Path(f.name)

        try:
            text = self._build_report(ref, brew, path)
            assert "## 6. Notes" in text
            assert "## 5. Notes" not in text
        finally:
            path.unlink(missing_ok=True)

    def test_equity_shows_raw_values(self) -> None:
        """Zero population does not affect raw sum display."""
        ref: dict[str, float] = {}
        brew: dict[str, float] = {
            "pop": 0.0,
            "median_income": 50000.0,
            "pct_minority": 100.0,
        }

        with tempfile.NamedTemporaryFile(suffix=".md", delete=False, mode="w") as f:
            path = Path(f.name)

        try:
            text = self._build_report(ref, brew, path)
            assert "| median_income ⚠ | $50,000 | $75,430 |" in text
            assert "| pct_minority | 100.0 | 55.2% |" in text
        finally:
            path.unlink(missing_ok=True)
