brewgis:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: rADfmsnMjDXKephNGWFkfdPkuSAjdASF
      password: glm5bKLmVKkfdJaM9qkDREdor4y8uSEJZKZvLVwP5jeEX6YSnw6DnNG9EYvupSlg
      dbname: brewgis
      schema: public
